"""Build ps225/prayed.json, draft 1 (canticle of Habakkuk, Hab 3:2-19, DO number 225).
python3.13 research/psalterium/ps225/build_v1.py"""
import json
from pathlib import Path

here = Path(__file__).resolve().parent

verses = {
    '3:2a': 'Senhor, {ouvi1} {auditio}, * e temi.',
    '3:2b': 'Senhor, a vossa obra, * no meio dos anos, {vivifica}:',
    '3:2c': 'No meio dos anos {notum}: * quando estiverdes irado, vos lembrareis da misericórdia.',
    '3:3a': 'Deus virá do sul, * e o Santo, do monte Farã:',
    '3:3b': 'A sua glória cobriu os céus: * e a terra está cheia do seu louvor.',
    '3:4a': 'O seu esplendor será como a luz: * {cornua} nas suas mãos:',
    '3:4b': 'Ali está escondida a sua força: * diante da sua face irá a morte.',
    '3:5b': 'E o {diabolus} sairá diante dos seus pés. * {stetit}, e mediu a terra.',
    '3:6b': 'Olhou, e dissolveu as nações: * e foram quebrados os montes {saeculi}.',
    '3:6c': '{incurvati} as colinas do mundo, * {ab_itineribus} da sua eternidade.',
    '3:7': '{pro_iniquitate} vi as tendas da Etiópia, * serão perturbadas {pelles} da terra de Madiã.',
    '3:8a': 'Acaso estais irado {in_flum1}, Senhor? * ou {in_flum2} o vosso furor? ou {in_mari} a vossa indignação?',
    '3:8b': 'Vós que montareis sobre os vossos cavalos: * e {quadrigae} são salvação.',
    '3:9a': '{suscitans} o vosso arco: * os juramentos que {locutus} às tribos.',
    '3:9b': '{scindes} os rios da terra: † viram-vos, e {doluerunt} os montes: * {gurges} das águas passou.',
    '3:10b': 'O abismo fez ouvir a sua voz: * a altura levantou as suas mãos.',
    '3:11': 'O sol e a lua {steterunt} na sua morada, * na luz das vossas setas, irão no esplendor da vossa lança {fulgurantis}.',
    '3:12': '{fremitu} calcareis aos pés a terra: * e no furor {obstupefacies} as nações.',
    '3:13a': 'Saístes para a salvação do vosso povo: * para a salvação com o vosso Cristo.',
    '3:13b': 'Feristes a cabeça da casa do ímpio: * {denudasti} o seu fundamento até o pescoço.',
    '3:14a': 'Amaldiçoastes os seus cetros, † a cabeça dos seus guerreiros, * que vinham como um {turbo} para me dispersar.',
    '3:14b': 'A exultação deles * {sicut} de quem devora o pobre às escondidas.',
    '3:15': 'Fizestes no mar um caminho para os vossos cavalos, * na lama das muitas águas.',
    '3:16a': '{ouvi2}, e o meu ventre se perturbou: * à voz estremeceram os meus lábios.',
    '3:16b': 'Que entre a podridão nos meus ossos, * e que {scateat} debaixo de mim.',
    '3:16c': 'Para que eu repouse no dia da tribulação: * para que eu suba ao nosso povo cingido.',
    '3:17a': 'Pois a figueira não florescerá: * e não haverá {germen} nas vinhas.',
    '3:17b': 'Mentirá {opus} da oliveira: * e os campos não trarão alimento.',
    '3:17c': 'O rebanho será cortado do aprisco: * e não haverá {armentum} nos estábulos.',
    '3:18': 'Eu, porém, {gaudebo} no Senhor: * e exultarei em Deus, {jesu}.',
    '3:19a': '{deus_dominus} é a minha força: * e {ponet} os meus pés como os {cervorum}.',
    '3:19b': 'E sobre as minhas alturas {victor} * {canentem}.',
}


def opt(label, forms, note, frm):
    return {'label': label, 'forms': forms, 'note': note, 'from': frm}


def dec(id_, refs, latin, kind, why, options):
    return {'id': id_, 'refs': refs, 'latin': latin, 'kind': kind, 'why': why, 'options': options}


decisions = [
    dec('auditio', ['3:2a'], 'audívi auditiónem tuam', 'word',
        "The Latin plays the verb against its own noun, and *auditio* is 'a report, a thing heard' (L&S). *Tuam* leaves it open whether the report comes from God or is about him (DRB 'thy hearing'; LXX τὴν ἀκοήν σου). The glossary's open row *audítio (a report) → notícia* (111:7a) said Hab 3:2 would decide for itself. *A vossa notícia* keeps the row's word and the possessive's openness (news from you / news of you). It loses the root echo with *ouvi*, which no plain noun keeps. MS1932 *a tua palavra* interprets (a word spoken), and so does the DM1962's *o teu oráculo* (from the Hebrew). The CNBB LH has *vossa mensagem*.",
        [opt('a vossa notícia', {'auditio': 'a vossa notícia'}, 'Draft; the glossary row (111:7a). Open between report from God and report about God, as the Latin.', 'glossary'),
         opt('o vosso anúncio', {'auditio': 'o vosso anúncio'}, 'A proclamation; leans to a report made by God.', 'draft'),
         opt('o que fizestes ouvir', {'auditio': 'o que fizestes ouvir'}, "Keeps the hearing root (cf. 215's *audítum fácere → fazer ouvir*); it decides that God is the speaker.", 'draft'),
         opt('a vossa palavra', {'auditio': 'a vossa palavra'}, 'MS1932. Interprets, and takes *verbum*’s word (D15).', 'MS1932')]),
    dec('ouvi', ['3:2a', '3:16a'], 'audívi … Audívi', 'grammar',
        "Both verses open with the first-person perfect *audívi*. In a psalter that says *vós* to God, a bare *Ouvi* at the head of a line is also the *vós* imperative ('Hear!'), the homograph of rule 3 in reverse: in 3:16a the whole verse would first be heard as a command to God. The subject pronoun Portuguese allows (D2) is supplied in both places, so they stay alike. MS1932 has *eu ouvi* in both verses.",
        [opt('eu ouvi … Eu ouvi', {'ouvi1': 'eu ouvi', 'ouvi2': 'Eu ouvi'}, 'Draft; MS1932. The pronoun rules out the imperative.', 'draft'),
         opt('ouvi … Ouvi', {'ouvi1': 'ouvi', 'ouvi2': 'Ouvi'}, 'The bare verb, as the Latin; open to being heard as "Hear!" (rule 3).', 'draft')]),
    dec('vivifica', ['3:2b'], 'opus tuum … vivífica illud', 'glossary',
        "The glossary's row *vivificáre → vivificar* (118, 40:3, 70:20; safe at the *vós* imperative). The Latin puts the object first and takes it up again with *illud*; the resumptive pronoun is kept as the enclitic *-a*. The blind reader of Ps 118 and Ps 40 did not know *vivificar*, and MS1932 has *faze viver*; the row keeps *dai … vida* as its option.",
        [opt('vivificai-a', {'vivifica': 'vivificai-a'}, 'Draft; the glossary row.', 'glossary'),
         opt('dai-lhe vida', {'vivifica': 'dai-lhe vida'}, "The row's plain option (MS1932 *faze viver*).", 'MS1932'),
         opt('fazei-a viver', {'vivifica': 'fazei-a viver'}, 'MS1932, word for word.', 'MS1932')]),
    dec('notum', ['3:2c'], 'notum fácies', 'glossary',
        "The glossary's row *notum fácere → fazer conhecer* (97:2, 76:15, 15:11, 102:7). *Notum* is neuter and has no noun: it points back to *opus* (DRB 'thou shalt make it known'), so the object pronoun *a* (the work) is supplied, as Portuguese needs one. The stylist of Ps 97 asked for *dar a conhecer*; the row kept *fazer conhecer* for the repetition across psalms.",
        [opt('a fareis conhecer', {'notum': 'a fareis conhecer'}, 'Draft; the glossary row.', 'glossary'),
         opt('a dareis a conhecer', {'notum': 'a dareis a conhecer'}, "The idiom; the row's option.", 'glossary'),
         opt('a tornareis conhecida', {'notum': 'a tornareis conhecida'}, 'MS1932 *tu a farás notória*; the CNBB LH *tornai-a conhecida*.', 'MS1932')]),
    dec('cornua', ['3:4a'], 'córnua in mánibus ejus', 'word',
        "Jerome wrote horns, as the Hebrew's word is horns (it can mean rays, which is what modern versions read) and as the LXX κέρατα. The glossary keeps *cornu → chifre*, the concrete image (rule 5; 17:3c, 111:9). The line is verbless in the Latin and stays verbless. MS1932 *raios de glória* and the DM1962 and CNBB *raios* all explain the image away from the Hebrew.",
        [opt('chifres', {'cornua': 'chifres'}, 'Draft; the glossary; DRB "horns".', 'glossary'),
         opt('raios', {'cornua': 'raios'}, "MS1932, DM1962, CNBB LH. The Hebrew's sense; it drops the Latin's image.", 'MS1932')]),
    dec('diabolus', ['3:5b'], 'egrediétur diábolus', 'glossary',
        "Jerome's *diábolus* (the Hebrew's is a plague-demon; LXX 'and his feet will go out in sandals'). The open glossary row *diábolus → diabo* (108:6) keeps the Latin's loanword; *demônio* is *dæmónium*'s (95:5). MS1932 *o demônio*.",
        [opt('diabo', {'diabolus': 'diabo'}, 'Draft; the glossary row.', 'glossary'),
         opt('demônio', {'diabolus': 'demônio'}, "MS1932; the glossary keeps it for *dæmónium*.", 'MS1932')]),
    dec('stetit', ['3:5b'], '(6a) Stetit, et mensus est terram', 'word',
        "God is the subject. *Deus stetit in synagóga* (81:1) is *Deus se pôs de pé*, and 105:30 *stetit Phínees* is *se pôs de pé*; the same build is kept. The *stare* rows split by context (*estar de pé*, *deter-se* on a road). MS1932 *Parou*.",
        [opt('Pôs-se de pé', {'stetit': 'Pôs-se de pé'}, 'Draft; 81:1, 105:30.', 'draft'),
         opt('Parou', {'stetit': 'Parou'}, 'MS1932. Shorter; loses the standing.', 'MS1932'),
         opt('Deteve-se', {'stetit': 'Deteve-se'}, 'The 1:1 row (stopping on a road).', 'glossary')]),
    dec('saeculi', ['3:6b'], 'montes sǽculi', 'word',
        "A genitive of age: the mountains of the age, i.e. ancient ones (DRB 'the ancient mountains'). *Do século* would be heard as 'of the century'. *Seculares* is MS1932's word and keeps the root; in Brazil it means age-old (*árvores seculares*), though it can also mean 'lay'. 142:3b *mórtui sǽculi* took *os mortos de outrora*, which does not suit mountains that still stand. The Latin's *æternitátis* in the next line takes *eterno*, so *eternos* is not used here.",
        [opt('seculares', {'saeculi': 'seculares'}, 'Draft; MS1932 *montanhas seculares*.', 'MS1932'),
         opt('antigos', {'saeculi': 'antigos'}, "DRB 'ancient'. Plainer; drops the root.", 'DRB'),
         opt('de outrora', {'saeculi': 'de outrora'}, '142:3b *mórtui sǽculi*.', 'glossary')]),
    dec('incurvati', ['3:6c'], 'Incurváti sunt colles mundi, * ab itinéribus æternitátis ejus', 'grammar',
        "*Ab* with the passive marks the agent or cause: the hills were bowed *by* the goings of his eternity (DRB 'by the journeys'). An active *Curvaram-se … pelos caminhos* would be heard as 'along the roads'; the Portuguese passive keeps *pelos* as the agent. *Iter → caminho* is the open glossary row (1:6, 49:23). MS1932 *curvaram-se sob os passos da sua eternidade* changes the preposition and the noun. The Latin's line keeps its comma before the asterisk.",
        [opt('Foram curvadas … pelos caminhos', {'incurvati': 'Foram curvadas', 'ab_itineribus': 'pelos caminhos'}, 'Draft. The passive marks *pelos* as the agent.', 'draft'),
         opt('Curvaram-se … sob os caminhos', {'incurvati': 'Curvaram-se', 'ab_itineribus': 'sob os caminhos'}, 'MS1932 (*sob os passos*). Changes the preposition.', 'MS1932'),
         opt('Curvaram-se … diante dos caminhos', {'incurvati': 'Curvaram-se', 'ab_itineribus': 'diante dos caminhos'}, 'Makes the hills bow in homage; the Latin does not say so.', 'draft')]),
    dec('pro_iniquitate', ['3:7'], 'Pro iniquitáte vidi', 'ambiguity',
        "*Pro* is 'because of, in return for' (DRB 'for their iniquity', supplying *their*). Whose iniquity the Latin does not say, and the draft does not either. *Pela iniquidade vi* could be heard as 'through iniquity I saw'; *Por causa da* is plain. MS1932 *na aflição* follows the Hebrew.",
        [opt('Por causa da iniquidade', {'pro_iniquitate': 'Por causa da iniquidade'}, 'Draft.', 'draft'),
         opt('Pela iniquidade', {'pro_iniquitate': 'Pela iniquidade'}, 'Shorter; can be heard as the means of seeing.', 'draft'),
         opt('Por causa da sua iniquidade', {'pro_iniquitate': 'Por causa da sua iniquidade'}, 'DRB; supplies an owner the Latin lacks.', 'DRB')]),
    dec('pelles', ['3:7'], 'pelles terræ Mádian', 'glossary',
        "The skins of the tents, parallel to *tentória*. The glossary row *pellis → pele* (103:2 *como uma pele*) keeps the image and does not explain it as a tent (DRB 'curtains', MS1932 *pavilhões*). Next to *tendas* the ear can take the skins as tent-cloths.",
        [opt('as peles', {'pelles': 'as peles'}, 'Draft; the glossary row.', 'glossary'),
         opt('as tendas de peles', {'pelles': 'as tendas de peles'}, 'Explains the image; supplies a noun.', 'draft'),
         opt('os pavilhões', {'pelles': 'os pavilhões'}, 'MS1932, DM1962. Another word.', 'MS1932')]),
    dec('in_fluminibus', ['3:8a'], 'in flumínibus … in flumínibus … in mari', 'ambiguity',
        "*In* + ablative is 'in' before it is 'against'. The Latin leaves open whether the wrath is aimed at the rivers or shows itself in them (the storm-theophany). DRB 'with the rivers', MS1932 *contra os rios*. The draft keeps the Latin's preposition, the same three times. *Iratus es* → *estais irado*, the copula build of 79:5 and 84:6, and the same participle as 3:2c *irátus fúeris → estiverdes irado*.",
        [opt('nos rios … nos rios … no mar', {'in_flum1': 'nos rios', 'in_flum2': 'nos rios', 'in_mari': 'no mar'}, "Draft. The Latin's preposition, three times.", 'draft'),
         opt('contra os rios … contra os rios … contra o mar', {'in_flum1': 'contra os rios', 'in_flum2': 'contra os rios', 'in_mari': 'contra o mar'}, 'MS1932, DM1962. Decides for hostility.', 'MS1932')]),
    dec('quadrigae', ['3:8b'], 'et quadrígæ tuæ salvátio', 'word',
        "*Quadríga* is a four-horse chariot; the Latin chose that word, not *currus* (19:8 *carros de guerra*). *Quadrigas* is a Portuguese word, though less common. The line is verbless; *são* is supplied (grammar). *Salvátio → salvação*, as *salus* in 3:13a (D6 merges the family). *Qui ascéndes* is future: *montareis*; *ascéndere equos → montar* is 75:7's row, and *super* is kept as *sobre*.",
        [opt('as vossas quadrigas', {'quadrigae': 'as vossas quadrigas'}, "Draft; the Latin's word.", 'draft'),
         opt('os vossos carros', {'quadrigae': 'os vossos carros'}, 'DRB "chariots"; MS1932 *carroças*. Plainer.', 'DRB')]),
    dec('suscitans', ['3:9a'], 'Súscitans suscitábis arcum tuum', 'word',
        "The Latin doubles the verb (participle + future), the Hebrew's emphasis carried over word for word; rule 2 keeps a repetition the Latin has. *Suscitáre → levantar* is the open glossary row (112:7; the cognate *suscitar* means 'provoke' in Brazil). DRB 'Thou wilt surely take up' and MS1932 *tomarás com denodo* resolve the doubling.",
        [opt('Levantando, levantareis', {'suscitans': 'Levantando, levantareis'}, "Draft; the Latin's doubling kept; the glossary row.", 'draft'),
         opt('Certamente levantareis', {'suscitans': 'Certamente levantareis'}, 'DRB. The sense of the doubling, not its form.', 'DRB'),
         opt('Despertando, despertareis', {'suscitans': 'Despertando, despertareis'}, "*Suscitáre*'s root sense 'rouse'; *despertar* is *excitáre*'s.", 'draft')]),
    dec('locutus', ['3:9a'], 'juraménta tríbubus quæ locútus es', 'word',
        "*Loqui* is *falar* in the psalter (88:20 *falastes em visão*), but *falar juramentos* is not Portuguese. *Proferir* is the verb Portuguese uses for uttering an oath and says only 'spoke out'. MS1932 *fizestes* makes the oaths a deed.",
        [opt('proferistes', {'locutus': 'proferistes'}, 'Draft.', 'draft'),
         opt('falastes', {'locutus': 'falastes'}, "The psalter's verb; a calque here.", 'glossary'),
         opt('fizestes', {'locutus': 'fizestes'}, 'MS1932.', 'MS1932')]),
    dec('scindes', ['3:9b'], 'Flúvios scindes terræ', 'word',
        "*Scíndere* is 'cleave, split' (L&S). *Fender* is that. MS1932 *dividirás* is gentler. *Flúvius* and *flumen* are both *rio* (73:15, 23:2), as the Hebrew has one word.",
        [opt('Fendereis', {'scindes': 'Fendereis'}, 'Draft.', 'draft'),
         opt('Dividireis', {'scindes': 'Dividireis'}, 'MS1932.', 'MS1932')]),
    dec('doluerunt', ['3:9b'], 'vidérunt te, et doluérunt montes', 'word',
        "*Dolére* is to feel pain (DRB 'were grieved'; MS1932 *ficaram traspassados de dor*). *Sentiram dor* keeps the body's pain; *doeram-se* is heard more as 'took offence'.",
        [opt('sentiram dor', {'doluerunt': 'sentiram dor'}, 'Draft.', 'draft'),
         opt('se doeram', {'doluerunt': 'se doeram'}, 'Shorter; leans to grief or offence.', 'draft')]),
    dec('gurges', ['3:9b'], 'gurges aquárum tránsiit', 'word',
        "*Gurges* is a whirlpool, an abyss, a flood (L&S). *Abismo* is *abýssus*'s, which comes in the next line. *Redemoinho* is the plain word for water that whirls. *Voragem* is the exact word but literary. DRB 'the great body of waters', MS1932 *uma tromba de água*.",
        [opt('o redemoinho', {'gurges': 'o redemoinho'}, 'Draft.', 'draft'),
         opt('a voragem', {'gurges': 'a voragem'}, 'Exact; literary.', 'draft'),
         opt('a torrente', {'gurges': 'a torrente'}, "Takes *torrens*'s word.", 'draft')]),
    dec('steterunt', ['3:11'], 'Sol, et luna stetérunt in habitáculo suo', 'word',
        "The sun and moon stood still; *pôr-se de pé* (3:6a, God) does not suit them. The *stare* row for stopping (1:1 *não se deteve*) is used. *Habitáculum → morada* (D44).",
        [opt('detiveram-se', {'steterunt': 'detiveram-se'}, 'Draft; the 1:1 row.', 'glossary'),
         opt('pararam', {'steterunt': 'pararam'}, 'MS1932. Plainer.', 'MS1932'),
         opt('ficaram parados', {'steterunt': 'ficaram parados'}, 'Longer.', 'draft')]),
    dec('fulgurantis', ['3:11'], 'fulgurántis hastæ tuæ', 'word',
        "*Fulgur* is *relâmpago* in the psalter (17:15, 96:4), so *relampejante* would keep the family, but it is a rare word. *Fulgurante* is the plain cognate, known in Brazil, and it keeps the Latin root. MS1932 *fulgurante*.",
        [opt('fulgurante', {'fulgurantis': 'fulgurante'}, 'Draft; MS1932.', 'draft'),
         opt('relampejante', {'fulgurantis': 'relampejante'}, "Keeps the psalter's *relâmpago* family.", 'draft')]),
    dec('fremitu', ['3:12'], 'In frémitu conculcábis terram', 'glossary',
        "*Frémitus* is the noun of *frémere* → *bramir* (glossary, 2:1). *No bramido* keeps the Latin's *in* and matches *e no furor* in the second colon. *Conculcáre → calcar aos pés* (D44). MS1932 *Na tua cólera* explains the roar as anger.",
        [opt('No bramido', {'fremitu': 'No bramido'}, "Draft; the *frémere* row's noun.", 'glossary'),
         opt('Com fragor', {'fremitu': 'Com fragor'}, 'A crash of noise; loses the root.', 'draft'),
         opt('Na vossa cólera', {'fremitu': 'Na vossa cólera'}, 'MS1932; explains.', 'MS1932')]),
    dec('obstupefacies', ['3:12'], 'obstupefácies gentes', 'word',
        "*Obstupefácere* is to strike dumb with amazement (L&S). *Espantar* in Brazil is both 'astonish' and 'frighten', which fits a theophany. MS1932 *espantarás*.",
        [opt('espantareis', {'obstupefacies': 'espantareis'}, 'Draft; MS1932.', 'MS1932'),
         opt('deixareis atônitas', {'obstupefacies': 'deixareis atônitas'}, 'Exact; longer.', 'draft')]),
    dec('denudasti', ['3:13b'], 'denudásti fundaméntum ejus usque ad collum', 'word',
        "*Denudáre* is to lay bare (DRB 'hast laid bare'). *Desnudar* is the cognate and plain. MS1932 *descobriste* can be heard as 'discovered'. The strange *usque ad collum* (a house laid bare to the neck) is Jerome's and is kept: *até o pescoço*.",
        [opt('desnudastes', {'denudasti': 'desnudastes'}, 'Draft.', 'draft'),
         opt('pusestes a nu', {'denudasti': 'pusestes a nu'}, 'The idiom.', 'draft'),
         opt('descobristes', {'denudasti': 'descobristes'}, 'MS1932, DM1962.', 'MS1932')]),
    dec('turbo', ['3:14a'], 'veniéntibus ut turbo', 'word',
        "*Turbo* is a whirlwind. *Turbilhão* keeps it apart from *gurges → redemoinho* (3:9b). MS1932 *torvelinho*.",
        [opt('turbilhão', {'turbo': 'turbilhão'}, 'Draft.', 'draft'),
         opt('redemoinho', {'turbo': 'redemoinho'}, "Takes *gurges*'s word in this draft.", 'draft')]),
    dec('sicut', ['3:14b'], 'Exsultátio eórum * sicut ejus, qui dévorat páuperem in abscóndito', 'grammar',
        "The Latin is verbless and leaves the tense open (DRB supplies 'was', MS1932 *estavam*). Portuguese can carry a verbless comparison (47:7 *dores como de quem está de parto*, settled D43). *In abscóndito → às escondidas* (9:30a).",
        [opt('como a', {'sicut': 'como a'}, "Draft; verbless, as the Latin.", 'draft'),
         opt('era como a', {'sicut': 'era como a'}, 'DRB, MS1932: a past copula supplied.', 'DRB')]),
    dec('scateat', ['3:16b'], 'et subter me scáteat', 'word',
        "*Scatére* is to bubble up, to teem or swarm (L&S; DRB 'swarm under me'). *Fervilhar* has both, the boiling and the swarming of worms, which suits *putrédo*. MS1932 *me consuma por dentro* explains. The jussive *Ingrediátur … scáteat* is carried by *Que … que*; a bare *Entre* at the head would be heard first as the preposition 'between'.",
        [opt('fervilhe', {'scateat': 'fervilhe'}, 'Draft.', 'draft'),
         opt('pulule', {'scateat': 'pulule'}, 'Swarming only; less common.', 'draft')]),
    dec('germen', ['3:17a'], 'non erit germen in víneis', 'word',
        "*Germen* is a sprout or bud (DRB 'spring'). *Germe* in Portuguese is heard as a germ; *broto* is the plain word.",
        [opt('broto', {'germen': 'broto'}, 'Draft.', 'draft'),
         opt('rebento', {'germen': 'rebento'}, "127:3b's word for *novéllæ*.", 'draft')]),
    dec('opus', ['3:17b'], 'Mentiétur opus olívæ', 'word',
        "The same noun as 3:2b *opus tuum* → *a vossa obra*. The Latin uses one word for God's work and the olive's yield; the draft keeps one word, so a reader crossing columns finds it. *Mentir* keeps the Latin's image of the tree that 'lies' (fails its promise; DRB 'shall fail', MS1932 *faltará*).",
        [opt('a obra', {'opus': 'a obra'}, 'Draft; the same word as 3:2b.', 'draft'),
         opt('o trabalho', {'opus': 'o trabalho'}, 'DRB "the labour". Plainer here; loses the echo with 3:2b.', 'DRB'),
         opt('o fruto', {'opus': 'o fruto'}, 'Explains.', 'draft')]),
    dec('armentum', ['3:17c'], 'non erit arméntum in præsépibus', 'glossary',
        "*Arméntum → manada*, as canticle 214 (Jer 31:14 *armentórum → manadas*); *pecus → rebanho*. *Præsépe* is a stall or manger; *estábulos* (MS1932). *Abscíndere → cortar* (76:9).",
        [opt('manada', {'armentum': 'manada'}, 'Draft; canticle 214.', 'glossary'),
         opt('gado', {'armentum': 'gado'}, 'The CNBB LH; plainer; collective.', 'CNBB')]),
    dec('gaudebo', ['3:18'], 'in Dómino gaudébo: * et exsultábo', 'glossary',
        "*Gaudére → regozijar-se* is the open glossary row (95:11), kept apart from *lætári → alegrar-se* and *exsultáre → exultar*, which stands in the next colon here.",
        [opt('me regozijarei', {'gaudebo': 'me regozijarei'}, 'Draft; the glossary row.', 'glossary'),
         opt('me alegrarei', {'gaudebo': 'me alegrarei'}, "The CNBB LH; takes *lætári*'s verb.", 'CNBB')]),
    dec('jesu', ['3:18'], 'in Deo Jesu meo', 'word',
        "Jerome wrote *Jesu*: the Hebrew is 'my salvation' (MS1932, DM1962 and the CNBB LH all have *meu Salvador*). But the Latin says the Name, and it is how the Church has prayed this line. DRB 'in God my Jesus'. Rule 1: the Latin's word, not the Hebrew's sense.",
        [opt('meu Jesus', {'jesu': 'meu Jesus'}, "Draft; DRB. The Latin's word.", 'draft'),
         opt('meu Salvador', {'jesu': 'meu Salvador'}, "MS1932, DM1962, CNBB LH: the Hebrew's sense.", 'MS1932')]),
    dec('deus_dominus', ['3:19a'], 'Deus Dóminus fortitúdo mea', 'order',
        "The Latin puts *Deus* first. At 117:27a *Deus Dóminus* is a sentence (*o Senhor é Deus*); here it is the subject of a verbless sentence whose predicate is *fortitúdo mea*, so *é* is supplied before the predicate. *Deus, o Senhor* keeps the Latin's order; *O Senhor Deus* is the familiar Portuguese order (MS1932). *Fortitúdo → força* (glossary).",
        [opt('Deus, o Senhor,', {'deus_dominus': 'Deus, o Senhor,'}, "Draft; the Latin's order.", 'draft'),
         opt('O Senhor Deus', {'deus_dominus': 'O Senhor Deus'}, 'MS1932; the usual order.', 'MS1932')]),
    dec('ponet', ['3:19a'], 'ponet pedes meos quasi cervórum', 'word',
        "*Pónere … ut* is 'make like' in 82:14 (*pone illos ut rotam → fazei-os como uma roda*); *porá os meus pés como* is not Portuguese. *Cervórum* → *das corças*, copying 17:34 (*pedes meos tamquam cervórum → os meus pés como os das corças*), where *cervos* was heard as *servos*.",
        [opt('fará … das corças', {'ponet': 'fará', 'cervorum': 'das corças'}, 'Draft; 82:14, 17:34.', 'glossary'),
         opt('tornará … das corças', {'ponet': 'tornará', 'cervorum': 'das corças'}, 'MS1932 *tornará*.', 'MS1932'),
         opt('fará … dos cervos', {'ponet': 'fará', 'cervorum': 'dos cervos'}, "The animal's own gender; heard as *servos* at 17:34.", 'draft')]),
    dec('canentem', ['3:19b'], 'dedúcet me victor * in psalmis canéntem', 'grammar',
        "*Victor* is nominative: God leads as victor. *Canéntem* is accusative: the one led is singing. A Portuguese participle after *me* would leave open who sings, which the Latin does not; so *a mim, que canto* names it. *Dedúcere* (guidance) → *guiar* (D22). *In psalmis → com salmos*, as 94:2 *in psalmis jubilémus → com salmos o aclamemos*.",
        [opt('ele, vencedor, me guiará, * a mim, que canto com salmos', {'victor': 'ele, vencedor, me guiará,', 'canentem': 'a mim, que canto com salmos'}, "Draft.", 'draft'),
         opt('me guiará vencedor * cantando eu salmos', {'victor': 'me guiará vencedor', 'canentem': 'cantando eu salmos'}, 'MS1932. *Vencedor* can be heard of the singer.', 'MS1932'),
         opt('ele, vencedor, me guiará, * enquanto canto salmos', {'victor': 'ele, vencedor, me guiará,', 'canentem': 'enquanto canto salmos'}, 'A conjunction supplied.', 'draft')]),
]

choices = {
    '3:2a': "DO's first line, *(Canticum Habacuc * Hab 3:2-19)*, is a heading with the book reference. It is not a prayed verse and is not translated (D7; readVerses skips it, as for 233, 211–216). The Latin is Jerome's Vulgate of Habakkuk, from the Hebrew, not the Gallican psalter. This line is also DO's antiphon for the canticle (Friday Lauds, `Psalmi major.txt` [Daya5 Laudes], [Monastic Laudes] feria 6). *Timére → temer*.",
    '3:2b': "The Latin's anacoluthon (object first, taken up by *illud*) is kept. *Medium annórum → o meio dos anos*, twice, as the Latin repeats it.",
    '3:2c': "The second colon, with *Dómine*, is DO's antiphon *Cum irátus fúeris, * Dómine, misericórdiæ recordáberis* ([Day5 Laudes2]): *Quando estiverdes irado, Senhor, vos lembrareis da misericórdia* reads alone. *Misericórdiæ recordári → lembrar-se da misericórdia* (97:3); no possessive supplied (MS1932 puts *(tua)* in parentheses). *Irátus fúeris → estiverdes irado*: the copula build of 79:5, 84:6.",
    '3:3a': "*Auster → sul* (the glossary's open row, 125:4; the region). *Sanctus* is God, parallel to *Deus*: *o Santo*, capital, as *o Santo de Israel* (70:22, 77:41, canticle 221). The verb is gapped in the second colon as in the Latin. *Pharan → Farã* (the Portuguese Bible form; the CNBB LH has *Farã*).",
    '3:3b': "Natural order (D2) for the Latin's *Opéruit cælos glória ejus … laudis ejus plena est terra*. *Laus → louvor*.",
    '3:4a': "Verbless second colon, as the Latin. *Splendor → esplendor* (89:17).",
    '3:4b': "DO's line crosses into Vulgate verse 5 at the inline marker *(5a)*, which is not reproduced. *Fortitúdo → força* (glossary). *Ante fáciem → diante da face* (glossary).",
    '3:5b': "Crosses into verse 6 at *(6a)*, not reproduced. *Egrédi → sair*, echoed by 3:13a *Egréssus es → Saístes*.",
    '3:6b': "*Dissólvere → dissolver* (DRB 'melted'). *Contérere → quebrar* (glossary).",
    '3:6c': "*Collis → colina* (64:13). *Mundus* here is the world (Habakkuk's Latin); D30 says the psalter has no *mundus* 'world', so nothing collides. *Æternitas → eternidade*.",
    '3:7': "*Tentórium → tenda* (the only tent word here; *tabernáculum → tenda* does not occur in the canticle). *Turbáre → perturbar* (glossary). *Æthiópia → Etiópia*, *Mádian → Madiã*.",
    '3:8a': "*Numquid → Acaso* (glossary). The second and third questions stay verbless, as the Latin. *Furor → furor*, *indignátio → indignação* (glossary).",
    '3:9b': "DO's line crosses into verse 10 at *(10a)*, not reproduced. The pointing † and * kept.",
    '3:10b': "*Dedit vocem suam → fez ouvir a sua voz*, copied from 17:14 and 45:7. *Altitúdo → altura* (glossary, concrete). *Leváre → levantar* (glossary).",
    '3:11': "DO's comma after *tuárum* is kept, so *na luz das vossas setas* hangs between the two verbs as in the Latin. *In luce … in splendóre → na luz … no esplendor*, the same preposition twice. *Sagítta → seta* (glossary).",
    '3:13a': "*Salus → salvação* (D6), twice, as the Latin repeats it. *Christus → Cristo* (D19), as 2:2 *o seu Cristo*.",
    '3:13b': "*Percútere → ferir*. *Caput de domo ímpii → a cabeça da casa do ímpio*. *Collum → pescoço* (the *cervix* row's word, 128:4; the two never meet).",
    '3:14a': "*Maledícere → amaldiçoar* (D44). The Latin's plural *sceptris* kept. *Bellátor → guerreiro*. *Dispérgere → dispersar* (glossary).",
    '3:15': "*Lutum → lama* (39:3, 17:43). *Aquæ multæ → as muitas águas* (92:3b).",
    '3:16a': "*Conturbáre → perturbar* (glossary; 30:10 *o meu ventre*). *Contremíscere → estremecer* (17:8, 76:19). *A voce → à voz* (DRB 'at the voice').",
    '3:16b': "*Putrédo → podridão*. The jussives are carried by *Que … que*.",
    '3:16c': "*Requiéscere → repousar* (glossary). *Ascéndere → subir*. *Accínctus → cingido* (64:7). *Tribulátio → tribulação*.",
    '3:17a': "*Enim → Pois*. *Víneæ → vinhas* (79:9, 104:33). *Florére → florescer* (91:13).",
    '3:17b': "*Arva → os campos*; *cibus → alimento* (64:10b). *Afférre → trazer*.",
    '3:17c': "Natural order (D2): *O rebanho será cortado do aprisco* for *Abscindétur de ovíli pecus*.",
    '3:18': "*Exsultáre → exultar* (glossary).",
    '3:19b': "*Excélsa → alturas* (D42; 17:34 *sobre as alturas*); the Latin's *mea* kept: *as minhas alturas*.",
}

audit = [
    {'step': 'draft', 'note': "Canticle-level draft. parallels.py handles psalm numbers only, so ps225/show_parallels.py builds consult/parallels/ps225.md (gitignored) from: the DO Latin; the Bolls Vulgate, Douay-Rheims and WLC Hebrew of Hab 3 (book 35); the Rahlfs LXX from consult/lxx-*.csv (a different text of the prayer, only a distant witness); Matos Soares 1932 from the pdftotext text layer of PDF pp. 1873–1874 = printed pp. 856–857; the Diurnal Monástico 1962 (Friday Lauds, ferial canticle; Portuguese from the Hebrew, *tu* address); DO's Portuguese (no authority). The third-party texts are in consult/ps225/ (gitignored). The Latin is Jerome's Habakkuk from the Hebrew, translated as it stands: *córnua* (horns), *diábolus*, *Jesu meo*, *usque ad collum*, *pelles* are the Latin's and are kept against the Hebrew-family readings of MS1932's glosses, the DM1962 and the CNBB. Precedent checked with ps225/concord.py and ps225/gloss.py (copies of ps216's). Brazilian circulation fetched and recorded in ps225/circulation.md. Hardest readings: *auditiónem tuam*, *Súscitans suscitábis*, *in flumínibus*, *ab itinéribus*, *Jesu meo*, *victor … canéntem*. The first-person *Audívi* at the head of 3:16a would be heard as the *vós* imperative 'Hear!', so *eu* is supplied in both places (decision `ouvi`)."},
    {'step': 'checks', 'note': "Hard checks pass: ids and marks match DO's Latin. render.py and checks.py work unchanged with DO number 225, and readVerses skips the heading line. Soft flags accepted. Length: 3:3a −3 (*Austro véniet → virá do sul*); 3:4a +3/−3 (the article and *como a*; the verbless *chifres* colon is short); 3:4b +3 (*mors → a morte*, *diante da sua face*); 3:5b −3/+3 (*Pôs-se de pé*, decision `stetit`); 3:6b +3 (*seculares*); 3:6c +3 (the passive, decision `incurvati`); 3:7 +5 (*turbabúntur → serão perturbadas*); 3:8b +3 (*Vós que* supplies the relative's antecedent); 3:12 +3 (*calcar aos pés*, D44); 3:13a +3 (*salútem → a salvação*, twice); 3:15 +5 (*Viam … equis tuis* needs *um caminho para os vossos cavalos*); 3:16b −3/+3 (the jussive *Que … que*); 3:17c +3 (natural order); 3:19b +4 (*ele* names the victor; decision `canentem`). Rhyme flag 3:8a/3:8b (*indignação / salvação*): the Latin's own *indignátio / salvátio*; kept. 3:14b is verbless as the Latin (decision `sicut`). No colon is too long for one breath; 3:11b is the Latin's longest too."},
]

prayed = {
    'psalm': 225, 'tier': 3, 'version': 1, 'address': 'vós', 'status': 'draft',
    'verses': verses, 'decisions': decisions, 'choices': choices, 'audit': audit,
}
(here / 'prayed.json').write_text(json.dumps(prayed, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print('written', len(verses), 'verses', len(decisions), 'decisions')
