export { fetchDay } from './fetchPage'
export { fetchVaticanGospelText, gospelOfTheDaySource } from './gospel'
export { paragraphText, parseSection } from './parse'
export { wordOfThePopeSource } from './pope'
export { blockHeading, type DayBlock, dayUrl, type Lang, narrowLang } from './url'
