export const iconMap: Record<string, string> = {
  sunrise: '🌅',
  cross: '✝️',
  mary: '🔵',
  rosary: '📿',
  book: '📖',
  moon: '🌙',
  star: '⭐',
  heart: '❤️',
  flame: '🔥',
  sun: '☀️',
  dove: '🕊️',
  church: '⛪',
  chalice: '🏆',
  crown: '👑',
  angel: '👼',
  candle: '🕯️',
  pray: '🙏',
  quill: '🪶',
  shield: '🛡️',
  water: '💧',
  lily: '🌷',
}
