"""Write ps105/prayed.json v1 (draft). Run once: python3.13 research/psalterium/ps105/tools/build_v1.py"""
import json
from pathlib import Path

here = Path(__file__).resolve().parents[1]

verses = {
    '105:1': 'Dai graças ao Senhor, porque ele é bom: * porque é para sempre a sua misericórdia.',
    '105:2': 'Quem falará das potências do Senhor, * fará ouvir todos os seus louvores?',
    '105:3': 'Bem-aventurados os que guardam o juízo, * e {faciunt} a justiça em todo tempo.',
    '105:4': 'Lembrai-vos de nós, Senhor, {beneplacito} do vosso povo: * visitai-nos na vossa salvação:',
    '105:5': '{videndum} dos vossos escolhidos, para nos alegrarmos na alegria da vossa nação: * {lauderis} com a vossa herança.',
    '105:6': 'Pecamos com os nossos pais: * agimos injustamente, fizemos a iniquidade.',
    '105:7': 'Os nossos pais no Egito não entenderam as vossas maravilhas: * não se lembraram da multidão da vossa misericórdia.',
    '105:7b': '{irritaverunt}, subindo ao mar, * ao Mar Vermelho.',
    '105:8': 'E salvou-os por causa do seu nome: * para fazer conhecer a sua potência.',
    '105:9': 'E repreendeu o Mar Vermelho, e ele secou-se, * e guiou-os pelos abismos como pelo deserto.',
    '105:10': 'E salvou-os da mão dos que os odiavam: * e resgatou-os da mão do inimigo.',
    '105:11': 'E a água cobriu os que os atribulavam: * não restou um só deles.',
    '105:12': 'E acreditaram nas suas palavras: * {laudaverunt}.',
    '105:13': '{cito}, esqueceram-se das suas obras: * e não esperaram pelo seu desígnio.',
    '105:14': '{concupierunt} no deserto: * e tentaram a Deus no lugar sem água.',
    '105:15': 'E deu-lhes a petição deles: * e enviou {saturitatem} às suas almas.',
    '105:16': 'E provocaram Moisés no acampamento: * Aarão, o santo do Senhor.',
    '105:17': 'Abriu-se a terra, e engoliu Datan: * e cobriu a congregação de Abiron.',
    '105:18': 'E inflamou-se um fogo na congregação deles, * a chama queimou os pecadores.',
    '105:19': 'E fizeram um bezerro em Horeb, * e adoraram uma imagem esculpida.',
    '105:20': 'E trocaram a sua glória * pela semelhança de um bezerro que come feno.',
    '105:21': 'Esqueceram a Deus, que os salvou, * que fez grandes coisas no Egito, maravilhas na terra de Cam: coisas terríveis no Mar Vermelho.',
    '105:23': 'E disse que os exterminaria: * se Moisés, o seu escolhido, {stetisset} na brecha diante dele:',
    '105:24': 'Para desviar a sua ira, para que não os exterminasse: * e tiveram por nada a terra desejável:',
    '105:25': 'Não acreditaram na sua palavra, e murmuraram nas suas tendas: * não escutaram a voz do Senhor.',
    '105:26': 'E levantou a sua mão sobre eles: * para os prostrar no deserto:',
    '105:27': 'E para abater a descendência deles entre as nações: * e para os dispersar pelas regiões.',
    '105:28': '{initiati}: * e comeram os sacrifícios dos mortos.',
    '105:29': 'E provocaram-no com as suas invenções: * e multiplicou-se entre eles a ruína.',
    '105:30': '{stetit}, e aplacou: * e cessou {quassatio}.',
    '105:31': 'E foi-lhe atribuído como justiça: * de geração em geração para todo o sempre.',
    '105:32': 'E provocaram-no {aquas}: * e Moisés foi maltratado por causa deles: porque {exacerbaverunt} o seu espírito.',
    '105:33': '{distinxit}: * não exterminaram as nações {quas}.',
    '105:35': 'E misturaram-se entre as nações, e aprenderam as obras delas: e serviram às imagens esculpidas delas: * e isso se tornou para eles um tropeço.',
    '105:37': 'E imolaram os seus filhos, * e as suas filhas aos demônios.',
    '105:38': 'E derramaram o sangue inocente: * o sangue dos seus filhos e das suas filhas, que sacrificaram às imagens esculpidas de Canaã.',
    '105:39': 'E a terra foi {infecta} de sangue, e foi contaminada pelas obras deles: * e prostituíram-se nas suas invenções.',
    '105:40': 'E o Senhor irou-se com furor contra o seu povo: * e abominou a sua herança.',
    '105:41': 'E entregou-os nas mãos das nações: * e dominaram-nos os que os odiavam.',
    '105:42': 'E atribularam-nos os inimigos deles, e foram humilhados sob as mãos deles: * muitas vezes os livrou.',
    '105:43': 'Eles, porém, provocaram-no com o seu desígnio: * e foram humilhados nas suas iniquidades.',
    '105:44': 'E viu, quando eram atribulados: * e ouviu a oração deles.',
    '105:45': 'E lembrou-se da sua aliança: * e {poenituit} segundo a multidão da sua misericórdia.',
    '105:46': '{dedit} * diante de todos os que {ceperant}.',
    '105:47': 'Salvai-nos, Senhor, nosso Deus: * e {congrega} dentre as nações:',
    '105:47b': 'Para darmos graças ao vosso santo nome: * e nos gloriarmos no vosso louvor.',
    '105:48': 'Bendito o Senhor, Deus de Israel, desde sempre e para todo o sempre: * e todo o povo dirá: Assim seja, assim seja.',
}


def opt(label, slot, form, note, frm=None, warn=False):
    o = {'label': label, 'forms': {slot: form}, 'note': note}
    if frm:
        o['from'] = frm
    if warn:
        o['warn'] = True
    return o


def dec(id_, refs, latin, kind, why, options):
    return {'id': id_, 'refs': refs, 'latin': latin, 'kind': kind, 'why': why, 'options': options}


decisions = [
    dec('faciunt', ['105:3'], 'et fáciunt justítiam', 'glossary',
        "fácere justítiam: the light verb kept as 'fazer', because 'praticar' is operári's verb (100:8 'os que praticam a iniquidade'; the ps100 ruling). DRB 'do justice'. MS1932 has 'praticam'. Also the Gradual of Quad2-0 and Commune C4c (105:3), where the colon must stand alone.",
        [opt('fazem', 'faciunt', 'fazem', "draft — fácere → fazer; DRB 'do'", 'draft'),
         opt('praticam', 'faciunt', 'praticam', "the natural collocation, MS1932; but operári's verb", 'MS1932')]),
    dec('beneplacito', ['105:4'], 'in beneplácito pópuli tui', 'glossary',
        "beneplácitum → favor (the 88:18 row, open): 'the favour of your people' keeps the Latin's openness (God's favour toward the people, or the people's delight). The versicle 'Meménto nostri, Dómine, in beneplácito pópuli tui. R. Vísita nos in salutári tuo' (Minor Special Advent, Adv4-0; missa Quad2-0) must read alone: it does.",
        [opt('no favor', 'beneplacito', 'no favor', 'draft — the 88:18 row; DRB "in the favour of thy people"', 'draft'),
         opt('no agrado', 'beneplacito', 'no agrado', 'the row\'s option; heard as the people\'s pleasure more than God\'s'),
         opt('segundo a benevolência que tendes para com', 'beneplacito', 'segundo a benevolência que tendes para com', 'explains; resolves the genitive — refused (rule 2)', warn=True)]),
    dec('videndum', ['105:5'], 'Ad vidéndum in bonitáte electórum tuórum', 'grammar',
        "Ad + gerund three times in the verse (ad vidéndum, ad lætándum, ut laudéris). 'in bonitáte' after 'see': the Latin keeps the preposition (to see [us] in the good of your chosen). DRB 'see the good of thy chosen' drops it; MS1932 'vejamos a felicidade'. bónitas → bondade (row). Kept 'in' would read 'Para vermos, na bondade dos vossos escolhidos' — a dangling comma that the ear cannot resolve; dropped it, as DRB.",
        [opt('Para vermos a bondade', 'videndum', 'Para vermos a bondade', "draft — DRB's build; bondade is the row", 'draft'),
         opt('Para vermos na bondade', 'videndum', 'Para vermos na bondade', "the Latin's 'in' kept; unclear to the ear"),
         opt('Para vermos o bem', 'videndum', 'Para vermos o bem', "the Hebrew's prosperity; bónum, not bónitas", warn=True)]),
    dec('lauderis', ['105:5'], 'ut laudéris cum hereditáte tua', 'ambiguity',
        "laudéris is 2nd singular passive: God is praised together with his inheritance. The Greek τοῦ ἐπαινεῖσθαι and the Hebrew (lehithallel, 'to glory') make the people the subject. Rule 1: the Latin. DRB 'that thou mayst be praised with thy inheritance'.",
        [opt('para serdes louvado', 'lauderis', 'para serdes louvado', "draft — the Latin's person; DRB", 'draft'),
         opt('para nos gloriarmos', 'lauderis', 'para nos gloriarmos', 'the Greek and the Hebrew — against the Latin', warn=True)]),
    dec('irritaverunt', ['105:7b'], 'Et irritavérunt ascendéntes in mare, * Mare Rubrum', 'grammar',
        "irritáre → provocar (D27). The Latin has no object (the Greek παρεπίκραναν neither); MS1932 supplies 'te', DRB 'provoked to wrath'. The participle kept as a gerund. 'ao Mar Vermelho' in apposition to 'ao mar', as the Latin repeats 'mare … Mare Rubrum'.",
        [opt('E provocaram', 'irritaverunt', 'E provocaram', 'draft — absolute, as the Latin', 'draft'),
         opt('E provocaram-vos', 'irritaverunt', 'E provocaram-vos', "MS1932's 'te' — the verse before addresses God; adds an object"),
         opt('E provocaram-no', 'irritaverunt', 'E provocaram-no', 'the third person of verse 8; adds an object')]),
    dec('laudaverunt', ['105:12'], 'et laudavérunt laudem ejus', 'word',
        "The Latin's figura etymologica (laudáre laudem), where the Greek has ᾖσαν τὴν αἴνεσιν 'sang'. Rule 2 keeps the repetition; laus → louvor (row), laudáre → louvar. MS1932 'cantaram o seu louvor' follows the Greek.",
        [opt('e louvaram o seu louvor', 'laudaverunt', 'e louvaram o seu louvor', 'draft — the Latin\'s repetition kept', 'draft'),
         opt('e cantaram o seu louvor', 'laudaverunt', 'e cantaram o seu louvor', 'MS1932 and the Greek; cantáre is not in the Latin', 'MS1932')]),
    dec('cito', ['105:13'], 'Cito fecérunt, oblíti sunt óperum ejus', 'grammar',
        "Cito fecérunt: the Greek ἐτάχυναν 'they hastened' — the Latin makes two words of it, 'they did quickly'. DRB 'They had quickly done, they forgot his works'; MS1932 folds it into 'depressa esqueceram'. 'Depressa o fizeram' keeps the verb and lets 'o' point forward to the forgetting, as the Latin's bare fecérunt does.",
        [opt('Depressa o fizeram', 'cito', 'Depressa o fizeram', 'draft — both Latin words; DRB', 'draft'),
         opt('Apressaram-se', 'cito', 'Apressaram-se', "the Greek verb; drops fácere"),
         opt('Depressa (esqueceram-se)', 'cito', 'Depressa', "MS1932: the adverb only — drops fecérunt; would need 'esqueceram-se' to follow without comma", 'MS1932', warn=True)]),
    dec('concupierunt', ['105:14'], 'Et concupiérunt concupiscéntiam in desérto', 'glossary',
        "concupíscere: the row (open) proposes cobiçar for goods, ansiar por for the good; the craving for meat in the desert is the first. The cognate object kept (rule 2) as 'com cobiça', the Portuguese figura (cf. 'desejei com desejo'). DRB 'they coveted their desire'; MS1932 'cobiçaram delícias'.",
        [opt('E cobiçaram com cobiça', 'concupierunt', 'E cobiçaram com cobiça', "draft — the row's split, the repetition kept", 'draft'),
         opt('E arderam de cobiça', 'concupierunt', 'E arderam de cobiça', 'natural, but one verb and an image not in the Latin'),
         opt('E ansiaram com ânsia', 'concupierunt', 'E ansiaram com ânsia', "the row's main word; for a sinful craving too gentle")]),
    dec('saturitatem', ['105:15'], 'et misit saturitátem in ánimas eórum', 'word',
        "saturitas: L&S 'fullness, plenty'. The Latin follows the Greek πλησμονή against the Hebrew's 'leanness' (rule 1). The saciar family (saturáre row) gives 'saciedade'; 'fartura' is the plainer concrete word (MS1932 'fartou-os').",
        [opt('fartura', 'saturitatem', 'fartura', 'draft — plenty, concrete', 'draft'),
         opt('saciedade', 'saturitatem', 'saciedade', 'the noun of saciar (the saturáre row); abstract'),
         opt('magreza', 'saturitatem', 'magreza', 'the Hebrew — against the Latin', warn=True)]),
    dec('stetisset', ['105:23', '105:30'], 'si non Móyses … stetísset in confractióne', 'word',
        "stare → estar de pé (row, open). The counterfactual pluperfect with 'estar de pé' is heavy ('não tivesse estado de pé'); 'pôr-se' says the taking of a stand, and 105:30 'stetit Phínees' takes the same verb ('se pôs de pé'). confráctio → brecha: L&S cite this verse, 'a breach' (the Greek θραῦσις).",
        [opt('não se tivesse posto', 'stetisset', 'não se tivesse posto', 'draft — MS1932 "se não tivesse posto"', 'MS1932'),
         opt('não estivesse de pé', 'stetisset', 'não estivesse de pé', "the row's verb, the imperfect subjunctive"),
         opt('não se tivesse mantido', 'stetisset', 'não se tivesse mantido', 'firmness; a new verb')]),
    dec('initiati', ['105:28'], 'Et initiáti sunt Beélphegor', 'word',
        "initiári + dative: L&S 'to initiate into mysteries' (the Greek ἐτελέσθησαν). The passive kept. MS1932 'consagraram-se a' turns it active. Beelfegor as MS1932 (59:9's rule: MS1932's forms of names).",
        [opt('E foram iniciados em Beelfegor', 'initiati', 'E foram iniciados em Beelfegor', "draft — the Latin's passive and verb", 'draft'),
         opt('E consagraram-se a Beelfegor', 'initiati', 'E consagraram-se a Beelfegor', 'MS1932; another verb, active', 'MS1932'),
         opt('E iniciaram-se no culto de Beelfegor', 'initiati', 'E iniciaram-se no culto de Beelfegor', "explains 'culto' — refused (rule 2)", warn=True)]),
    dec('stetit', ['105:30'], 'Et stetit Phínees', 'word',
        "The same verb as 105:23 (stare), so the same Portuguese. Phínees → Finéas, MS1932's form (59:9's rule); modern Bibles write Fineias.",
        [opt('E Finéas pôs-se de pé', 'stetit', 'E Finéas pôs-se de pé', "draft — MS1932's name; 105:23's verb", 'draft'),
         opt('E Fineias pôs-se de pé', 'stetit', 'E Fineias pôs-se de pé', 'the current spelling'),
         opt('E apresentou-se Finéas', 'stetit', 'E apresentou-se Finéas', 'MS1932; another verb than 105:23', 'MS1932')]),
    dec('quassatio', ['105:30'], 'et cessávit quassátio', 'word',
        "quassátio: L&S 'a shaking; a disturbance, affliction', citing this verse; the Greek θραῦσις (a smashing, a slaughter) is the same word as 105:23's confráctio, which the Latin splits. 'Flagelo' (MS1932) belongs to flagéllum (D39); 'aflição' to afflíctio; 'ruína' is 105:29's. 'abalo' is the shaking, but may be heard as an earthquake.",
        [opt('o abalo', 'quassatio', 'o abalo', 'draft — the root sense (quassáre, shake)', 'draft'),
         opt('a mortandade', 'quassatio', 'a mortandade', "DRB 'the slaughter'; the event, named more than the Latin does"),
         opt('o flagelo', 'quassatio', 'o flagelo', "MS1932; flagéllum's word (D39)", 'MS1932', warn=True)]),
    dec('aquas', ['105:32'], 'ad aquas contradictiónis', 'glossary',
        "contradíctio → contenda (row), which notes 105:32 as a proper name may keep 'contradição'. 'Águas da contradição' is the traditional Catholic name (MS1932 'Águas da contradição'), the Latin word kept; 'Meribá' is the Hebrew.",
        [opt('junto às águas da contradição', 'aquas', 'junto às águas da contradição', 'draft — MS1932; ad → junto a', 'MS1932'),
         opt('junto às águas da contenda', 'aquas', 'junto às águas da contenda', "the row's word"),
         opt('junto às águas de Meribá', 'aquas', 'junto às águas de Meribá', 'the Hebrew — against the Latin', warn=True)]),
    dec('exacerbaverunt', ['105:32'], 'quia exacerbavérunt spíritum ejus', 'glossary',
        "exacerbáre beside irritáre in one verse: D27 decides locally. Both are παροξύνω/παραπικραίνω in the Greek; here the Greek is παρεπίκραναν 'embittered', and acerbus is bitter. 'amargurar' gives the Latin root. 'o seu espírito' left open between Moses' and God's, as 'ejus'.",
        [opt('amarguraram', 'exacerbaverunt', 'amarguraram', 'draft — the root (acerbus), the Greek πικρ-', 'draft'),
         opt('exasperaram', 'exacerbaverunt', 'exasperaram', 'the row\'s earlier proposal; unknown to a blind reader in Ps 9'),
         opt('perturbaram', 'exacerbaverunt', 'perturbaram', 'MS1932; conturbáre\'s word', 'MS1932')]),
    dec('distinxit', ['105:33'], 'Et distínxit in lábiis suis', 'glossary',
        "distínguere lábia → pronunciar (the 65:13 row, the same Greek διέστειλεν, to utter distinctly). The Latin names no object; the Hebrew 'spoke rashly' is not in it. MS1932 'foi duvidoso nas suas palavras' is a gloss.",
        [opt('E pronunciou com os seus lábios', 'distinxit', 'E pronunciou com os seus lábios', 'draft — 65:13', 'draft'),
         opt('E distinguiu com os seus lábios', 'distinxit', 'E distinguiu com os seus lábios', "DRB 'he distinguished with his lips'", 'DRB'),
         opt('E foi duvidoso nas suas palavras', 'distinxit', 'E foi duvidoso nas suas palavras', 'MS1932 — a gloss', 'MS1932', warn=True)]),
    dec('quas', ['105:33'], 'gentes, quas dixit Dóminus illis', 'grammar',
        "quas dixit: 'the nations the Lord told them of'. DRB 'the nations of which the Lord spoke unto them'; MS1932 'que o Senhor lhes tinha indicado'. dícere → dizer would need 'que o Senhor lhes dissera', which Portuguese hears as 'the nations the Lord said'.",
        [opt('de que o Senhor lhes tinha falado', 'quas', 'de que o Senhor lhes tinha falado', "draft — DRB's build", 'DRB'),
         opt('que o Senhor lhes dissera', 'quas', 'que o Senhor lhes dissera', 'dícere → dizer, word for word'),
         opt('que o Senhor lhes tinha indicado', 'quas', 'que o Senhor lhes tinha indicado', 'MS1932; another verb', 'MS1932')]),
    dec('infecta', ['105:39'], 'Et infécta est terra in sanguínibus', 'word',
        "infícere: L&S 'to stain, dye, taint'. in sanguínibus → 'de sangue' (D29, singular). MS1932 'infeccionada'; DRB 'polluted'.",
        [opt('manchada', 'infecta', 'manchada', 'draft — the stain', 'draft'),
         opt('infectada', 'infecta', 'infectada', 'the cognate, MS1932; heard as disease', 'MS1932'),
         opt('poluída', 'infecta', 'poluída', "DRB 'polluted'; heard as environmental", 'DRB')]),
    dec('poenituit', ['105:45'], 'et pœnítuit eum', 'word',
        "pœnitére of God (μετεμελήθη): DRB 'repented'; MS1932 'teve piedade deles' explains. The Latin says repent; the tradition reads it of God's turning from wrath.",
        [opt('arrependeu-se', 'poenituit', 'arrependeu-se', "draft — the Latin; DRB", 'draft'),
         opt('teve compaixão', 'poenituit', 'teve compaixão', 'MS1932\'s sense — explains', 'MS1932', warn=True)]),
    dec('dedit', ['105:46'], 'Et dedit eos in misericórdias', 'grammar',
        "dare … in misericórdias: 'gave them over to mercies' (the Greek εἰς οἰκτιρμούς), i.e. made them objects of pity before their captors. The plural kept; 'dar' kept (trádere → entregar is 105:41's).",
        [opt('E deu-os às misericórdias', 'dedit', 'E deu-os às misericórdias', 'draft — the Latin word for word', 'draft'),
         opt('E entregou-os à misericórdia', 'dedit', 'E entregou-os à misericórdia', "smoother; trádere's verb and a singular"),
         opt('E fez que achassem misericórdia', 'dedit', 'E fez que achassem misericórdia', 'explains — refused (rule 2)', warn=True)]),
    dec('ceperant', ['105:46'], 'ómnium qui céperant eos', 'glossary',
        "cápere → tomar (the 58:4 row). With persons as object 'tomar' is unclear in Portuguese; 'capturar' says taking prisoners (the Greek αἰχμαλωτισάντων, 'made captive').",
        [opt('os tinham capturado', 'ceperant', 'os tinham capturado', 'draft — a local departure from the row', 'draft'),
         opt('os tinham tomado', 'ceperant', 'os tinham tomado', "the row's verb (58:4)"),
         opt('os tinham levado cativos', 'ceperant', 'os tinham levado cativos', 'the Greek; longer')]),
    dec('congrega', ['105:47'], 'et cóngrega nos de natiónibus', 'glossary',
        "congregáre with people as object: congregári → reunir-se (D43) for people gathering; the active 15:4b took 'congregar'. 'reuni-nos' has an enclitic, so no clash with a past. Also the Introit of Nat2-0 and the Matins V/R (105:47–47b).",
        [opt('reuni-nos', 'congrega', 'reuni-nos', 'draft — the people-gathering verb (D43)', 'draft'),
         opt('congregai-nos', 'congrega', 'congregai-nos', 'the cognate; 15:4b')]),
]

choices = {
    '105:1': "= 117:1 word for word (D5, D14).",
    '105:2': "poténtia → potência (row; 70:19 'A vossa potência'); plural kept. audítas fáciet → 'fará ouvir'. The question mark closes both colons, as the Latin.",
    '105:3': "Gradual of Quad2-0 and Commune C4c; stands alone.",
    '105:4': "Versicle and response (Minor Special Advent, Adv4-0; missa Quad2-0): both colons stand alone. 'Lembrai-vos', 'visitai-nos': enclitics, so no clash with a past.",
    '105:5': "gens (singular) → nação (42:1).",
    '105:6': "A versicle in 093-0. 'Pecamos' is also the present in pt-BR; the verse's other perfects fix the past. iniquitátem fácere → 'fizemos a iniquidade' (row).",
    '105:7': "memor esse → lembrar-se de (row); multitúdo → multidão (row 5:7b).",
    '105:7b': "The Latin repeats mare; kept.",
    '105:8': "Matins antiphon 'Salvávit eos Dóminus propter nomen suum' → 'Salvou-os o Senhor por causa do seu nome'. notam fácere → 'fazer conhecer' (97:2).",
    '105:9': "increpáre → repreender (row); dedúcere → guiar (D22); in abýssis … in desérto → 'pelos abismos … pelo deserto' (MS1932's prepositions).",
    '105:10': "redímere → resgatar (row).",
    '105:11': "operíre → cobrir, as 105:17. tribuláre → atribular (row).",
    '105:12': "crédere + dative → acreditar em (row, open). Ps 77:22 'non credidérunt in Deo' has 'creram em' — another construction.",
    '105:13': "oblivísci + genitive → esquecer-se de (58:12 row); sustinére with a non-divine object → esperar por (the D36 build); consílium (God's purpose) → desígnio (D33).",
    '105:14': "tentáre Deum → tentar a Deus; in inaquóso → 'no lugar sem água' (Ps 77:17, 40).",
    '105:15': "petítio → petição (36:4); 'deles' for ipsórum, so the gift is not heard as God's own petition.",
    '105:16': "irritáre → provocar (D27); castra → acampamento (26:3); Aarão (the names row, 117:3; Ps 104:26).",
    '105:17': "deglutíre → engolir (the absorbére row prefers it to tragar). Datan, Abiron as MS1932 (59:9's rule). 'opéruit super' → 'cobriu' — the Latin's 'super' is the Greek ἐπί and adds no sense in Portuguese.",
    '105:18': "synagóga → congregação (the row names 105:17–18: one Portuguese word for congregátio and synagóga). exardéscere → inflamar-se.",
    '105:19': "vítulus → bezerro (the 21:13 row foresaw 105:19–20); scúlptile → imagem esculpida (77:58, 96:7).",
    '105:20': "mutáre … in → trocar … por.",
    '105:21': "Matins antiphon 'Oblíti sunt Deum qui salvávit eos' → 'Esqueceram a Deus, que os salvou' — the accusative, as 49:22 (the verb without 'se', against 105:13's genitive). magnália → grandes coisas (70:19 row); Cam, Egito (Ps 77 names).",
    '105:23': "dispérdere → exterminar (row), three times in 105:23–24 and again 105:33 — kept. in conspéctu ejus → 'diante dele' (as 105:46).",
    '105:24': "avértere iram → desviar a ira (77:38b); pro níhilo → por nada (D44); desiderábilis → desejável.",
    '105:25': "exaudíre → escutar (D3); murmuráre → murmurar; tabernáculum → tenda (row).",
    '105:26': "eleváre manum → levantar a mão; prostérnere → prostrar.",
    '105:27': "deícere → abater (36:14b row); semen → descendência (D32; the row lists 105:27); dispérgere → dispersar.",
    '105:29': "irritáre → provocar (D27); adinvéntio → invenções (27:4 row, which names 105:29 and 39); 'com' here, 'nas' at 105:39, where the verb takes 'em'.",
    '105:31': "reputáre in justítiam → 'atribuído como justiça' (imputáre → atribuir, 31:2; the same Greek λογίζομαι). in generatiónem et generatiónem usque in sempitérnum → 'de geração em geração para todo o sempre' (D37).",
    '105:32': "vexáre → maltratar (93:5 row, which names 105:32).",
    '105:35': "scándalum → tropeço (row names 105:35); 'e isso se tornou para eles' as 68:11's build. 'delas' twice for eórum (the nations'), where 'suas' would be heard as Israel's own.",
    '105:37': "immoláre → imolar (D44 row names 105:37).",
    '105:38': "Canaã, as Ps 104:11 (MS1932 'Canaan').",
    '105:39': "contamináre → contaminar (D44 row names 105:39); fornicári → prostituir-se (72:27 row names 105:39).",
    '105:40': "irásci → irar-se; abominári → abominar (row names 105:40).",
    '105:41': "trádere → entregar (117:18 row); dominári → dominar.",
    '105:42': "sæpe → 'muitas vezes'; liberáre → livrar; humiliáre → humilhar.",
    '105:43': "exacerbáre alone → provocar (D27). consílium (their purpose) → desígnio (D33), as 105:13.",
    '105:44': "Matins antiphon 'Cum tribularéntur vidit Dóminus: et audívit oratiónem eórum' → 'Quando eram atribulados, viu o Senhor: e ouviu a oração deles' — reads alone. No object supplied for vidit, as the Latin.",
    '105:45': "testaméntum → aliança (row); 'segundo a multidão da sua misericórdia' (5:7b build).",
    '105:47': "Introit of Nat2-0; with 105:47b the Matins V/R (Psalmi matutinum). Both colons stand alone.",
    '105:47b': "confitéri → dar graças a (D5); gloriári in → gloriar-se em (row); laus → louvor.",
    '105:48': "= 40:14 with 'e todo o povo dirá' (D41: fiat, fiat → assim seja, assim seja). a sǽculo et usque in sǽculum → 'desde sempre e para todo o sempre' (40:14).",
}

audit = [
    {'step': 'draft', 'note': "Psalm-level draft from consult/parallels/ps105.md. Glossary rows read for every controlled word (ps077/gl.py; dump in ps105/tools/gl_dump.txt); twins by ps105/tools/twins.py (117:1, 40:14, 70:19, 97:2, 65:13, 72:27, 93:5); Ps 77's narrative wording and Ps 104's draft names (Aarão, Canaã, Cam) followed. Liturgical uses by ps105/tools/uses.py: V/R 105:4 (Advent), 105:47–47b (Matins V/R, Introit Nat2-0), 105:6 (093-0), 105:2–3 (Quad2-0), 105:3 (C4c); Matins antiphons 105:8, 105:21a, 105:44. Hard readings: 105:13 Cito fecérunt, 105:30 quassátio, 105:33 distínxit in lábiis, 105:46 dedit in misericórdias, 105:5 laudéris (Latin against Greek/Hebrew)."},
]

prayed = {'psalm': 105, 'tier': 3, 'version': 1, 'address': 'vós', 'status': 'draft',
          'verses': verses, 'decisions': decisions, 'choices': choices, 'audit': audit}
(here / 'prayed.json').write_text(json.dumps(prayed, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print('wrote', here / 'prayed.json')
