"""How Douay-Rheims, Matos Soares 1932, the Diurnal Monástico 1962 and pt-PT rendered each law-word of Ps 118.

Run from the repo root:  python3.13 research/psalterium/ps118/renderings.py
Reads consult/parallels/ps118.md (generate it first), writes ps118/renderings.md.

For every Latin verse that holds the term, the script looks in the same verse of each version for a list of
candidate nouns and tallies which were found. A verse with two law-words credits both with whatever nouns stand
in it, so the tallies are indicative (the per-verse table underneath is what to trust). Matos Soares is a raw OCR
layer with marginal notes running into the text: verses are cut at their leading numbers, hyphenated breaks joined.
"""

import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from latin import doLatin, readVerses, words  # noqa: E402

here = Path(__file__).resolve().parent
parallels = here.parent / 'consult/parallels/ps118.md'

terms = {
    'lex': r'^(lex|legis|legi|legem|lege)$',
    'testimonium': r'^testimoni',
    'mandatum': r'^mandat(um|i|o|a|orum|is)$',
    'iustificatio': r'^iustificatio',
    'iudicium': r'^iudici',
    'verbum': r'^verb(um|i|o|a|orum|is)$',
    'sermo': r'^sermo(n|$)',
    'eloquium': r'^eloqui',
}
ptStems = r'justificaç|testemunh|mandament|preceit|decret|estatut|orden|ordem|determinaç|sentenç|juízo|juizo|julgament|palavra|promessa|oráculo|\bleis?\b|justiça|dito|ensinament|prescriç|vontade'
enStems = r'justification|testimon|commandment|precept|statute|ordinance|judgment|word|speech|saying|\blaw\b|justice|promise'


def sections():
    text = parallels.read_text(encoding='utf-8')
    parts = re.split(r'^## ', text, flags=re.M)
    return {p.split('\n', 1)[0][:12]: p.split('\n', 1)[1] for p in parts[1:]}


def numbered(block, prefix=''):
    verses = {}
    for line in block.splitlines():
        match = re.match(rf'^{prefix}(\d+)\s+(.*)$', line.strip())
        if match:
            verses[int(match.group(1))] = match.group(2)
    return verses


def matosSoares(block):
    """Cut the OCR layer at verse numbers 1..176 met in ascending order."""
    text = re.sub(r'\xad\s*\n\s*', '', block)  # soft hyphen breaks
    text = re.sub(r'­\s+', '', text)
    flat = re.sub(r'\s+', ' ', text)
    verses, expected, position = {}, 1, 0
    starts = []
    while expected <= 176:
        match = re.compile(rf'(?<![\d,]) {expected}:? ?(?=[A-ZÉÓÁ])').search(flat, position)
        if not match:
            expected += 1
            continue
        starts.append((expected, match.end()))
        position = match.end()
        expected += 1
    for (n, start), (_, end) in zip(starts, starts[1:] + [(0, len(flat))]):
        verses[n] = flat[start:end][:260]
    return verses


def main():
    parts = sections()
    byName = {name: block for name, block in parts.items()}
    drb = numbered(next(b for n, b in byName.items() if n.startswith('Douay')))
    ptpt = numbered(next(b for n, b in byName.items() if n.startswith('pt-PT')), prefix='118:')
    dmLines = [l for l in next(b for n, b in byName.items() if n.startswith('Diurnal')).splitlines() if ' * ' in l]
    dm = {i + 1: line for i, line in enumerate(dmLines)}
    ms = matosSoares(next(b for n, b in byName.items() if n.startswith('Matos')))

    latin = readVerses(doLatin / 'Psalmorum/Psalm118.txt')
    versions = [('DRB', drb, enStems), ('MS1932', ms, ptStems), ('DM1962', dm, ptStems), ('pt-PT', ptpt, ptStems)]
    out = ['# Ps 118 — what the versions did with each law-word\n', 'Generated by `ps118/renderings.py`; do not edit. Tallies are per verse, so a verse with two law-words credits both; read the tables.\n']
    out.append(f'Verses found: DRB {len(drb)}, MS1932 {len(ms)} (OCR, cut at verse numbers), DM1962 {len(dm)}, pt-PT {len(ptpt)}.\n')
    for lemma, pattern in terms.items():
        rows, tallies = [], defaultdict(Counter)
        for verse in latin:
            if not any(re.search(pattern, w) for w in words(verse['text'])):
                continue
            cells = []
            for name, table, stems in versions:
                line = table.get(verse['verse'], '')
                found = sorted({m.lower() for m in re.findall(rf'\w*(?:{stems})\w*', line, flags=re.I)})
                for f in found or ['(none)']:
                    tallies[name][re.sub(r's$', '', f)] += 1
                cells.append(', '.join(found) or '—')
            rows.append(f"| {verse['id']} | " + ' | '.join(cells) + ' |')
        out.append(f'## {lemma} ({len(rows)} verses)\n')
        for name, _, _ in versions:
            out.append(f"- **{name}:** " + ', '.join(f'{k} {n}' for k, n in tallies[name].most_common(8)))
        out += ['', '| verse | DRB | MS1932 | DM1962 | pt-PT |', '| --- | --- | --- | --- | --- |', *rows, '']
    (here / 'renderings.md').write_text('\n'.join(out), encoding='utf-8')
    for line in out:
        if line.startswith('## ') or line.startswith('- **') or line.startswith('Verses found'):
            print(line)


main()
