"""The law-vocabulary of Ps 118, counted from the DO Latin — per term, per stanza, per verse.

Run from the repo root:  python3.13 research/psalterium/ps118/terms.py [--psalter]
Writes ps118/terms.md (the tables quoted in words/ps118-terms.md). With --psalter also counts each
term in the other 149 psalms, so that "frequent in Ps 118, rare elsewhere" can be seen.

Nouns only: the verbs mandásti (118:4, 118:138) and júdica (118:154) are excluded on purpose.
"""

import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from latin import doLatin, readVerses, words  # noqa: E402

here = Path(__file__).resolve().parent

# lemma → regex over folded lowercase words (j→i, no accents)
terms = {
    'lex': r'^(lex|legis|legi|legem|lege|leges|legum|legibus)$',
    'testimonium': r'^testimoni',
    'mandatum': r'^mandat(um|i|o|a|orum|is)$',
    'iustificatio': r'^iustificatio',
    'iudicium': r'^iudici',
    'verbum': r'^verb(um|i|o|a|orum|is)$',
    'sermo': r'^sermo(n|$)',
    'eloquium': r'^eloqui',
    'via': r'^(via|viae|viam|vias|viis|viarum)$',
    'semita': r'^semit',
    'praeceptum': r'^praecept',
    'iustitia': r'^iustiti',
    'veritas': r'^veritat|^veritas$',
    'aequitas': r'^aequita',
    'mirabilia': r'^mirabil',
    'ordinatio': r'^ordinatio',
    'misericordia': r'^misericordi',
    'miserationes': r'^miseration',
    'salutare': r'^salutar',
    'salus': r'^salus$|^salutis$|^salutem$|^salute$',
    'nomen': r'^nomen$|^nomini',
    'timor': r'^timor',
    'bonitas': r'^bonitat|^bonitas$',
    'disciplina': r'^disciplin',
    'scientia': r'^scienti',
    'intellectus': r'^intellectu',
}
lawEight = ['lex', 'testimonium', 'mandatum', 'iustificatio', 'iudicium', 'verbum', 'sermo', 'eloquium']
stanzaNames = 'Aleph Beth Ghimel Daleth He Vav Zai Heth Teth Joth Caph Lamed Mem Nun Samech Ain Phe Sade Coph Res Sin Thau'.split()


def count(verses):
    perVerse = defaultdict(list)
    for verse in verses:
        for word in words(verse['text']):
            for lemma, pattern in terms.items():
                if re.search(pattern, word):
                    perVerse[verse['id']].append((lemma, word))
    return perVerse


def main():
    verses = readVerses(doLatin / 'Psalmorum/Psalm118.txt')
    perVerse = count(verses)
    totals, forms = Counter(), defaultdict(Counter)
    stanza = defaultdict(Counter)
    for index, verse in enumerate(verses):
        for lemma, word in perVerse[verse['id']]:
            totals[lemma] += 1
            forms[lemma][word] += 1
            stanza[index // 8][lemma] += 1

    out = ['# Ps 118 — the law-vocabulary, counted\n', 'Generated by `ps118/terms.py`; do not edit. Folded spelling (j→i). Nouns only.\n']
    out += ['## Totals\n', '| lemma | n | singular/plural forms |', '| --- | --- | --- |']
    for lemma, n in totals.most_common():
        out.append(f"| {lemma} | {n} | {', '.join(f'{w} {c}' for w, c in forms[lemma].most_common())} |")

    out += ['', '## The eight law-words by stanza\n', '| stanza | verses | ' + ' | '.join(lawEight) + ' | via | sum of eight |', '| --- | --- | ' + ' | '.join('---' for _ in lawEight) + ' | --- | --- |']
    for s in range(22):
        row = [stanza[s][t] for t in lawEight]
        out.append(f"| {stanzaNames[s]} | {s * 8 + 1}–{s * 8 + 8} | " + ' | '.join(str(n or '·') for n in row) + f" | {stanza[s]['via'] or '·'} | {sum(row)} |")
    out.append(f"| **all** | 1–176 | " + ' | '.join(str(totals[t]) for t in lawEight) + f" | {totals['via']} | {sum(totals[t] for t in lawEight)} |")

    none = [v['id'] for v in verses if not any(l in lawEight for l, _ in perVerse[v['id']])]
    two = [f"{v['id']} ({' + '.join(l for l, _ in perVerse[v['id']] if l in lawEight)})" for v in verses if sum(l in lawEight for l, _ in perVerse[v['id']]) >= 2]
    out += ['', f'## Verses with none of the eight ({len(none)})\n', ', '.join(none), '', f'## Verses with two or more of the eight ({len(two)})\n', ', '.join(two), '']

    closing = Counter()
    for verse in verses:
        for colon in re.split(r'[†‡*]', verse['text']):
            found = words(colon)
            if not found:
                continue
            # the law-word "ends the colon" when it is the last word, or is followed only by tuus/eius/oris tui…
            tail = found[-3:]
            for lemma in lawEight:
                hits = [i for i, w in enumerate(tail) if re.search(terms[lemma], w)]
                if hits and all(re.search(r'^(tu[aoiu]|tuis|tuum|tuam|tuas|tuos|tuorum|tuarum|tuae|eius|oris|mei|meo)', w) for w in tail[hits[-1] + 1 :]):
                    closing[lemma] += 1
    out += ['## How often each closes a colon (alone or with its possessive)\n', '| lemma | n closing | n total |', '| --- | --- | --- |']
    out += [f'| {t} | {closing[t]} | {totals[t]} |' for t in lawEight] + ['']

    out += ['## Per verse\n', '| verse | terms |', '| --- | --- |']
    out += [f"| {v['id']} | {', '.join(f'{l} ({w})' for l, w in perVerse[v['id']]) or '—'} |" for v in verses]

    if '--psalter' in sys.argv:
        elsewhere = Counter()
        wherePsalms = defaultdict(Counter)
        for psalm in range(1, 151):
            if psalm == 118:
                continue
            for vid, hits in count(readVerses(doLatin / f'Psalmorum/Psalm{psalm}.txt')).items():
                for lemma, _ in hits:
                    elsewhere[lemma] += 1
                    wherePsalms[lemma][psalm] += 1
        out += ['', '## The same lemmas in the other 149 psalms\n', '| lemma | Ps 118 | elsewhere | share in Ps 118 | psalms with most |', '| --- | --- | --- | --- | --- |']
        for lemma in terms:
            total = totals[lemma] + elsewhere[lemma]
            share = f'{100 * totals[lemma] // total}%' if total else '—'
            top = ', '.join(f'{p} (×{n})' for p, n in wherePsalms[lemma].most_common(5))
            out.append(f'| {lemma} | {totals[lemma]} | {elsewhere[lemma]} | {share} | {top} |')

    (here / 'terms.md').write_text('\n'.join(out) + '\n', encoding='utf-8')
    print('\n'.join(out[: out.index('## Per verse\n')]))
    if '--psalter' in sys.argv:
        print('\n'.join(out[out.index('## The same lemmas in the other 149 psalms\n') :]))


main()
