export { AdoptSheet } from './AdoptSheet'
export { cadenceLabel } from './cadence'
export { type TemplateListItem, useTemplateList, useTemplateManifest } from './hooks'
export { ProposedPractices } from './ProposedPractices'
export { resolvePracticeIcon, resolvePracticeName } from './resolvePractice'
export { TemplateHero } from './TemplateHero'
