"""Build ps067/prayed.json draft 1. Run: python3.13 research/psalterium/ps067/build_v1.py"""
import json
from pathlib import Path

here = Path(__file__).resolve().parent

verses = {
    '67:2': 'Levante-se Deus, e sejam dispersos os seus inimigos, * e fujam da sua face os que o odeiam.',
    '67:3': 'Como {deficit}: * como escorre a cera {facie3a}, assim pereçam os pecadores {facie3b}.',
    '67:4': 'E os justos se banqueteiem, e exultem {consp4}: * e se deleitem na alegria.',
    '67:5a': 'Cantai a Deus, entoai um salmo ao seu nome: * {iter} que sobe sobre o poente: {reverentia} é o seu nome.',
    '67:5b': 'Exultai {consp5}: * serão perturbados {facie5b}, do pai dos órfãos e do juiz das viúvas.',
    '67:6b': 'Deus está no seu lugar santo: * Deus, que faz {moris} habitar numa casa:',
    '67:7b': 'Que faz sair os presos com força, * igualmente {exasperant}, os que habitam nos sepulcros.',
    '67:8': 'Deus, quando saíeis {consp8}, * quando passáveis pelo deserto:',
    '67:9': 'A terra foi abalada, {etenim9} os céus gotejaram {facie9a}, * {facie9b}.',
    '67:10': '{segregabis}, Deus, para a vossa herança {voluntaria}: * e ela enfraqueceu, mas vós a aperfeiçoastes.',
    '67:11': 'Os vossos animais habitarão nela: * na vossa doçura preparastes para o pobre, Deus.',
    '67:12': 'O Senhor dará a palavra {evangelizantibus}, * com grande poder.',
    '67:13': '{rex}: * {speciei} os despojos.',
    '67:14': 'Se dormirdes {cleros}, asas de pomba prateadas, * e a parte de trás do seu dorso {pallore}.',
    '67:15': 'Enquanto o Celeste separa reis sobre ela, ficarão brancos de neve no Selmon: * monte de Deus, {pinguis15}.',
    '67:16b': 'Monte coalhado, {pinguis16}: * {suspicamini} montes coalhados?',
    '67:17b': 'Monte em que agradou a Deus habitar: * {etenim17} o Senhor habitará para sempre.',
    '67:18': '{currus}, milhares dos que se alegram: * o Senhor está entre eles, no Sinai, {sancto18}.',
    '67:19a': 'Subistes ao alto, {captivitatem}: * recebestes dons {hominibus}.',
    '67:19b': '{etenim19} {credentes} * {inhabitare}',
    '67:20': 'Bendito o Senhor dia após dia: * o Deus {salutarium} nos fará próspero o caminho.',
    '67:21': 'O nosso Deus é o Deus que salva: * e do Senhor, do Senhor são as saídas da morte.',
    '67:22': 'Todavia, Deus quebrará as cabeças dos seus inimigos: * {capilli} dos que andam nas suas faltas.',
    '67:23': 'Disse o Senhor: {convertam23a}, * {convertam23b} ao fundo do mar:',
    '67:24': 'Para que o teu pé se tinja no sangue: * a língua dos teus cães, dos inimigos, {abipso}.',
    '67:25': 'Viram {ingressus25a}, Deus: * {ingressus25b} do meu Deus, do meu Rei, que está {sancto25}.',
    '67:26': 'Adiantaram-se os príncipes, unidos aos que entoavam salmos: * no meio {tympanistriarum}.',
    '67:27': 'Nas assembleias bendizei a Deus, ao Senhor, * das fontes de Israel.',
    '67:28a': 'Ali está Benjamim, muito jovem: * {excessu}.',
    '67:28b': 'Os príncipes de Judá, os seus guias: * os príncipes de Zabulon, os príncipes de Neftali.',
    '67:29': 'Dai ordem, Deus, ao vosso poder: * confirmai, Deus, isto que operastes em nós.',
    '67:30': 'Do vosso templo em Jerusalém, * os reis vos oferecerão dádivas.',
    '67:31a': 'Repreendei {arundinis}, a congregação dos touros entre as vacas dos povos: * para que excluam os que foram provados com a prata.',
    '67:31b': 'Dispersai as nações que querem guerras: virão embaixadores do Egito: * a Etiópia adiantará as suas mãos a Deus.',
    '67:33a': 'Reinos da terra, cantai a Deus: * entoai salmos ao Senhor.',
    '67:33b': 'Entoai salmos a Deus, que sobe sobre {caelicaeli}, * para o oriente.',
    '67:34b': 'Eis que ele dará à sua voz uma voz de poder: dai glória a Deus sobre Israel, * a sua magnificência, e o seu poder, nas nuvens.',
    '67:36': 'Maravilhoso é Deus nos seus santos, o Deus de Israel, ele mesmo dará poder e força ao seu povo, * {benedictus}.',
}


def opt(label, forms, note, source):
    return {'label': label, 'forms': forms, 'note': note, 'from': source}


def dec(id, refs, latin, kind, why, options):
    return {'id': id, 'refs': refs, 'latin': latin, 'kind': kind, 'why': why, 'options': options}


decisions = [
    dec('afacie', ['67:3', '67:5b', '67:9'], 'a fácie (ignis, Dei, ejus, Dei Sínai, Dei Israël)', 'word',
        'The Latin says *a fácie* seven times in the psalm (67:2, 3 twice, 5b, 9 twice) and 67:3 sets fire and God side by side under the same phrase. The glossary keeps the face (*diante da face de*, row *fácies*, with *à face de* as its named alternative). *Diante da face de* twice in 67:3 puts the second colon seven syllables over the Latin; *à face de* keeps the face and the echo fire/God at the Latin\'s length. 67:2, with a verb of flight, keeps *fujam da sua face* (row *a fácie terræ → da face de*).',
        [opt('à face de', {'facie3a': 'à face do fogo', 'facie3b': 'à face de Deus', 'facie5b': 'à face dele', 'facie9a': 'à face do Deus do Sinai', 'facie9b': 'à face do Deus de Israel'},
             'draft — the glossary row\'s alternative; the face kept, the fire/God echo kept, the length of the Latin kept', 'draft'),
         opt('diante da face de', {'facie3a': 'diante da face do fogo', 'facie3b': 'diante da face de Deus', 'facie5b': 'diante da face dele', 'facie9a': 'diante da face do Deus do Sinai', 'facie9b': 'diante da face do Deus de Israel'},
             'the glossary row\'s main form; 67:3b +7 syllables, 67:9 heavy', 'glossary'),
         opt('diante de', {'facie3a': 'diante do fogo', 'facie3b': 'diante de Deus', 'facie5b': 'diante dele', 'facie9a': 'diante do Deus do Sinai', 'facie9b': 'diante do Deus de Israel'},
             'DRB "before the fire … at the presence of God", MS1932 *diante do fogo … diante de Deus*: plain, but the face the Latin names seven times is gone', 'DRB')]),
    dec('deficit', ['67:3'], 'Sicut déficit fumus, defíciant', 'word',
        'One verb twice, of smoke and of the enemies. The glossary\'s *defícere → desfalecer* (open) is a man fainting; smoke does not faint. ἐκλείπει: to fail, give out, vanish. *Desfazer-se* is plain, says the smoke thinning away, and holds the repetition. No *assim* is supplied in the first colon, where the Latin has none (it has *sic* only in the second).',
        [opt('se desfaz … desfaçam-se', {'deficit': 'se desfaz a fumaça, desfaçam-se'}, 'draft — the repetition kept, the smoke\'s own verb', 'draft'),
         opt('se desvanece … desvaneçam-se', {'deficit': 'se desvanece a fumaça, desvaneçam-se'}, 'MS1932 *Como se desvanece o fumo, assim eles se desvaneçam*; a step more literary', 'MS1932'),
         opt('desaparece … desapareçam', {'deficit': 'desaparece a fumaça, desapareçam'}, 'plainest; heavier by two syllables', 'draft'),
         opt('desfalece … desfaleçam', {'deficit': 'desfalece a fumaça, desfaleçam'}, 'the glossary row *defícere → desfalecer*; smoke does not faint', 'glossary')]),
    dec('conspectu', ['67:4', '67:5b', '67:8'], 'in conspéctu (Dei, ejus, pópuli tui)', 'glossary',
        'Three places. The glossary row (*conspéctus*, open) gives *à vista de* for predicates and *na presença* where the phrase hangs beside a verb or noun, and warns that *à vista* fails with verbs of motion. 67:4 and 67:5b are joy before God (*exultem na presença de Deus* — *exultem à vista de Deus* sounds like spectators); 67:8 is the going-out of God seen by his people, where *à vista do vosso povo* is exactly DRB\'s *in the sight of*. Two renderings for one phrase, each where it works.',
        [opt('na presença (4, 5b) · à vista (8)', {'consp4': 'na presença de Deus', 'consp5': 'na presença dele', 'consp8': 'à vista do vosso povo'}, 'draft', 'draft'),
         opt('à vista, all three', {'consp4': 'à vista de Deus', 'consp5': 'à vista dele', 'consp8': 'à vista do vosso povo'}, 'one word for the Latin\'s one phrase; the joy of 4 and 5b turns into being watched', 'glossary'),
         opt('diante de, all three', {'consp4': 'diante de Deus', 'consp5': 'diante dele', 'consp8': 'diante do vosso povo'}, 'DRB "before God … before him"; in 67:8 *saíeis diante do vosso povo* is "went out ahead of" — MS1932\'s *à frente*, an interpretation; and *diante* is already the voice of other phrases in the glossary', 'DRB')]),
    dec('iter', ['67:5a'], 'iter fácite ei', 'word',
        'ὁδοποιήσατε, "make a road". The natural Portuguese *abri caminho* is a bare *vós* imperative equal to "I opened" (rule 3, D13). *Fazei caminho para* keeps the Latin\'s own verb and noun (*iter → caminho*, row *iter*). *Preparai o caminho* is Isaiah\'s and the Baptist\'s (*paráte viam*), another verb.',
        [opt('fazei caminho para aquele', {'iter': 'fazei caminho para aquele'}, 'draft — the Latin\'s verb and noun; safe at the imperative', 'draft'),
         opt('preparai o caminho para aquele', {'iter': 'preparai o caminho para aquele'}, 'MS1932 *aparelhai o caminho*; *paráre* is another verb (67:11 *parásti*)', 'MS1932'),
         opt('abri caminho para aquele', {'iter': 'abri caminho para aquele'}, 'the most natural idiom — excluded: bare *abri* is also "I opened" (D1, D13)', 'draft')]),
    dec('reverentia', ['67:5a'], '(fit reverentia) Dóminus nomen illi', 'grammar',
        'DO\'s Latin carries the rubric *(fit reverentia)* inside the verse, at the Name: a bow is made. Rule 4 excludes `(20)` markers and `(Aleph)` labels; a rubric is neither — it tells the one praying what to do, and the Portuguese text is meant for DO\'s own file (D12). Kept, translated, in parentheses (the checks strip parentheses). **For the coordinator:** if rubrics are meant to be dropped, option 2 drops it; 110:9b and 112:2 have the same rubric (grep).',
        [opt('(faz-se reverência) o Senhor', {'reverentia': '(faz-se reverência) o Senhor'}, 'draft — the rubric translated in place', 'draft'),
         opt('(inclina-se a cabeça) o Senhor', {'reverentia': '(inclina-se a cabeça) o Senhor'}, 'names the gesture; *reveréntia* does not say which', 'draft'),
         opt('o Senhor (no rubric)', {'reverentia': 'o Senhor'}, 'the rubric left to the Latin column', 'draft')]),
    dec('moris', ['67:6b'], 'qui inhabitáre facit uníus moris in domo', 'word',
        '*uníus moris* (μονοτρόπους): "of one way of life, of one manner" (DRB "men of one manner"). The Latin\'s *mos* is custom, manner. *Os de um só costume* keeps the word; the causative follows the glossary row *inhabitáre facit → fazer habitar* (28:10), with the subject of the infinitive before it so that *numa casa* can close the colon as *in domo* closes the Latin.',
        [opt('os de um só costume', {'moris': 'os de um só costume'}, 'draft', 'draft'),
         opt('os que têm um mesmo viver', {'moris': 'os que têm um mesmo viver'}, 'MS1932; *viver* as a noun is literary', 'MS1932'),
         opt('os de um só modo de vida', {'moris': 'os de um só modo de vida'}, 'plainer, longer; *vida* is not the Latin\'s word', 'draft')]),
    dec('exasperant', ['67:7b'], 'simíliter eos qui exásperant', 'glossary',
        '*exasperáre* is always intransitive in the psalter (65:7, 67:7b, 77:8 — grep), παραπικραίνω, "to embitter, provoke". D27 gave *provocar* to *exacerbáre* and *irritáre* (παροξύνω, God the object); this is another Greek verb and has no object, so it keeps its cognate. *Exasperar* is common Brazilian speech ("isso me exaspera"). Proposed to the glossary as open, for 65:7 and 77:8.',
        [opt('os que exasperam', {'exasperant': 'os que exasperam'}, 'draft — the cognate, no object supplied', 'draft'),
         opt('os que provocam', {'exasperant': 'os que provocam'}, 'D27\'s verb for another Greek; merges the two', 'glossary'),
         opt('os que o irritam', {'exasperant': 'os que o irritam'}, 'MS1932; supplies an object the Latin lacks, and *irritar* is *irritáre*\'s', 'MS1932')]),
    dec('segregabis', ['67:10'], 'Plúviam voluntáriam segregábis, Deus, hereditáti tuæ', 'word',
        '*segregáre* (ἀφοριεῖς): to set apart. *Separar* would be its plain cognate, but 67:15 *discérnit* has *separar* by D42 (the Latin\'s two verbs would merge five verses apart). *Reservar para* is "set apart for" (DRB "set aside for thy inheritance", MS1932 *reservaste*). The future is kept.',
        [opt('Reservareis', {'segregabis': 'Reservareis'}, 'draft', 'draft'),
         opt('Separareis', {'segregabis': 'Separareis'}, 'the cognate sense; collides with 67:15 *separa* (D42 *discérnere*)', 'draft')]),
    dec('voluntaria', ['67:10'], 'plúviam voluntáriam', 'word',
        'ἑκούσιον, "freely given". DRB keeps it ("a free rain"). *Uma chuva voluntária* is the Latin\'s adjective and strange in Portuguese as it is strange in Latin; *generosa* says the gift\'s quality and leans toward abundance (MS1932 *abundante* is the Hebrew\'s "rain of plenty").',
        [opt('uma chuva voluntária', {'voluntaria': 'uma chuva voluntária'}, 'draft — the Latin\'s word', 'draft'),
         opt('uma chuva generosa', {'voluntaria': 'uma chuva generosa'}, 'plainer; interprets', 'draft'),
         opt('uma chuva dada de livre vontade', {'voluntaria': 'uma chuva dada de livre vontade'}, 'the row *voluntárie → de livre vontade*; long', 'glossary')]),
    dec('evangelizantibus', ['67:12'], 'evangelizántibus', 'word',
        'εὐαγγελιζομένοις. *Anunciar a boa-nova* spells out what the verb says, but it puts the colon 7 syllables over the Latin (21 against 14). *Evangelizar* is the Latin\'s own word, current in Brazil, and gives the Latin\'s length exactly. It now names the Church\'s mission, and the Church has always read this verse as the preaching of the Gospel, so the cognate narrows nothing the tradition did not already hear in it.',
        [opt('aos que evangelizam', {'evangelizantibus': 'aos que evangelizam'}, 'draft — the cognate, the Latin\'s length', 'draft'),
         opt('aos que anunciam a boa-nova', {'evangelizantibus': 'aos que anunciam a boa-nova'}, 'DRB "them that preach good tidings", MS1932 *anunciam a boa nova*; +7 syllables', 'DRB')]),
    dec('rex', ['67:13'], 'Rex virtútum dilécti, dilécti', 'ambiguity',
        'Verbless in the Latin and the Greek. DRB supplies "is": "The king of powers is of the beloved, of the beloved". A second parse is possible: "the King of the powers of the beloved". The copula (grammar, D2) follows DRB; the doubled *dilécti* stays doubled. *Rex virtútum* follows D43 *Dóminus virtútum → o Senhor dos poderes*; *diléctus* → *o amado* (row, 28:6).',
        [opt('O Rei dos poderes é do amado, do amado', {'rex': 'O Rei dos poderes é do amado, do amado'}, 'draft — DRB\'s copula', 'draft'),
         opt('O Rei dos poderes do amado, do amado', {'rex': 'O Rei dos poderes do amado, do amado'}, 'verbless, as the Latin; both parses left open, and the colon hard to hear', 'draft'),
         opt('O Rei dos exércitos é do amado, do amado', {'rex': 'O Rei dos exércitos é do amado, do amado'}, 'MS1932, DRB-family *exércitos* (the Hebrew\'s Sabaoth) — D43\'s option', 'MS1932')]),
    dec('speciei', ['67:13'], 'et speciéi domus divídere spólia', 'grammar',
        'A dative and an infinitive: "and to the beauty of the house, to divide spoils" (ὡραιότητι τοῦ οἴκου διελέσθαι σκῦλα). DRB turns it into a future (*the beauty of the house shall divide spoils*). *Cabe* supplies the verb Portuguese needs for a dative + infinitive ("it falls to"), keeping both the dative and the infinitive. *spécies → beleza* (D43); *spólia → despojos* (row); *divídere* (land, spoil) → *repartir* (row *partíri / divídere*).',
        [opt('e à beleza da casa cabe repartir', {'speciei': 'e à beleza da casa cabe repartir'}, 'draft', 'draft'),
         opt('e à beleza da casa, repartir', {'speciei': 'e à beleza da casa, repartir'}, 'verbless, as the Latin; hard to hear', 'draft'),
         opt('e a beleza da casa repartirá', {'speciei': 'e a beleza da casa repartirá'}, 'DRB, MS1932 (*reparte*): a subject and a finite verb the Latin does not have', 'DRB')]),
    dec('cleros', ['67:14'], 'inter médios cleros', 'word',
        'κλῆροι: lots cast, and the portions allotted by lot. DRB "among the midst of lots". *Sortes* is heard in Brazil as luck; *lotes* as plots of building land; *heranças* collides with *heréditas* (67:10). *Partilhas* is the share-out of an inheritance — the allotted portion, which is κλῆρος.',
        [opt('no meio das partilhas', {'cleros': 'no meio das partilhas'}, 'draft', 'draft'),
         opt('no meio das sortes', {'cleros': 'no meio das sortes'}, 'the lots themselves; heard as luck', 'DRB'),
         opt('no meio dos lotes', {'cleros': 'no meio dos lotes'}, 'the allotments; heard as building plots', 'draft'),
         opt('no meio das heranças', {'cleros': 'no meio das heranças'}, 'MS1932 *herdades*; collides with 67:10 *herança* (*heréditas*)', 'MS1932')]),
    dec('pallore', ['67:14'], 'in pallóre auri', 'word',
        'χλωρότης: the pale, greenish-yellow sheen. The Latin says "paleness". *Na palidez do ouro* keeps the Latin\'s noun; it is an unusual image, and it is the Latin\'s. *pennæ* → *asas* (glossary row, open; πτέρυγες).',
        [opt('na palidez do ouro', {'pallore': 'na palidez do ouro'}, 'draft — DRB "the paleness of gold"', 'draft'),
         opt('no brilho pálido do ouro', {'pallore': 'no brilho pálido do ouro'}, 'adds *brilho*; MS1932 *o brilho flavo do ouro*', 'MS1932'),
         opt('no amarelo pálido do ouro', {'pallore': 'no amarelo pálido do ouro'}, 'names the colour', 'draft')]),
    dec('pinguis', ['67:15', '67:16b'], 'mons pinguis (twice); mons coagulátus', 'glossary',
        'πῖον, "fat", beside τετυρωμένον, "curdled, cheesed". The glossary gives *pinguis → gordo* (open; *touros gordos*, *os gordos da terra*) and *coaguláre → coalhar* (118:70, milk). Rule 5: concrete images stay concrete. *Monte gordo* is also a common place name in the Portuguese-speaking world, which helps the ear accept it. *Fértil* (MS1932) explains the image.',
        [opt('monte gordo', {'pinguis15': 'monte gordo', 'pinguis16': 'monte gordo'}, 'draft — the glossary row', 'glossary'),
         opt('monte fértil', {'pinguis15': 'monte fértil', 'pinguis16': 'monte fértil'}, 'MS1932; explains the image', 'MS1932'),
         opt('monte pingue', {'pinguis15': 'monte pingue', 'pinguis16': 'monte pingue'}, 'a real Portuguese word for rich/fat, but bookish', 'draft')]),
    dec('suspicamini', ['67:16b'], 'ut quid suspicámini montes coagulátos?', 'ambiguity',
        '*montes coagulátos* can be the object ("why do you suspect curdled mountains?", i.e. imagine other ones — MS1932 *por que pensais em (outros) montes*) or a vocative (DRB "Why suspect, ye curdled mountains?"). ὄρη τετυρωμένα is the same in both cases. Without a comma or a preposition, *por que suspeitais montes coalhados?* keeps both: *suspeitar* + direct object is "surmise". The glossary row *suspicári → recear* (118:39) is another context (a feared reproach).',
        [opt('por que suspeitais', {'suspicamini': 'por que suspeitais'}, 'draft — both readings open', 'draft'),
         opt('por que suspeitais, (vocative)', {'suspicamini': 'por que suspeitais,'}, 'DRB\'s vocative', 'DRB'),
         opt('por que suspeitais de', {'suspicamini': 'por que suspeitais de'}, 'the object reading, decided', 'MS1932'),
         opt('por que receais', {'suspicamini': 'por que receais'}, 'the glossary row (118:39)', 'glossary')]),
    dec('etenim', ['67:9', '67:17b', '67:19b'], 'étenim (three times)', 'glossary',
        'The glossary gives *étenim → pois*, *nam et → pois também*. In all three places here the Greek is καὶ γάρ and the *et* carries weight: the heavens too (67:9), the Lord too (67:17b), even the unbelievers (67:19b). *Pois também* in all three, one form for the psalm.',
        [opt('pois também', {'etenim9': 'pois também', 'etenim17': 'pois também', 'etenim19': 'Pois também'}, 'draft', 'draft'),
         opt('pois', {'etenim9': 'pois', 'etenim17': 'pois', 'etenim19': 'Pois'}, 'the glossary row', 'glossary')]),
    dec('currus', ['67:18'], 'Currus Dei decem míllibus múltiplex', 'word',
        'The glossary row *currus* (19:8) became *carros de guerra* because a blind reader heard automobiles; it left 67:18 to decide. Here the chariot is God\'s, among thousands, at Sinai; the ear has less room for a car, but the risk is real. *múltiplex* ("manifold") as a participle, *multiplicado dez mil vezes* (μυριοπλάσιον).',
        [opt('O carro de Deus, multiplicado dez mil vezes', {'currus': 'O carro de Deus, multiplicado dez mil vezes'}, 'draft — DRB "chariot", MS1932 *O carro de Deus*', 'draft'),
         opt('O carro de guerra de Deus, multiplicado dez mil vezes', {'currus': 'O carro de guerra de Deus, multiplicado dez mil vezes'}, 'the 19:8 form; heavy', 'glossary'),
         opt('A carruagem de Deus, multiplicada dez mil vezes', {'currus': 'A carruagem de Deus, multiplicada dez mil vezes'}, 'no car; loses the war', 'draft')]),
    dec('sancto', ['67:18', '67:25'], 'in sancto (twice)', 'glossary',
        'The glossary row *sancta / sanctum (a place)* gives *o lugar santo* where the phrase is plainly a place; 59:8 kept *no seu santo* where the bare neuter was open. In 67:18 it stands beside *in Sina*, and in 67:25 after *regis mei qui est*: a place both times (DRB "in the holy place … in his sanctuary").',
        [opt('no lugar santo', {'sancto18': 'no lugar santo', 'sancto25': 'no lugar santo'}, 'draft — the row', 'glossary'),
         opt('no santo', {'sancto18': 'no santo', 'sancto25': 'no santo'}, '59:8\'s bare neuter; leaves place / holiness / holy one open', 'draft')]),
    dec('captivitatem', ['67:19a'], 'cepísti captivitátem', 'word',
        'The Greek repeats one root (ᾐχμαλώτευσας αἰχμαλωσίαν), the Latin half-echoes it (*cepísti captivitátem*). *Levastes cativo o cativeiro* is the form Portuguese has for this line (Eph 4:8, *captivam duxit captivitatem* — the Clementine wording not checked here) and says "you took captives" with the Latin\'s noun (*captívitas → cativeiro*, row). *Cativastes* is "you charmed" in Brazil.',
        [opt('levastes cativo o cativeiro', {'captivitatem': 'levastes cativo o cativeiro'}, 'draft', 'draft'),
         opt('tomastes o cativeiro', {'captivitatem': 'tomastes o cativeiro'}, 'closest to *cepísti*; opaque', 'draft'),
         opt('tomastes cativos', {'captivitatem': 'tomastes cativos'}, 'MS1932 *levaste contigo cativos*; the abstract noun made concrete', 'MS1932')]),
    dec('hominibus', ['67:19a'], 'accepísti dona in homínibus', 'ambiguity',
        '*in homínibus* (ἐν ἀνθρώπῳ): "among men" or "in men" (DRB). *Entre os homens* is the Portuguese that can be said; *nos homens* keeps the preposition and sounds broken.',
        [opt('entre os homens', {'hominibus': 'entre os homens'}, 'draft', 'draft'),
         opt('nos homens', {'hominibus': 'nos homens'}, 'DRB "in men"', 'DRB')]),
    dec('credentes', ['67:19b'], 'Étenim non credéntes, * inhabitáre Dóminum Deum', 'ambiguity',
        'The hardest colon. The Latin reads naturally as an accusative + infinitive after *credéntes*: "even those not believing that the Lord God dwells" — MS1932 *mesmo pelos que não criam que o Senhor Deus habitava*. DRB takes the infinitive as a noun: "for those also that do not believe, the dwelling of the Lord God". The Greek (ἀπειθοῦντες τοῦ κατασκηνῶσαι) is "the disobedient, (so as) to dwell". The draft follows the natural Latin parse and keeps the fragment a fragment, as the Latin is; the imperfect *criam … habitasse* follows the past of 67:19a.',
        [opt('os que não criam * que o Senhor Deus habitasse', {'credentes': 'os que não criam', 'inhabitare': 'que o Senhor Deus habitasse.'}, 'draft — MS1932\'s parse', 'draft'),
         opt('os que não creem * na habitação do Senhor Deus', {'credentes': 'os que não creem', 'inhabitare': 'na habitação do Senhor Deus.'}, 'DRB\'s noun', 'DRB'),
         opt('os que não criam, * para que o Senhor Deus habitasse', {'credentes': 'os que não criam,', 'inhabitare': 'para que o Senhor Deus habitasse.'}, 'the Greek\'s purpose reading', 'draft')]),
    dec('salutarium', ['67:20'], 'Deus salutárium nostrórum', 'glossary',
        'A plural (σωτηρίων). D6 gives *salvação*; the plural *salvações* stands at 27:8 (*salvátio*, row). *O Deus da nossa salvação* is the phrase Portuguese prays; number is grammar (D27, on *sǽculum sǽculi*).',
        [opt('da nossa salvação', {'salutarium': 'da nossa salvação'}, 'draft — DRB "the God of our salvation", MS1932 the same', 'draft'),
         opt('das nossas salvações', {'salutarium': 'das nossas salvações'}, 'the Latin\'s number', 'draft')]),
    dec('capilli', ['67:22'], 'vérticem capílli', 'word',
        'The glossary row *vertex → o alto da cabeça* (7:17) names this verse. With *capílli* beside it, "the crown of the hair": *o alto da cabeleira* keeps both nouns and does not say *cabeça* twice after *cabeças* in the first colon. DRB "the hairy crown".',
        [opt('o alto da cabeleira', {'capilli': 'o alto da cabeleira'}, 'draft', 'draft'),
         opt('o alto da cabeça cabeluda', {'capilli': 'o alto da cabeça cabeluda'}, 'the row + an adjective; *cabeluda* is comic', 'glossary')]),
    dec('convertam', ['67:23'], 'Ex Basan convértam, * convértam in profúndum maris', 'order',
        '*convértam* twice, with no object (ἐπιστρέψω, "I will bring back"; DRB, MS1932 supply "them"). *Farei voltar* is the glossary\'s causative (*convértere*, 52:7). In the Latin\'s order the colon ends *De Basã farei voltar* before a verse ending *mar* — an accidental rhyme the Latin does not have (rule 5). Moving *de Basã* after the verb makes the repetition an anaphora in place of the Latin\'s adjacency; the words and the doubling are all kept.',
        [opt('Farei voltar de Basã, * farei voltar', {'convertam23a': 'Farei voltar de Basã', 'convertam23b': 'farei voltar'}, 'draft', 'draft'),
         opt('De Basã farei voltar, * farei voltar', {'convertam23a': 'De Basã farei voltar', 'convertam23b': 'farei voltar'}, 'the Latin\'s order; *voltar / mar* rhyme', 'draft'),
         opt('De Basã voltarei, * voltarei', {'convertam23a': 'De Basã voltarei', 'convertam23b': 'voltarei'}, 'intransitive: God himself returns — a possible reading of the bare verb', 'draft')]),
    dec('abipso', ['67:24'], 'lingua canum tuórum ex inimícis, ab ipso', 'ambiguity',
        'Elliptic in the Latin and the Greek (ἐξ ἐχθρῶν παρ᾿ αὐτοῦ). *ab ipso* can be "from him" or "from the same" (the blood — DRB "be red with the same"). *Dele mesmo* holds both (*dele* = of him / of it, *mesmo* = self / same). No verb is supplied for the second colon; the first colon\'s *se tinja* governs it, as *intingátur* governs the Latin.',
        [opt('dele mesmo', {'abipso': 'dele mesmo'}, 'draft', 'draft'),
         opt('do mesmo', {'abipso': 'do mesmo'}, 'DRB\'s reading (the same blood)', 'DRB'),
         opt('da parte dele', {'abipso': 'da parte dele'}, 'the Greek παρ᾿ αὐτοῦ, "from him"', 'draft')]),
    dec('ingressus', ['67:25'], 'ingréssus tuos … ingréssus Dei mei', 'word',
        'πορεῖαι, "goings, marches" (DRB "goings"). *ingréssus* is a going-in; the noun occurs only here in the psalter (grep). *As vossas entradas* keeps the Latin\'s noun and MS1932\'s *entrada (triunfal)*; *passos* belongs to *gressus* (16:5); *procissões* and *cortejo* interpret.',
        [opt('as vossas entradas … as entradas', {'ingressus25a': 'as vossas entradas', 'ingressus25b': 'as entradas'}, 'draft', 'draft'),
         opt('os vossos passos … os passos', {'ingressus25a': 'os vossos passos', 'ingressus25b': 'os passos'}, '*gressus*\'s word', 'draft'),
         opt('as vossas marchas … as marchas', {'ingressus25a': 'as vossas marchas', 'ingressus25b': 'as marchas'}, 'the Greek\'s πορεῖαι', 'draft')]),
    dec('tympanistriarum', ['67:26'], 'in médio juvenculárum tympanistriárum', 'word',
        'Two nouns in apposition: young women who are drummers. *tamborim* is the usual Portuguese for the biblical hand-drum (and a Brazilian instrument too); *juvéncula* → *moça*, the plain word.',
        [opt('das moças que tocavam tamborins', {'tympanistriarum': 'das moças que tocavam tamborins'}, 'draft', 'draft'),
         opt('das donzelas que tocavam tamborins', {'tympanistriarum': 'das donzelas que tocavam tamborins'}, 'MS1932 (*timbales*); *donzela* is old-fashioned', 'MS1932'),
         opt('das jovens tocadoras de tamborim', {'tympanistriarum': 'das jovens tocadoras de tamborim'}, 'two nouns, as the Latin', 'draft')]),
    dec('excessu', ['67:28a'], 'in mentis excéssu', 'glossary',
        'The glossary row *excéssus mentis → fora de mim* (30:23) names this verse. Here of Benjamin: *fora de si*. It holds ecstasy and being beside oneself, as ἐν ἐκστάσει does.',
        [opt('fora de si', {'excessu': 'fora de si'}, 'draft — the row', 'glossary'),
         opt('em êxtase', {'excessu': 'em êxtase'}, 'decides for mystical joy', 'draft'),
         opt('no arrebatamento da mente', {'excessu': 'no arrebatamento da mente'}, 'the row\'s option; keeps *mens*', 'glossary')]),
    dec('arundinis', ['67:31a'], 'feras arúndinis', 'word',
        '"The beasts of the reed" (τοῦ καλάμου). *Canavial* (MS1932) is a sugar-cane field in Brazil; *caniçal* is the exact word and little known; *juncos* are rushes, the plain word for what grows in a marsh.',
        [opt('as feras dos juncos', {'arundinis': 'as feras dos juncos'}, 'draft', 'draft'),
         opt('as feras do caniçal', {'arundinis': 'as feras do caniçal'}, 'exact, bookish', 'draft'),
         opt('as feras dos canaviais', {'arundinis': 'as feras dos canaviais'}, 'MS1932; heard as sugar cane', 'MS1932')]),
    dec('caelicaeli', ['67:33b'], 'super cælum cæli', 'word',
        'Singular in the Latin (τὸν οὐρανὸν τοῦ οὐρανοῦ). The idiom Portuguese knows is the plural *céu dos céus*, which 148:4 *cæli cælórum* will need. Kept singular here so that the two stay two.',
        [opt('o céu do céu', {'caelicaeli': 'o céu do céu'}, 'draft — the Latin\'s number', 'draft'),
         opt('o céu dos céus', {'caelicaeli': 'o céu dos céus'}, 'the idiom; merges with 148:4', 'draft')]),
    dec('benedictus', ['67:36'], 'benedíctus Deus', 'order',
        'The formula *Benedíctus Dóminus* is verbless in the psalter (*Bendito o Senhor*, D41, 67:20). *Bendito Deus*, without an article, cannot stand verbless in Portuguese; the jussive *seja* is supplied (grammar, D2). DRB "Blessed be God", MS1932 *Bendito seja Deus!*',
        [opt('bendito seja Deus', {'benedictus': 'bendito seja Deus'}, 'draft', 'draft'),
         opt('bendito Deus', {'benedictus': 'bendito Deus'}, 'verbless, as the Latin', 'draft')]),
]

choices = {
    '67:2': '*dissipéntur* (people) → *sejam dispersos*: the glossary row *dissipáre* proposes *dispersar* for people (17:15, 34:16); 67:31b *Díssipa gentes* → *Dispersai* the same. *oderunt* present in sense (*odísse*) → *odeiam*. The Latin ends on *a fácie ejus*; Portuguese order puts it before the subject. The verse is Num 10:35.',
    '67:4': '*epulári → banquetear-se* (D42), *delectári → deleitar-se* (D44), *exsultáre → exultar* (row).',
    '67:5a': '*psalmum dícite* → *entoai um salmo* (row *psállere*, 17:50 *psalmum dicam → entoarei um salmo*). *ascéndit super occásum* → *sobe sobre o poente*: *subir* as 46:6 and 67:19a, 67:33b (the same *ascéndit super*); *occásus → poente* as 49:1.',
    '67:5b': 'Vós is the plural of the people addressed (*Exsultáte*); God is in the third person, so *dele*, not *sua* (which a Brazilian ear can take as "your"). *turbabúntur* keeps its open subject. The apposition *patris … et júdicis* keeps both genitives. *órphanus → órfão* (row).',
    '67:6b': 'The copula *está* supplied (verbless Latin; D2).',
    '67:7b': '*in fortitúdine* stands after *os presos*, where it can belong to the bringing-out ("with strength") or to the bound ("bound fast") — the Latin\'s ambiguity (DRB keeps it too). *edúcere → fazer sair* (row). *simíliter* → *igualmente*.',
    '67:9': '*movéri → ser abalado* (row). *distilláre → gotejar*: the concrete drip (DRB "dropped"). *Dei Sínai* read as the Latin has it, "the God of Sinai" (the Greek\'s τοῦτο Σινα is not followed).',
    '67:10': '*infirmáta est* → *enfraqueceu*; *ela* can be the rain or the inheritance, as in the Latin. *perfícere → aperfeiçoar* (row; 67:10 is one of the places it was tried on). *tu vero* → *mas vós*.',
    '67:11': '*Animália* → *animais*, the Latin\'s concrete word (DRB "animals"). *parásti* has no object in the Latin; none supplied. *dulcédo → doçura* (row).',
    '67:12': '*virtúte multa* → *com grande poder* (row *virtus* → *poder*).',
    '67:14': '*pennæ* → *asas* (row, open; the Greek πτέρυγες). The verbless apposition *asas de pomba prateadas* is kept verbless (DRB supplies "you shall be as").',
    '67:15': '*discérnit* → *separa* (D42). *cæléstis* as a title, *o Celeste* (DRB "he that is in heaven"). *nive dealbabúntur* → *ficarão brancos de neve* (D44 *dealbári → ficar mais branco*, here without the comparative). *Selmon* as the Latin spells it.',
    '67:16b': '*coagulátus* → *coalhado* (row *coaguláre*, 118:70).',
    '67:17b': 'The Latin\'s resumptive *in quo … in eo* is one relative in Portuguese (grammar). *beneplácitum est* → *agradou* (the row *beneplácitum fácere*). *in finem* → *para sempre* (row, D27: perpetuity; εἰς τέλος).',
    '67:18': '*in eis* → *entre eles*, with *está* supplied. *Sina* and 67:9 *Sínai* are one place → *Sinai* both.',
    '67:20': '*Benedíctus Dóminus* → *Bendito o Senhor* (formula row, D41). *die cotídie* → *dia após dia*. *prósperum iter fáciet nobis* → *nos fará próspero o caminho*; the subject moved to the head of the colon (natural order).',
    '67:21': '*Deus salvos faciéndi* → *o Deus que salva*: a gerund as a relative (grammar); *salvum fácere → salvar* (row). The copula supplied, as DRB. *Dómini Dómini* doubled, as the Latin. *éxitus mortis* → *as saídas da morte* (plural, as the Greek; ways out of, or into, death — open as in the Latin).',
    '67:22': '*Verúmtamen → Todavia* (row). *confríngere → quebrar* (row). *perambuláre in → andar* (row, the Church sense). *delíctum → falta* (row).',
    '67:24': '*tuus*, *tuórum*: the Lord speaks to one (Israel) — *tu*, as D17 (address follows the speaker). *intingátur* → *se tinja*, the Latin\'s own verb (*tingo*).',
    '67:25': '*Rei* capitalised, as *meu Rei e meu Deus* (5:3).',
    '67:26': '*prævenire* intransitive → *adiantar-se* (row, 118:147–148). *conjúncti* → *unidos a*.',
    '67:27': '*In ecclésiis* → *Nas assembleias* (D34). *Deo Dómino* → *a Deus, ao Senhor* (dative repeated in apposition). *de fóntibus Israël* left bare, as the Latin (MS1932 supplies *vós que sois da estirpe de*).',
    '67:28a': '*adolescéntulus → muito jovem* (row); the copula *está* supplied.',
    '67:28b': '*duces* → *guias*, as 54:14 *dux meus → meu guia* (D44).',
    '67:29': '*Manda … virtúti tuæ* → *Dai ordem … ao vosso poder* (row *mandáre*: *dar ordem* where there is no thing as object; here a dative). *confírma hoc* → *confirmai … isto* (row *confirmáre*: *confirmar* for a thing). *operári → operar* (D43).',
    '67:30': '*A templo tuo* → *Do vosso templo*: *de* keeps "from" and lets the causal sense ("because of your temple") be heard. *múnera → dádivas* (row; it names 67:30). Cadence *dádivas* is a proparoxytone, allowed.',
    '67:31a': '*increpáre → repreender* (row). *congregátio* (συναγωγή) → *congregação* (D34\'s Greek test). *ut exclúdant* follows the Latin (positive), not the Greek\'s τοῦ μὴ ἀποκλεισθῆναι. *probáti argénto* → *provados com a prata* (row *probáre → provar*); the ablative left open (tested like silver, or with silver).',
    '67:31b': '*Díssipa gentes* → *Dispersai as nações* (row *dissipáre*, people). *legáti* → *embaixadores* (MS1932). *prævéniet manus ejus Deo* → *adiantará as suas mãos a Deus*: the row\'s verb *adiantar* used transitively ("put forward"), keeping one family with 67:26 *Adiantaram-se*.',
    '67:33a': '*psállite → entoai salmos* (D25).',
    '67:33b': '*ad Oriéntem* → *para o oriente*; it answers 67:5a *sobre o poente*.',
    '67:34b': '*dabit voci suæ vocem virtútis* → *dará à sua voz uma voz de poder*. *super Israël* can belong to *date glóriam* or to *magnificéntia ejus* (the Greek\'s reading); the second colon is left verbless so both hold. *magnificéntia → magnificência* (row). The Latin\'s inline *(35)* is not reproduced.',
    '67:36': '*Mirábilis → Maravilhoso* (row *mirábilis*). *virtus → poder*, *fortitúdo → força* (rows; kept apart). *plebs → povo* (row).',
}

prayed = {
    'psalm': 67, 'tier': 3, 'version': 1, 'address': 'vós', 'status': 'draft',
    'verses': verses, 'decisions': decisions, 'choices': choices,
    'audit': [
        {'step': 'draft', 'note': 'Psalm-level draft from the parallels (no DM1962 for this psalm). Hard readings: 67:13 (verbless Rex … dilécti; dative + infinitive), 67:14 (cleros, pallor), 67:15–17 (the fat and curdled mountains; suspicámini with object or vocative), 67:19b (non credéntes inhabitáre), 67:24 (ab ipso), 67:31a (ut exclúdant, against the Greek). The rubric (fit reverentia) in 67:5a translated and kept in parentheses — see decision reverentia. Liturgical uses (grep content/do): 67:6b + 67:36 as the Introit of Pent11-0 (*Deus in loco sancto suo … ipse dabit virtútem*), with 67:2 as its psalm verse; 67:2 also the Introit verse of Pentecost (missa Pasc7-0) and of 01-19; 67:29–30 the Offertory of Pentecost and a Pentecost Office antiphon (*Confírma hoc, Deus*).'},
        {'step': 'checks', 'note': 'Hard checks pass. Soft, all accepted: 67:3 +3 (two *à face de*, the Latin\'s own repetition); 67:5a +4 (*fazei caminho para aquele*; the rubric in parentheses is not counted) and its rhyme flag *nome / nome*, which is the Latin\'s *nómini … nomen*; 67:12 +3 after taking *evangelizam* (was +7); 67:13 +5 and +3 (a copula and a supplied *cabe* for a verbless Latin; see decisions rex, speciei); 67:15 +4 and 67:18 +4/+5 (Portuguese articles and *está*; *multiplicado dez mil vezes* for one word *múltiplex*); 67:16b −3 and 67:17b −6 (the resumptive *in eo* dropped: grammar); 67:19a +3 (*levastes cativo o cativeiro*); 67:21 +3 (the copula *são*); 67:26 +8 (*psalléntibus* → *aos que entoavam salmos*, the glossary\'s *psállere*; no shorter form keeps the psalm); 67:28b +4 (*de* before each tribe); 67:31a +3; 67:33a +3 (*psállite → entoai salmos*, D25). Oxytone cadences throughout (Deus, Israel, Senhor) are allowed.'},
    ],
}

(here / 'prayed.json').write_text(json.dumps(prayed, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print('wrote', here / 'prayed.json')
