"""Stage one of Ps 17 (17:2–17:25), draft 1 → ps017/prayed.json.
python3.13 research/psalterium/ps017/build_v1.py
Written as a script so that the options are built with one helper and the JSON cannot be malformed."""
import json
from pathlib import Path

here = Path(__file__).resolve().parent


def opt(label, forms, note, source='draft'):
    return {'label': label, 'forms': forms, 'note': note, 'from': source}


def dec(id, refs, latin, kind, why, options):
    return {'id': id, 'refs': refs, 'latin': latin, 'kind': kind, 'why': why, 'options': options}


verses = {
    '17:2': 'Eu vos amarei, Senhor, {fortitudo}: * o Senhor é {firmamentum}, e o meu refúgio, e o meu libertador.',
    '17:3b': 'O meu Deus é {adjutor}, * e nele esperarei.',
    '17:3c': '{v3c} {protector}, e {cornu} da minha salvação, * e o meu amparo.',
    '17:4': '{laudans}: * e serei salvo dos meus inimigos.',
    '17:5': 'Cercaram-me as dores da morte, * e as torrentes da iniquidade me perturbaram.',
    '17:6': 'As dores do {inferni} me cercaram, * {s6} os laços da morte.',
    '17:7a': 'Na minha tribulação invoquei o Senhor, * e clamei ao meu Deus.',
    '17:7b': 'E do seu templo santo ele escutou a minha voz, * e o meu clamor, {c7}, entrou nos seus ouvidos.',
    '17:8': 'A terra {m8a} e estremeceu, * os fundamentos dos montes {m8b} e {m8c}, porque ele se irou contra eles.',
    '17:9': 'Subiu {fumus} na sua ira, † e da sua face um fogo se inflamou, * {carb9} foram acesos por ele.',
    '17:10': 'Inclinou os céus, e desceu, * e {caligo} sob os seus pés.',
    '17:11': 'E subiu sobre os querubins, e voou: * voou sobre as asas dos ventos.',
    '17:12': 'E {posuit}, † ao seu redor a sua tenda: * água tenebrosa nas nuvens do ar.',
    '17:13': 'Ao fulgor {c13} passaram as nuvens, * granizo e {carb13} de fogo.',
    '17:14': 'E o Senhor trovejou do céu, † e o Altíssimo {vocem}: * granizo e {carb14} de fogo.',
    '17:15': 'E enviou as suas setas, e os {dissipavit}: * multiplicou os relâmpagos, e os perturbou.',
    '17:16a': 'E apareceram as fontes das águas, * e foram desvendados os fundamentos {orbis}:',
    '17:16b': '{increpatio}, Senhor, * ao sopro do espírito da vossa ira.',
    '17:17': 'Enviou do alto, e me tomou, * e me {assumpsit} de muitas águas.',
    '17:18': 'Arrancou-me dos meus fortíssimos inimigos, † e dos que me odeiam, * porque se fortaleceram {super}.',
    '17:19': '{s19} no dia da minha aflição, * e o Senhor se fez {p19}.',
    '17:20': 'E me {eduxit} para a amplidão, * salvou-me, porque {voluit}.',
    '17:21': 'E o Senhor {r21a} segundo a minha justiça, * e segundo a pureza das minhas mãos {r21b}.',
    '17:22': 'Porque guardei os caminhos do Senhor, * e não agi como ímpio {impie}.',
    '17:23': 'Porque todos os seus juízos estão {c23}, * e não afastei de mim {justitias}.',
    '17:24': 'E serei imaculado {cumeo}, * e me {observabo} da minha iniquidade.',
    '17:25': 'E o Senhor {r25} segundo a minha justiça, * e segundo a pureza das minhas mãos {c25}.',
}

decisions = [
    dec('fortitudo', ['17:2'], 'fortitúdo mea', 'glossary',
        'The psalm opens on a string of titles of God, each a word the psalter uses again (fortitúdo, firmaméntum, refúgium, liberátor; then adjútor, protéctor, cornu salútis, suscéptor). fortitúdo → força is the glossary\'s working word (117:14 Fortitúdo mea, et laus mea Dóminus; also 30:4, 42:2 with the same "fortitúdo mea").',
        [opt('minha força', {'fortitudo': 'minha força'}, 'Ruling: the glossary row (open) — plain, and left free by virtus → poder. The possessive without article in the vocative, as Portuguese says it (Senhor, minha força).', 'glossary'),
         opt('minha fortaleza', {'fortitudo': 'minha fortaleza'}, 'Matos Soares 1932 (que és a minha fortaleza) and DM1962 (minha fôrça … minha fortaleza, for another Hebrew word). Refused as the glossary refuses it: in Brazil a fortaleza is first a fortress — and a fortress would be heard beside refúgio as one more building.', 'MS1932')]),
    dec('firmamentum', ['17:2'], 'Dóminus firmaméntum meum', 'word',
        'firmaméntum (στερέωμα) is "a support, a prop" (Lewis & Short) and also the vault of heaven — the same Latin word is the sky in 18:2 and 150:1 and God as support here, 24:14 and 70:3 (grep, nine lines). Portuguese firmamento is only the sky. The Latin ear hears both; the Portuguese ear will hear only the sky.',
        [opt('o meu firmamento', {'firmamentum': 'o meu firmamento'}, 'Ruling, to be tested on the blind reader: the Latin\'s word, which keeps the psalter\'s one word for the vault and for the stay (18:2, 150:1 in firmaménto virtútis ejus) and is sayable. Risk: heard as "my sky". If the blind reader hears only the sky, draft 2 moves to option 1.'),
         opt('o meu esteio', {'firmamentum': 'o meu esteio'}, 'A concrete prop (a post that holds something up), and a living figure in Brazil (o esteio da família); keeps the image of support. Loses the root firm- and the link with the sky.'),
         opt('o meu firme apoio', {'firmamentum': 'o meu firme apoio'}, 'Matos Soares 1932: the sense spelled out in two words; keeps firm-.', 'MS1932'),
         opt('a minha firmeza', {'firmamentum': 'a minha firmeza'}, 'Keeps the root in one word; but a quality where the Latin names a thing that holds.')]),
    dec('adjutor', ['17:3b'], 'Deus meus adjútor meus', 'glossary',
        'adjútor → auxílio is the glossary\'s working rendering (117:6–7, 118:114, 9:10, 9:35b); the Latinist has asked for the agent noun auxiliador in each of those psalms. Here the question is sharper: 17:2–3 set four agent nouns side by side (liberátor, adjútor, protéctor, suscéptor) and the Portuguese makes two of them agents (libertador, protetor) and two abstract (auxílio, amparo — D19 settled the latter).',
        [opt('o meu auxílio', {'adjutor': 'o meu auxílio'}, 'Ruling: the glossary, as held in Pss 9, 117 and 118 (D24). The metonymy is the same as suscéptor → amparo three words later, which is settled.', 'glossary'),
         opt('o meu auxiliador', {'adjutor': 'o meu auxiliador'}, 'The agent noun the Latinist keeps asking for; it would make the series libertador · auxiliador · protetor regular. Long (five syllables) and hardly said.', 'latinist')]),
    dec('v3c', ['17:3c'], 'Protéctor meus, et cornu salútis meæ, et suscéptor meus', 'grammar',
        'The Latin carries the titles on without a verb from 17:2 into 17:3c. 17:3b needs a copula (the Deus meus is not a vocative: "et sperábo in eum" follows in the third person); 17:3c can continue the list bare.',
        [opt('O meu', {'v3c': 'O meu'}, 'Ruling: the list continues without a verb, as the Latin; the verse is heard as more names, after "O meu Deus é o meu auxílio".'),
         opt('É o meu', {'v3c': 'É o meu'}, 'Matos Soares 1932 (É o meu protector): a copula supplied; clearer, heavier at the head of the verse.', 'MS1932')]),
    dec('protector', ['17:3c', '17:19'], 'protéctor meus', 'glossary',
        'protéctor (ὑπερασπιστής, the one who holds a shield over) is in the psalter 19 times (grep); the glossary names protéctor → protetor only as what suscéptor → amparo must stay apart from. This psalm has it three times (17:3c, 17:19, 17:31), beside suscéptor and adjútor in one verse (17:3b–3c). Proposed as a row.',
        [opt('protetor', {'protector': 'protetor', 'p19': 'o meu protetor'}, 'Ruling: the cognate, plain; the Latin\'s agent noun; stays apart from amparo and auxílio. MS1932 protector in all three.', 'glossary'),
         opt('defensor', {'protector': 'defensor', 'p19': 'o meu defensor'}, 'Keeps a shield-bearer\'s sense (defending); MS1932 uses defensor for suscéptor — the two would cross.'),
         opt('escudo', {'protector': 'escudo', 'p19': 'o meu escudo'}, 'The Hebrew\'s image (magen), DM1962. Refused: the Latin has an agent noun, not a shield.', 'DM1962')]),
    dec('cornu', ['17:3c'], 'cornu salútis meæ', 'glossary',
        'The glossary\'s open row cornu → chifre names 17:3c among the places it must serve. The image is the Latin\'s (κέρας σωτηρίας), and the Benedictus has the same phrase (not quoted here from memory).',
        [opt('o chifre', {'cornu': 'o chifre'}, 'Ruling: the concrete image (rule 5), as the glossary row; corno is an insult in Brazil. Douay-Rheims "the horn of my salvation". Risk: the blind reader listed "chifre do altar" as unknown in Ps 117.', 'glossary'),
         opt('a força', {'cornu': 'a força'}, 'Explains the image (MS1932 "a minha poderosa salvação" does the same). Refused under D2: an image stays an image.', 'MS1932')]),
    dec('laudans', ['17:4'], 'Laudans invocábo Dóminum', 'order',
        'The participle stands first in the Latin, absolute (no object: the praise is God\'s, left unsaid).',
        [opt('Louvando, invocarei o Senhor', {'laudans': 'Louvando, invocarei o Senhor'}, 'Ruling: the Latin\'s order, the participle bare, as the Latin; laudáre → louvar (glossary, kept apart from confitéri → dar graças).'),
         opt('Invocarei o Senhor, louvando-o', {'laudans': 'Invocarei o Senhor, louvando-o'}, 'Matos Soares 1932\'s order; supplies an object the Latin does not have.', 'MS1932')]),
    dec('inferni', ['17:6'], 'Dolóres inférni', 'glossary',
        'inférnus → inferno is an open row held for Gustavo (D22): heard first as the hell of the damned. Here the parallel with death (dolóres mortis, 17:5; láquei mortis, 17:6) makes the sense the realm of the dead; but "dolóres inférni" is the Latin\'s phrase, and it is still the Latin\'s word.',
        [opt('inferno', {'inferni': 'inferno'}, 'Ruling: the Latin\'s word, as 6:6 and 9:18 have it; DRB "the sorrows of hell"; MS1932 "Dores de inferno".', 'glossary'),
         opt('dos infernos', {'inferni': 'dos infernos'}, 'The old plural for the abode of the dead (the glossary\'s option; the Creed\'s wording is from memory, unverified). Would read "As dores dos infernos".'),
         opt('abismo dos mortos', {'inferni': 'abismo dos mortos'}, 'A paraphrase for the realm of the dead; refused under D2.')]),
    dec('praeoccupare', ['17:6', '17:19'], 'præoccupavérunt me (17:6) · Prævenérunt me (17:19)', 'word',
        'Two Latin verbs, one Greek verb (προέφθασάν με in both verses: "came upon me first"). Lewis & Short præoccupo "to seize upon beforehand … to take, catch, detect"; prævenio "to come before, anticipate". By D15\'s test the Latin\'s variation is an elegance and one Portuguese verb may serve; the pair also ties the two ends of the rescue together (the snares of death came upon me — they came upon me in the day of my affliction).',
        [opt('surpreender, both', {'s6': 'surpreenderam-me', 's19': 'Surpreenderam-me'}, 'Ruling: Matos Soares 1932\'s verb in 17:6, carried to 17:19 (the Greek\'s one verb). The hostile "coming upon first" is heard; nothing added.', 'MS1932'),
         opt('kept apart: surpreender / anteciparam-se a', {'s6': 'surpreenderam-me', 's19': 'Anteciparam-se a mim'}, 'Keeps the Latin\'s two verbs apart; anteciparam-se a mim is stiff and is left to anticipáre (76:5).'),
         opt('apanhar / atacar', {'s6': 'apanharam-me', 's19': 'Atacaram-me'}, 'MS1932 at 17:19 (atacaram-me) — it interprets the coming-first as an attack.', 'MS1932')]),
    dec('conspectu', ['17:7b', '17:13', '17:23', '17:25'], 'in conspéctu ejus / meo / oculórum ejus', 'glossary',
        'in conspéctu four times in the first half: the glossary proposes à vista de (Ps 5, 9) and notes that it fails with verbs of motion, where Ps 118 used a vossa presença. Here two builds: the phrase qualifies a noun (clamor meus in conspéctu ejus, 7b; fulgóre in conspéctu ejus, 13) or is a predicate with a place (judícia ejus in conspéctu meo, 23; in conspéctu oculórum ejus, 25).',
        [opt('presença with a noun, vista as predicate', {'c7': 'na sua presença', 'c13': 'na sua presença', 'c23': 'à minha vista', 'c25': 'à vista dos seus olhos'}, 'Ruling: à vista de where it is a predicate (the glossary proposal, and "à vista dos seus olhos" keeps oculórum), a noun phrase where it hangs on a noun and a verb of motion follows (7b entrou), as 118:168–170 did. The noun of seeing kept in the two places where it reads, presence in the other two.'),
         opt('à vista everywhere', {'c7': 'à sua vista', 'c13': 'à sua vista', 'c23': 'à minha vista', 'c25': 'à vista dos seus olhos'}, 'One rendering for the phrase; 7b "o meu clamor, à sua vista, entrou" and 13 "Ao fulgor à sua vista" are stiff.', 'glossary'),
         opt('diante de everywhere', {'c7': 'diante dele', 'c13': 'diante dele', 'c23': 'diante de mim', 'c25': 'diante dos seus olhos'}, 'Douay-Rheims "before him … in my sight … before his eyes"; MS1932 "diante de mim". Plain; loses the noun.', 'DRB')]),
    dec('commota', ['17:8'], 'Commóta est … conturbáta sunt, et commóta sunt', 'grammar',
        'Three passive perfects of motion (ἐσαλεύθη … ἐταράχθησαν καὶ ἐσαλεύθησαν). The Latin repeats commovéri, and the Portuguese repeats one verb for it. The voice: a passive with middle sense, as elsewhere in the glossary rendered by the pronominal form (8:2b se elevou; 7:7a exaltai-vos). The earth is not said to be shaken BY anyone; it shook.',
        [opt('pronominal: se abalou … se perturbaram e se abalaram', {'m8a': 'se abalou', 'm8b': 'se perturbaram', 'm8c': 'se abalaram'}, 'Ruling: the middle sense, which is what the Portuguese pronominal says; one verb twice for commovéri; conturbáre → perturbar (glossary, tried on bones, soul, eye in Ps 6). MS1932 "abalaram-se".'),
         opt('passive: foi abalada … foram perturbados e foram abalados', {'m8a': 'foi abalada', 'm8b': 'foram perturbados', 'm8c': 'foram abalados'}, 'The voice to the letter; heavier (foram … foram), and it suggests an agent.'),
         opt('estremeceram (for conturbáta)', {'m8a': 'se abalou', 'm8b': 'estremeceram', 'm8c': 'se abalaram'}, 'MS1932 "estremeceram" for the foundations; but estremecer is taken by contrémuit in the first colon.', 'MS1932')]),
    dec('fumus', ['17:9'], 'fumus', 'word', 'The plain word for smoke.',
        [opt('fumaça', {'fumus': 'fumaça'}, 'Ruling: the Brazilian word (DM1962 "Uma fumaça").', 'DM1962'),
         opt('fumo', {'fumus': 'fumo'}, 'MS1932; in Brazil fumo is first tobacco.', 'MS1932')]),
    dec('carbones', ['17:9', '17:13', '17:14'], 'carbónes succénsi sunt · carbónes ignis (×2)', 'word',
        'Three times: coals kindled from the fire (9), and the refrain-like "grando et carbónes ignis" (13, 14 — the Latin repeats it word for word, so the Portuguese does).',
        [opt('carvões', {'carb9': 'carvões', 'carb13': 'carvões', 'carb14': 'carvões'}, 'Ruling: MS1932 in all three ("carvões de fogo"); carvões that are kindled (9) and then carvões OF fire (13, 14) keep the Latin\'s sequence — the coal set alight.', 'MS1932'),
         opt('brasas', {'carb9': 'brasas', 'carb13': 'brasas', 'carb14': 'brasas'}, 'DM1962 "brasas de fogo"; plainer, but "brasas foram acesas" says the fire twice.', 'DM1962')]),
    dec('caligo', ['17:10'], 'calígo', 'word',
        'calígo (γνόφος): "thick air, mist, fog; darkness" (L&S). ténebræ → trevas comes two verses later, so calígo needs its own word.',
        [opt('uma névoa escura', {'caligo': 'uma névoa escura'}, 'Ruling: the mist and the dark in two plain words; MS1932 "uma nuvem obscura" (nuvem is núbes\'s, 17:12–13).'),
         opt('a escuridão', {'caligo': 'a escuridão'}, 'One plain word; close to trevas (17:12), which the Latin keeps apart.'),
         opt('a caligem', {'caligo': 'a caligem'}, 'The cognate; literary, needs a footnote.')]),
    dec('posuit', ['17:12'], 'pósuit ténebras latíbulum suum', 'word',
        'pónere with a double accusative, "made the darkness his hiding-place". latíbulum: "a hiding-place, lurking-place" (L&S), ἀποκρυφή. The psalm has the same build twice more (17:33 pósuit immaculátam viam meam; 17:35 posuísti ut arcum ǽreum brácchia mea), so the verb chosen here should serve all three.',
        [opt('fez das trevas o seu esconderijo', {'posuit': 'fez das trevas o seu esconderijo'}, 'Ruling: the Portuguese idiom for pónere + two accusatives (MS1932 "Fez das trevas o lugar do seu retiro"); esconderijo is the plain word for latíbulum.', 'MS1932'),
         opt('pôs as trevas por seu esconderijo', {'posuit': 'pôs as trevas por seu esconderijo'}, 'The Latin\'s verb; the predicative "por" is bookish.'),
         opt('fez das trevas o seu abrigo', {'posuit': 'fez das trevas o seu abrigo'}, 'abrigo loses the hiding (and is near refúgio).')]),
    dec('vocem', ['17:14'], 'dedit vocem suam', 'word',
        'dare vocem is an idiom: to utter, to sound (the Greek ἔδωκεν φωνήν is the same). Portuguese "deu a sua voz" is not said. The phrase returns in 45:7 (dedit vocem suam, mota est terra) and 67:34 (dabit voci suæ vocem virtútis).',
        [opt('fez ouvir a sua voz', {'vocem': 'fez ouvir a sua voz'}, 'Ruling: the idiom (MS1932, DM1962); the light verb yields as it does elsewhere in the glossary (laudem dícere → dar louvor). Proposed as a formula for 45:7.', 'MS1932'),
         opt('deu a sua voz', {'vocem': 'deu a sua voz'}, 'The Latin\'s verb; a calque, not said in Portuguese.'),
         opt('soltou a sua voz', {'vocem': 'soltou a sua voz'}, 'Idiomatic (soltar a voz) and short; changes the verb as much as option 0.')]),
    dec('dissipavit', ['17:15'], 'dissipávit eos', 'glossary',
        'dissipáre → dissipar is an open row that lists 17:15; ἐσκόρπισεν "scattered". Here the object is people (eos, the enemies).',
        [opt('dissipou', {'dissipavit': 'dissipou'}, 'Ruling: the row (one verb for nine verses); "dissipar a multidão" is current Portuguese for scattering people.', 'glossary'),
         opt('dispersou', {'dissipavit': 'dispersou'}, 'The plainest word; but it is wanted for dispérgere (58:12 Dispérge illos).'),
         opt('desbaratou', {'dissipavit': 'desbaratou'}, 'MS1932: routed; a military sense the Latin does not name.', 'MS1932')]),
    dec('orbis', ['17:16a'], 'fundaménta orbis terrárum', 'glossary',
        'orbis terræ → o orbe da terra is an open row (Ps 9:8b); the blind reader did not know orbe. Here the plural terrárum.',
        [opt('do orbe da terra', {'orbis': 'do orbe da terra'}, 'Ruling: the row, so that the phrase is one phrase through the psalter (the plural terrárum is not heard, as in DRB "the world").', 'glossary'),
         opt('do mundo', {'orbis': 'do mundo'}, 'Douay-Rheims "the foundations of the world"; plain; loses the orb.', 'DRB'),
         opt('da terra', {'orbis': 'da terra'}, 'MS1932 "os fundamentos da terra"; drops orbis.', 'MS1932')]),
    dec('increpatio', ['17:16b'], 'Ab increpatióne tua', 'glossary',
        'The noun of increpáre → repreender (working; shared since D21 with árguere). ἀπὸ ἐπιτιμήσεως: the rebuke at which the sea-bed is laid bare. The same phrase opens 75:7 and 103:7 (Ab increpatióne tua fúgient) and closes 79:17. "ab" is the cause (at, because of), as Douay-Rheims "At thy rebuke".',
        [opt('À vossa repreensão', {'increpatio': 'À vossa repreensão'}, 'Ruling: the glossary\'s family; "À" gives the cause as DRB\'s "At" does and echoes 17:13 "Ao fulgor".', 'glossary'),
         opt('Pela vossa repreensão', {'increpatio': 'Pela vossa repreensão'}, 'The cause spelled out; heavier, and "pela … pelo" in the second colon.'),
         opt('Às vossas ameaças', {'increpatio': 'Às vossas ameaças'}, 'MS1932 "às tuas ameaças"; a threat is not a rebuke.', 'MS1932')]),
    dec('assumpsit', ['17:17'], 'accépit me: et assúmpsit me', 'word',
        'Two verbs of taking (ἔλαβεν … προσελάβετο, "took … took to himself"). accípere → tomar; assúmere wants a second verb with the sense of taking up to oneself.',
        [opt('recolheu', {'assumpsit': 'recolheu'}, 'Ruling: "took up, took in" — a second verb of taking that says the taking-to-oneself; plain.'),
         opt('tomou consigo', {'assumpsit': 'tomou consigo'}, 'The Greek\'s προσ- spelled out; repeats tomar.'),
         opt('tirou', {'assumpsit': 'tirou'}, 'MS1932 "tirou-me da inundação": the direction only, not the taking-to-himself.', 'MS1932')]),
    dec('super', ['17:18'], 'confortáti sunt super me', 'word',
        'ἐστερεώθησαν ὑπὲρ ἐμέ: "they were made strong beyond me" — stronger than I. confortári → fortalecer-se is the open row from 9:20.',
        [opt('acima de mim', {'super': 'acima de mim'}, 'Ruling: the Latin\'s preposition (super = above, beyond); open between "more than I" and "over me" as the Latin is.'),
         opt('mais do que eu', {'super': 'mais do que eu'}, 'The sense stated (DRB "too strong for me"; MS1932 "mais poderosos do que eu"); closes the openness.', 'DRB'),
         opt('contra mim', {'super': 'contra mim'}, 'A hostile "over me"; one of the two readings only.')]),
    dec('eduxit', ['17:20'], 'edúxit me in latitúdinem', 'word',
        'edúcere: "lead out, bring out"; latitúdo → amplidão is the glossary row, which names this verse.',
        [opt('fez sair', {'eduxit': 'fez sair'}, 'Ruling: keeps the e- (out) and the leading; "E me fez sair para a amplidão".'),
         opt('levou', {'eduxit': 'levou'}, '"E me levou para a amplidão": plainer; the out is lost.'),
         opt('tirou', {'eduxit': 'tirou'}, 'MS1932 "Retirou-me"; "tirar para" is not idiomatic.', 'MS1932')]),
    dec('voluit', ['17:20'], 'quóniam vóluit me', 'glossary',
        'velle → querer (glossary). "vóluit me" with a person as object: he wanted me, he took pleasure in me (ἠθέλησέν με).',
        [opt('me quis', {'voluit': 'me quis'}, 'Ruling: the glossary verb; "porque me quis" is heard in Brazil as "because he wanted me / loved me", which is the Latin\'s range.', 'glossary'),
         opt('se agradou de mim', {'voluit': 'se agradou de mim'}, 'Douay-Rheims "because he was well pleased with me": the sense, another verb.', 'DRB'),
         opt('me amava', {'voluit': 'me amava'}, 'MS1932 "porque me amava": dilígere\'s verb (17:2 Díligam → amarei).', 'MS1932')]),
    dec('retribuet', ['17:21', '17:25'], 'retríbuet mihi … retríbuet mihi (17:21) · retríbuet mihi (17:25)', 'word',
        'The Latin says retríbuet three times, and 17:25 repeats the first colon of 17:21 word for word: the stanza on the psalmist\'s innocence is framed by it. Matos Soares 1932 varies (retribuirá … recompensará).',
        [opt('me retribuirá, three times', {'r21a': 'me retribuirá', 'r21b': 'me retribuirá', 'r25': 'me retribuirá'}, 'Ruling: one verb three times (rule 2; glossary retribúere → retribuir outside the vós imperative); 17:21a = 17:25a word for word.', 'glossary'),
         opt('retribuirá … recompensará', {'r21a': 'me retribuirá', 'r21b': 'me recompensará', 'r25': 'me retribuirá'}, 'Matos Soares 1932\'s variation; refused — it drops a repetition the Latin has.', 'MS1932')]),
    dec('impie', ['17:22'], 'nec ímpie gessi a Deo meo', 'ambiguity',
        '"ímpie gérere a Deo" calques ἠσέβησα ἀπὸ τοῦ θεοῦ μου: to act impiously away from God, i.e. to depart from him in impiety. The preposition is one of separation; Douay-Rheims and Matos Soares both render it "against".',
        [opt('contra o meu Deus', {'impie': 'contra o meu Deus'}, 'Ruling: both Vulgate-family versions ("have not done wickedly against my God"; "não procedi impiamente contra o meu Deus"); plain. Cost: "contra" is not separation. "agi como ímpio" for ímpie gessi: the adverb impiamente is heavy and ímpio is the glossary\'s word.', 'DRB'),
         opt('longe do meu Deus', {'impie': 'longe do meu Deus'}, 'Keeps the separation; heard as "while far from God", which the Latin does not say either.'),
         opt('apartando-me do meu Deus', {'impie': 'apartando-me do meu Deus'}, 'The sense of the calque spelled out; adds a verb.')]),
    dec('justitias', ['17:23'], 'justítias ejus', 'glossary',
        'The Latin\'s plural justítiæ stands for δικαιώματα here (the Greek word that is justificatiónes → preceitos in Ps 118). The glossary row justítiæ (plural) asks that these places decide locally, "preceitos may be wanted". But the Latin chose justítia, and this stanza is built on it: justítiam meam (21) — justítias ejus (23) — justítiam meam (25).',
        [opt('as suas justiças', {'justitias': 'as suas justiças'}, 'Ruling: the Latin\'s word, keeping the stanza\'s echo (my justice / his justices); 10:8 has "as justiças" and it was never heard as the courts. Douay-Rheims "his justices".', 'DRB'),
         opt('os seus preceitos', {'justitias': 'os seus preceitos'}, 'The Greek\'s sense (δικαιώματα) and MS1932\'s word; loses the echo and renders the Greek, not the Latin.', 'MS1932')]),
    dec('cumeo', ['17:24'], 'immaculátus cum eo', 'word',
        'cum eo (μετ᾿ αὐτοῦ): "with him". The next stanza is built on cum (17:26–27 Cum sancto sanctus eris), so the preposition should stay.',
        [opt('com ele', {'cumeo': 'com ele'}, 'Ruling: the Latin\'s preposition, which 17:26–27 will repeat four times.'),
         opt('diante dele', {'cumeo': 'diante dele'}, 'MS1932 "sem mácula diante dele": in conspéctu\'s phrase.', 'MS1932')]),
    dec('observabo', ['17:24'], 'observábo me ab iniquitáte mea', 'word',
        'observáre is a second verb of keeping two verses after custodívi (17:22); the Greek has one verb in both (ἐφύλαξα … φυλάξομαι). Reflexive with ab: to keep oneself from.',
        [opt('me guardarei', {'observabo': 'guardarei'}, 'Ruling: the Greek\'s one verb (D15\'s test) and the Portuguese idiom "guardar-se de"; MS1932 "guardar-me-ei da minha iniquidade".', 'MS1932'),
         opt('me acautelarei', {'observabo': 'acautelarei'}, 'Keeps the verbs apart; "acautelar-se de" is to beware of — close, bookish.'),
         opt('me observarei', {'observabo': 'observarei'}, 'The cognate; "observar-se" is to watch oneself, not to keep away from.')]),
]

choices = {
    '17:2': 'The psalm begins at 17:2 (17:1 is the titulus; D7). The inline marker (3a) is not reproduced. dilígere → amar (glossary); "Eu vos amarei" supplies the subject so that the verse does not open on a clitic. refúgium → refúgio, liberátor → libertador. The copula "é" is supplied in the second colon (D2), as DRB does.',
    '17:3b': 'speráre in → esperar em (glossary). "Deus meus" is not a vocative: the second colon speaks of him in the third person, so the copula is supplied (DRB, MS1932).',
    '17:3c': 'suscéptor → amparo (settled, D19). The four agent nouns of 17:2–3 come out as two agents (libertador, protetor) and two abstracts (auxílio, amparo) — see decision adjutor.',
    '17:4': 'invocáre → invocar; salvus ero → serei salvo.',
    '17:5': 'circumdáre → cercar; conturbáre → perturbar (glossary). Articles supplied (as dores da morte, as torrentes da iniquidade) so that 17:5 and 17:6 match: dolóres mortis / dolóres inférni / láquei mortis. The Greek ὠδῖνες are birth-pangs; the Latin dolóres is pain, and the Portuguese follows the Latin.',
    '17:6': 'láqueus → laço (glossary). The subject stands after the verb as in the Latin (præoccupavérunt me láquei mortis).',
    '17:7a': 'tribulátio → tribulação, clamáre → clamar (glossary). Natural order in the second colon.',
    '17:7b': 'exaudíre → escutar (D3). "ele" supplied so that "do seu templo santo" is not heard as the voice\'s origin. templum sanctum → templo santo (5:8b).',
    '17:8': 'irásci → irar-se (glossary); eis → contra eles (MS1932). "ele" supplied: the Latin leaves the subject in the verb (the Greek adds ὁ θεός).',
    '17:9': 'a fácie ejus → da sua face (glossary: a fácie → da face de); exardéscere → inflamar-se (117:12). "ab eo" → "por ele", open between God and the fire as the Latin is (DRB "by it").',
    '17:10': 'The second colon has no verb in the Latin and none is supplied.',
    '17:11': 'volávit, volávit: the repetition kept. pennæ → asas (open row; collides with alæ, which this psalm does not have). Chérubim lowercase, as ángelus → anjo.',
    '17:12': 'in circúitu → ao redor (glossary); tabernáculum → tenda (open). "tenebrósa" echoes "ténebras" in the Latin, and "tenebrosa" echoes "trevas" only faintly; kept.',
    '17:13': 'præ with the ablative is cause (Douay-Rheims "At the brightness"): "Ao fulgor" keeps it without spelling it out. fulgor → fulgor (the family of fúlgura in 17:15, which Portuguese cannot keep: relâmpagos). grando → granizo (Brazilian; saraiva is European). The second colon is verbless, as the Latin.',
    '17:14': 'The second colon repeats 17:13\'s word for word, as the Latin does.',
    '17:15': 'míttere → enviar, here and in 17:17 (Misit de summo), one verb twice. sagítta → seta (glossary). "et dissipávit eos … et conturbávit eos": the parallel endings kept (os dissipou … os perturbou).',
    '17:16a': 'reveláre → desvendar (the glossary\'s verb for reveláre, 118:18); the passive kept. The colon ends on ":" as the Latin, which runs on into 17:16b.',
    '17:16b': 'The address turns to God in mid-description (tua … tuæ); vós. inspirátio (ἐμπνεύσεως) → sopro; spíritus → espírito (kept: the breath of the spirit of your wrath, the Latin\'s two nouns).',
    '17:17': 'Misit with no object, as the Latin and DRB ("He sent from on high"); MS1932 supplies "a sua mão". de aquis multis → de muitas águas, no article, as the phrase is usually said.',
    '17:18': 'erípere de + me → arrancar (glossary: with a source named, arrancar is untouched). odérunt is a perfect with present sense (odi): "que me odeiam". confortári → fortalecer-se (open row, 9:20).',
    '17:19': 'afflíctio → aflição. fíeri → fazer-se (open row): "se fez o meu protetor".',
    '17:20': 'salvum fácere → salvar (glossary).',
    '17:21': 'púritas → pureza. The Latin\'s final ":" (the sentence runs into 17:22) becomes a full stop in the draft\'s punctuation, since 17:22 opens with its own "Porque".',
    '17:22': 'custodíre → guardar (glossary); via → caminho.',
    '17:23': 'judícia → juízos (D15); repéllere a → afastar de (glossary). The order of the second colon made natural (e não afastei de mim as suas justiças).',
    '17:24': 'immaculátus → imaculado (open row).',
    '17:25': 'The first colon is 17:21\'s, word for word (decision retribuet). Stage one ends here: 17:21 and 17:25 frame the psalmist\'s account of his innocence, and 17:26 turns to address God (Cum sancto sanctus eris) — see audit.',
}

audit = [
    {'step': 'source', 'note': "Latin = DO Psalm17.txt: 54 prayed verses 17:2–17:51 with DO's split ids (17:3b, 17:3c, 17:7a, 17:7b, 17:16a, 17:16b, 17:36a, 17:36b; there is no 17:3a — the first colon of Vulgate verse 3 is inside 17:2, after the inline marker (3a), which is not reproduced). 17:1 is the titulus (D7). Douay-Rheims checked against the Latin at both ends (Bolls chapter 18): 17:2 'I will love thee, O Lord, my strength' = Díligam te, Dómine, fortitúdo mea; 17:51 'Giving great deliverance to his king, and shewing mercy to David his anointed: and to his seed for ever' = Magníficans salútes Regis ejus … usque in sǽculum. The Diurnal Monástico 1962 in the dossier breaks off at Hebrew v. 25. Worked in two stages in one folder, as Ps 9 was: 17:2–17:25 first, then 17:26–17:51 appended. While partial, prayed.json and literal.json carry 'range'; ps017/partial.py (copied from ps009/partial.py) stands in for checks.py, ps017/part.py (from ps009/part.py) builds the critics' sub-folder for stage two. The parallel text 2 Samuel (2 Kings) 22 is not used: its Vulgate is Jerome's version from the Hebrew, not a witness of the Gallican Latin."},
    {'step': 'draft', 'note': "Stage one (17:2–17:25), draft 1, from consult/parallels/ps017.md (LXX Rahlfs, Douay-Rheims, Matos Soares 1932 text layer, DM1962 for diction; DO's Portuguese not used, D12). Why the stage ends at 17:25: it is the 27th of the 54 prayed verses, and it closes the unit 17:21–25, framed by the same colon (Et retríbuet mihi Dóminus secúndum justítiam meam) — the psalmist's account of his innocence; 17:26 opens a new movement addressed to God (Cum sancto sanctus eris … Quóniam tu …). Lewis & Short read for præoccupo, latíbulum, firmaméntum. Repeats found with ps005/grep_latin.py: firmaméntum 9 lines (sky in 18:2 and 150:1, support here, 24:14, 70:3); protéctor 19 lines (three in this psalm); 'Ab increpatióne tua' also 75:7, 103:7; 'fortitúdo mea' 30:4, 42:2, 117:14. Glossary applied: dilígere → amar, fortitúdo → força, refúgium, adjútor → auxílio, suscéptor → amparo (D19), speráre in, laudáre → louvar, invocáre, circumdáre → cercar, conturbáre → perturbar, láqueus → laço, tribulátio, clamáre, exaudíre → escutar (D3), irásci, exardéscere → inflamar-se, a fácie → da face, pennæ → asas, in circúitu, tabernáculum → tenda, sagítta → seta, dissipáre → dissipar, orbis terræ → orbe da terra, increpáre (noun) → repreensão, erípere de → arrancar, confortári → fortalecer-se, latitúdo → amplidão, salvum fácere, velle → querer, retribúere → retribuir, custodíre → guardar, judícia → juízos (D15), repéllere a → afastar, immaculátus → imaculado, inférnus → inferno (held for Gustavo, D22). Places where the Latin follows the Greek and the draft follows the Latin: 17:3c 'O meu protetor' (not the Hebrew's shield), 17:6 inferno as dolóres (not cords), 17:17 muitas águas, 17:18 'acima de mim', 17:20 'porque me quis', 17:23 'as suas justiças'. Every vós imperative checked for rule 3: none in stage one (the address to God in 17:16b is by possessives only)."},
    {'step': 'checks', 'note': "Stage one, draft 1, through ps017/partial.py (checks.py's own code on 17:2–17:25): hard pass (ids and marks). Mended before the critics: 17:18 flex on the proparoxytone 'fortíssimos' → MS1932's order 'dos meus fortíssimos inimigos'; 17:10 'debaixo dos' → 'sob os' (+5 → +2). Soft flags accepted: 17:8 second colon +4 (three verbs and 'ele' supplied; the Latin's own colon is 26 syllables); 17:7a first colon −3, 17:12 flex −4, 17:16b first colon −3, 17:20 second colon −5, 17:25 second colon −5 (Latin polysyllables: tribulatióne, tabernáculum, increpatióne, quóniam vóluit, oculórum); 17:16a second colon +3 (orbe da terra). Rhymes accepted as the Latin's own: 17:15 dissipou / perturbou (dissipávit eos / conturbávit eos), 17:13 / 17:14 the same final colon (grando et carbónes ignis twice). Every Portuguese colon ends oxytone or paroxytone."},
]

prayed = {'psalm': 17, 'tier': 3, 'version': 1, 'address': 'vós', 'status': 'draft', 'range': '17:2–17:25',
          'verses': verses, 'decisions': decisions, 'choices': choices, 'audit': audit}
(here / 'prayed.json').write_text(json.dumps(prayed, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print('prayed.json v1:', len(verses), 'verses,', len(decisions), 'decisions')
