/* AUTO-GENERATED by scripts/build-starter.py — do not edit. */
import type { CatalogEntry } from '../manifestTypes'

export const STARTER_ITEMS: Record<string, CatalogEntry> = {
  'prayer/sign-of-cross': {
    kind: 'prayer',
    hash: 'e47026ff40825cbc5bd336cc21d1684c91c279edffe1e2a3eb43672f7b88fb0f',
    size: 364,
  },
  'prayer/our-father': {
    kind: 'prayer',
    hash: '31bd9cc6e79f117d5cf1537db4188596d0729df83d47261ffb6bbde6818eb18e',
    size: 1138,
  },
  'prayer/hail-mary': {
    kind: 'prayer',
    hash: '1b6efdabada803b9389d88a588aeeca8db1d77ef87419b497c5af62a575690f5',
    size: 822,
  },
  'prayer/glory-be': {
    kind: 'prayer',
    hash: '63ad70c78be13ab131a2694d045d863514c20472df1571325aad70cf0679d427',
    size: 575,
  },
  'prayer/apostles-creed': {
    kind: 'prayer',
    hash: 'b5c41843118cf30c78912d55906d24030db412a9a391828f126e15a205e1ea8f',
    size: 2018,
  },
  'prayer/act-of-contrition': {
    kind: 'prayer',
    hash: '0cecb492dd71b0382d05973f757e73996fc4f112cce9e6c0a27c3fb1f056be8a',
    size: 1090,
  },
  'prayer/anima-christi': {
    kind: 'prayer',
    hash: 'fad45850afc6175747a71161ab096bc4f6fb5d5b929b8781c7a6379849398fcd',
    size: 1401,
  },
  'prayer/memorare': {
    kind: 'prayer',
    hash: '7e9b17c1a98020d4316e4b621afd838b16d2fdaaa5c960e6af5887c3e749e22b',
    size: 1546,
  },
  'prayer/angele-dei': {
    kind: 'prayer',
    hash: 'c5c6b5b2fd6c27da030874fb1586a0b858282dbf91c79b81e2a69f81d11d661c',
    size: 568,
  },
  'prayer/fatima-prayer': {
    kind: 'prayer',
    hash: 'a29034cac748919c9984bbd7380760c07727da0a738a67b49e082eb8fdc5ff2f',
    size: 648,
  },
  'prayer/hail-holy-queen': {
    kind: 'prayer',
    hash: 'e71556ec350a516903fc949411c168a55e3fec7510fcf20775429044ec01b18d',
    size: 1365,
  },
} as const

export const STARTER_BODIES: Record<string, unknown> = {
  e47026ff40825cbc5bd336cc21d1684c91c279edffe1e2a3eb43672f7b88fb0f: {
    title: {
      'en-US': 'Sign of the Cross',
      'pt-BR': 'Sinal da Cruz',
      la: 'Signum Crucis',
    },
    body: [
      {
        type: 'prayer',
        inline: {
          'en-US': 'In the name of the Father, and of the Son, and of the Holy Spirit. Amen.',
          'pt-BR': 'Em nome do Pai, e do Filho, e do Espírito Santo. Amém.',
          la: 'In nómine Patris, et Fílii, et Spíritus Sancti. Amen.',
        },
      },
    ],
    id: 'prayer/sign-of-cross',
  },
  '31bd9cc6e79f117d5cf1537db4188596d0729df83d47261ffb6bbde6818eb18e': {
    title: {
      'en-US': 'Our Father',
      'pt-BR': 'Pai Nosso',
      la: 'Pater Noster',
    },
    body: [
      {
        type: 'prayer',
        inline: {
          'en-US':
            'Our Father, who art in heaven,\nhallowed be thy name.\nThy kingdom come.\nThy will be done on earth, as it is in heaven.\nGive us this day our daily bread,\nand forgive us our trespasses,\nas we forgive those who trespass against us.\nAnd lead us not into temptation,\nbut deliver us from evil.\nAmen.',
          'pt-BR':
            'Pai nosso, que estais nos céus,\nsantificado seja o vosso nome.\nVenha a nós o vosso reino.\nSeja feita a vossa vontade, assim na terra como no céu.\nO pão nosso de cada dia nos dai hoje,\nperdoai as nossas ofensas,\nassim como nós perdoamos a quem nos tem ofendido.\nE não nos deixeis cair em tentação,\nmas livrai-nos do mal.\nAmém.',
          la: 'Pater noster, qui es in cælis,\nsanctificétur nomen tuum.\nAdvéniat regnum tuum.\nFiat volúntas tua, sicut in cælo et in terra.\nPanem nostrum quotidiánum da nobis hódie,\net dimítte nobis débita nostra,\nsicut et nos dimíttimus debitóribus nostris.\nEt ne nos indúcas in tentatiónem,\nsed líbera nos a malo.\nAmen.',
        },
      },
    ],
    id: 'prayer/our-father',
  },
  '1b6efdabada803b9389d88a588aeeca8db1d77ef87419b497c5af62a575690f5': {
    title: {
      'en-US': 'Hail Mary',
      'pt-BR': 'Ave Maria',
      la: 'Ave Maria',
    },
    body: [
      {
        type: 'prayer',
        inline: {
          'en-US':
            'Hail Mary, full of grace, the Lord is with thee.\nBlessed art thou amongst women,\nand blessed is the fruit of thy womb, Jesus.\nHoly Mary, Mother of God,\npray for us sinners,\nnow and at the hour of our death.\nAmen.',
          'pt-BR':
            'Ave Maria, cheia de graça, o Senhor é convosco.\nBendita sois vós entre as mulheres,\ne bendito é o fruto do vosso ventre, Jesus.\nSanta Maria, Mãe de Deus,\nrogai por nós, pecadores,\nagora e na hora da nossa morte.\nAmém.',
          la: 'Ave María, grátia plena, Dóminus tecum.\nBenedícta tu in muliéribus,\net benedíctus fructus ventris tui, Iesus.\nSancta María, Mater Dei,\nora pro nobis peccatóribus,\nnunc et in hora mortis nostræ.\nAmen.',
        },
      },
    ],
    id: 'prayer/hail-mary',
  },
  '63ad70c78be13ab131a2694d045d863514c20472df1571325aad70cf0679d427': {
    title: {
      'en-US': 'Glory Be',
      'pt-BR': 'Glória ao Pai',
      la: 'Gloria Patri',
    },
    body: [
      {
        type: 'prayer',
        inline: {
          'en-US':
            'Glory be to the Father, and to the Son, and to the Holy Spirit.\nAs it was in the beginning, is now, and ever shall be,\nworld without end.\nAmen.',
          'pt-BR':
            'Glória ao Pai, e ao Filho, e ao Espírito Santo.\nAssim como era no princípio, agora e sempre, e pelos séculos dos séculos.\nAmém.',
          la: 'Glória Patri, et Fílio, et Spirítui Sancto.\nSicut erat in princípio, et nunc, et semper,\net in sǽcula sæculórum.\nAmen.',
        },
      },
    ],
    id: 'prayer/glory-be',
  },
  b5c41843118cf30c78912d55906d24030db412a9a391828f126e15a205e1ea8f: {
    title: {
      'en-US': "Apostles' Creed",
      'pt-BR': 'Credo dos Apóstolos',
      la: 'Symbolum Apostolorum',
    },
    body: [
      {
        type: 'prayer',
        inline: {
          'en-US':
            'I believe in God, the Father almighty, Creator of heaven and earth,\nand in Jesus Christ, his only Son, our Lord,\nwho was conceived by the Holy Spirit, born of the Virgin Mary,\nsuffered under Pontius Pilate, was crucified, died and was buried;\nhe descended into hell; on the third day he rose again from the dead;\nhe ascended into heaven, and is seated at the right hand of God the Father almighty;\nfrom there he shall come to judge the living and the dead.\nI believe in the Holy Spirit,\nthe holy catholic Church, the communion of saints,\nthe forgiveness of sins,\nthe resurrection of the body,\nand life everlasting.\nAmen.',
          'pt-BR':
            'Creio em Deus Pai todo-poderoso, Criador do céu e da terra;\ne em Jesus Cristo, seu único Filho, nosso Senhor,\nque foi concebido pelo poder do Espírito Santo, nasceu da Virgem Maria;\npadeceu sob Pôncio Pilatos, foi crucificado, morto e sepultado;\ndesceu à mansão dos mortos; ressuscitou ao terceiro dia;\nsubiu aos céus; está sentado à direita de Deus Pai todo-poderoso,\nde onde há de vir a julgar os vivos e os mortos.\nCreio no Espírito Santo,\nna Santa Igreja Católica, na comunhão dos santos,\nna remissão dos pecados,\nna ressurreição da carne,\nna vida eterna.\nAmém.',
          la: 'Credo in Deum Patrem omnipoténtem, Creatórem cæli et terræ.\nEt in Iesum Christum, Fílium eius únicum, Dóminum nostrum,\nqui concéptus est de Spíritu Sancto, natus ex María Vírgine,\npassus sub Póntio Piláto, crucifíxus, mórtuus, et sepúltus,\ndescéndit ad ínferos, tértia die resurréxit a mórtuis,\nascéndit ad cælos, sedet ad déxteram Dei Patris omnipoténtis,\ninde ventúrus est iudicáre vivos et mórtuos.\nCredo in Spíritum Sanctum,\nsanctam Ecclésiam cathólicam, sanctórum communiónem,\nremissiónem peccatórum,\ncarnis resurrectiónem,\nvitam ætérnam.\nAmen.',
        },
      },
    ],
    id: 'prayer/apostles-creed',
  },
  '0cecb492dd71b0382d05973f757e73996fc4f112cce9e6c0a27c3fb1f056be8a': {
    title: {
      'en-US': 'Act of Contrition',
      'pt-BR': 'Ato de Contrição',
      la: 'Actus Contritionis',
    },
    body: [
      {
        type: 'prayer',
        inline: {
          'en-US':
            'O my God, I am heartily sorry for having offended Thee,\nand I detest all my sins, because of Thy just punishments,\nbut most of all because they offend Thee, my God,\nWho art all-good and deserving of all my love.\nI firmly resolve, with the help of Thy grace,\nto sin no more and to avoid the near occasions of sin.\nAmen.',
          'pt-BR':
            'Meu Deus, pesa-me muito ter-Vos ofendido,\nporque sois infinitamente bom e o pecado Vos desagrada.\nProponho firmemente, com o auxílio da Vossa graça,\nnão Vos ofender mais e evitar as ocasiões de pecado.\nAmém.',
          la: 'Deus meus, ex toto corde pænitet me omnium meorum peccatorum,\næque detestor, quia peccando, non solum pœnas a Te iuste statutas promeritus sum,\nsed præsertim quia offendi Te, summum bonum, ac dignum qui super omnia diligaris.\nIdeo firmiter propono, adiuvante Tua gratia, de cetero me non peccaturum\npeccandique occasiones proximas fugiturum.\nAmen.',
        },
      },
    ],
    id: 'prayer/act-of-contrition',
  },
  fad45850afc6175747a71161ab096bc4f6fb5d5b929b8781c7a6379849398fcd: {
    title: {
      'en-US': 'Anima Christi',
      'pt-BR': 'Alma de Cristo',
      la: 'Anima Christi',
    },
    body: [
      {
        type: 'prayer',
        inline: {
          'en-US':
            'Soul of Christ, sanctify me.\nBody of Christ, save me.\nBlood of Christ, inebriate me.\nWater from the side of Christ, wash me.\nPassion of Christ, strengthen me.\nO good Jesus, hear me.\nWithin Thy wounds hide me.\nPermit me not to be separated from Thee.\nFrom the malignant enemy defend me.\nIn the hour of my death call me,\nand bid me come to Thee,\nthat with Thy saints I may praise Thee\nforever and ever. Amen.',
          'pt-BR':
            'Alma de Cristo, santificai-me.\nCorpo de Cristo, salvai-me.\nSangue de Cristo, embriagai-me.\nÁgua do lado de Cristo, lavai-me.\nPaixão de Cristo, confortai-me.\nÓ bom Jesus, escutai-me.\nNas Vossas chagas escondei-me.\nNão permitais que me separe de Vós.\nDo maligno defendei-me.\nNa hora da minha morte chamai-me\ne mandai-me vir a Vós,\npara que com os Vossos santos Vos louve\npelos séculos dos séculos. Amém.',
          la: 'Anima Christi, sanctifica me.\nCorpus Christi, salva me.\nSanguis Christi, inebria me.\nAqua lateris Christi, lava me.\nPassio Christi, conforta me.\nO bone Iesu, exaudi me.\nIntra tua vulnera absconde me.\nNe permittas me separari a te.\nAb hoste maligno defende me.\nIn hora mortis meae voca me.\nEt iube me venire ad te.\nUt cum sanctis tuis laudem te\nin saecula saeculorum. Amen.',
        },
      },
    ],
    id: 'prayer/anima-christi',
  },
  '7e9b17c1a98020d4316e4b621afd838b16d2fdaaa5c960e6af5887c3e749e22b': {
    title: {
      'en-US': 'The Memorare',
      'pt-BR': 'Memorare (Lembrai-vos)',
      la: 'Memorare',
    },
    body: [
      {
        type: 'prayer',
        inline: {
          'en-US':
            'Remember, O most gracious Virgin Mary,\nthat never was it known\nthat anyone who fled to thy protection,\nimplored thy help, or sought thy intercession,\nwas left unaided.\n\nInspired by this confidence,\nI fly unto thee,\nO Virgin of virgins, my Mother;\nto thee do I come,\nbefore thee I stand, sinful and sorrowful.\n\nO Mother of the Word Incarnate,\ndespise not my petitions,\nbut in thy mercy hear and answer me. Amen.',
          'pt-BR':
            'Lembrai-vos, ó piíssima Virgem Maria,\nque nunca se ouviu dizer\nque algum daqueles que recorreram à vossa proteção,\nimplorado o vosso auxílio\nou pedido vossa intercessão,\nfosse por Vós desamparado.\n\nAnimado eu, pois, de igual confiança,\na Vós, Virgem entre todas singular,\ncomo a Mãe recorro,\nde Vós me valho\ne, gemendo sob o peso de meus pecados,\nme prostro a vossos pés.\n\nNão desprezeis as minhas súplicas,\nó Mãe do Verbo encarnado,\nmas dignai-vos de ouvi-las propícia,\ne mostrai-vos sempre minha advogada\njunto ao divino Filho Jesus. Amém.',
          la: 'Memorare, O piissima Virgo Maria,\nnon esse auditum a saeculo,\nquemquam ad tua currentem praesidia,\ntua implorantem auxilia,\ntua petentem suffragia,\nesse derelictum.\n\nEgo tali animatus confidentia,\nad te, Virgo Virginum, Mater,\ncurro, ad te venio,\ncoram te gemens peccator assisto.\n\nNoli, Mater Verbi,\nverba mea despicere,\nsed audi propitia et exaudi. Amen.',
        },
      },
    ],
    id: 'prayer/memorare',
  },
  c5c6b5b2fd6c27da030874fb1586a0b858282dbf91c79b81e2a69f81d11d661c: {
    title: {
      'en-US': 'Angel of God',
      'pt-BR': 'Anjo de Deus',
      la: 'Angele Dei',
    },
    body: [
      {
        type: 'prayer',
        inline: {
          'en-US':
            "Angel of God, my guardian dear,\nto whom God's love commits me here,\never this day be at my side,\nto light and guard, to rule and guide. Amen.",
          'pt-BR':
            'Santo Anjo do Senhor, meu zeloso guardador,\nse a ti me confiou a piedade divina,\nsempre me rege, me guarda, me governa e me ilumina. Amém.',
          la: 'Angele Dei, qui custos es mei,\nme tibi commissum pietate superna,\nhodie illumina, custodi, rege et guberna. Amen.',
        },
      },
    ],
    id: 'prayer/angele-dei',
  },
  a29034cac748919c9984bbd7380760c07727da0a738a67b49e082eb8fdc5ff2f: {
    title: {
      'en-US': 'Fatima Prayer',
      'pt-BR': 'Oração de Fátima',
      la: 'Oratio Fatimensis',
    },
    body: [
      {
        type: 'prayer',
        inline: {
          'en-US':
            'O my Jesus, forgive us our sins,\nsave us from the fires of hell,\nlead all souls to heaven,\nespecially those most in need of thy mercy.',
          'pt-BR':
            'Ó meu Jesus, perdoai-nos,\nlivrai-nos do fogo do inferno,\nlevai as almas todas para o céu,\nprincipalmente aquelas que mais precisarem da vossa misericórdia.',
          la: 'O mi Iesu, dimítte nobis débita nostra,\nsalva nos ab igne inférni,\nperduc in cælum omnes ánimas,\npræsértim eas quæ misericórdiæ tuæ máxime indígent.',
        },
      },
    ],
    id: 'prayer/fatima-prayer',
  },
  e71556ec350a516903fc949411c168a55e3fec7510fcf20775429044ec01b18d: {
    title: {
      'en-US': 'Hail, Holy Queen',
      'pt-BR': 'Salve Rainha',
      la: 'Salve Regina',
    },
    body: [
      {
        type: 'prayer',
        inline: {
          'en-US':
            'Hail, Holy Queen, Mother of mercy,\nour life, our sweetness, and our hope.\nTo thee do we cry, poor banished children of Eve.\nTo thee do we send up our sighs,\nmourning and weeping in this valley of tears.\nTurn then, most gracious advocate,\nthine eyes of mercy toward us.\nAnd after this our exile,\nshow unto us the blessed fruit of thy womb, Jesus.\nO clement, O loving, O sweet Virgin Mary.',
          'pt-BR':
            'Salve, Rainha, Mãe de misericórdia,\nvida, doçura e esperança nossa, salve!\nA vós bradamos, os degredados filhos de Eva.\nA vós suspiramos, gemendo e chorando\nneste vale de lágrimas.\nEia, pois, advogada nossa,\nesses vossos olhos misericordiosos a nós volvei.\nE depois deste desterro,\nmostrai-nos Jesus, bendito fruto do vosso ventre.\nÓ clemente, ó piedosa, ó doce sempre Virgem Maria.',
          la: 'Salve, Regína, Mater misericórdiæ,\nvita, dulcédo, et spes nostra, salve.\nAd te clamámus, éxsules fílii Evæ.\nAd te suspirámus, geméntes et flentes\nin hac lacrimárum valle.\nEia ergo, advocáta nostra,\nillos tuos misericórdes óculos ad nos convérte.\nEt Iesum, benedíctum fructum ventris tui,\nnobis post hoc exsílium osténde.\nO clemens, o pia, o dulcis Virgo María.',
        },
      },
    ],
    id: 'prayer/hail-holy-queen',
  },
} as const
