/**
 * Embedded starter pack — registered into contentIndex at boot before the
 * remote catalog is fetched. Makes the app functional offline on first
 * launch with the most essential prayers.
 *
 * The data.ts module is auto-generated by scripts/build-starter.py.
 */
import { registerStaticEntry } from '../contentIndex'
import { registerStaticBlob } from '../store'
import { STARTER_BODIES, STARTER_ITEMS } from './data'

const TEXT_ENCODER = new TextEncoder()

let registered = false

export function registerStarter(): void {
  if (registered) return
  registered = true

  for (const [id, entry] of Object.entries(STARTER_ITEMS)) {
    registerStaticEntry(id, entry, STARTER_BODIES[entry.hash])
  }

  // Pre-fill the in-memory blob store with starter blobs so that prefetch /
  // pin operations targeting these hashes don't fall back to network.
  for (const [hash, body] of Object.entries(STARTER_BODIES)) {
    const bytes = TEXT_ENCODER.encode(JSON.stringify(body))
    registerStaticBlob(hash, bytes)
  }
}
