"""Tier 1 for Ps 4: a word-by-word interlinear rendered from the dossier's parse and glosses.json.

Run from the repo root:  python3.13 research/psalterium/ps004/interlinear.py
Writes research/psalterium/ps004/interlinear.md. A lemma missing from glosses.json shows as ??? so gaps are loud.
glosses.json is keyed by LatinCy's lemma; `formOverrides` fixes a gloss (and records a parser error) for one form.
"""

import json
from pathlib import Path

here = Path(__file__).resolve().parent
dossier = json.loads((here / 'dossier.json').read_text(encoding='utf-8'))
glossFile = here / 'glosses.json'
glosses = json.loads(glossFile.read_text(encoding='utf-8')) if glossFile.exists() else {'lemmas': {}, 'formOverrides': {}}

morphKeys = ['Case', 'Number', 'Gender', 'Person', 'Tense', 'Mood', 'Voice', 'VerbForm', 'Degree']


def shortMorph(morph):
    pairs = dict(p.split('=') for p in morph.split('|') if '=' in p)
    return ' '.join(pairs[k].lower() for k in morphKeys if k in pairs)


def main():
    out = ['# Ps 4 — interlinear (tier 1)\n', 'Generated by `interlinear.py` from `dossier.json` + `glosses.json`; do not edit.\n']
    missing = set()
    for verse in dossier['verses']:
        out.append(f"## {verse['id']}\n\n*{verse['latin']}*\n")
        out.append('| form | lemma | morphology | gloss |\n| --- | --- | --- | --- |')
        for colon in verse['cola']:
            if colon['mark']:
                out.append(f"| `{colon['mark']}` | | | |")
            for token in colon['tokens']:
                override = glosses['formOverrides'].get(token['form'].lower())
                gloss = override['gloss'] if override else glosses['lemmas'].get(token['lemma'])
                if not gloss:
                    missing.add(token['lemma'])
                lemma = override.get('lemma', token['lemma']) if override else token['lemma']
                morph = override.get('morph', shortMorph(token['morph'])) if override else shortMorph(token['morph'])
                flag = ' ⚑' if token.get('rare') else ''
                out.append(f"| {token['form']} | {lemma}{flag} | {token['pos'].lower()} {morph} | {gloss or '???'} |")
        out.append('')
    (here / 'interlinear.md').write_text('\n'.join(out), encoding='utf-8')
    print('missing glosses:', sorted(missing))


main()
