// Every translation is addressed by the Douay slugs the corpus files its books
// under. Each row: Douay slug, the Portuguese slug shared by the Claretian API
// and Lírio Católico, the book code catholicbible.online uses.
const rows: [string, string, string][] = [
  ['genesis', 'genesis', 'OT/Gen'],
  ['exodus', 'exodo', 'OT/Ex'],
  ['leviticus', 'levitico', 'OT/Lev'],
  ['numbers', 'numeros', 'OT/Num'],
  ['deuteronomy', 'deuteronomio', 'OT/Dt'],
  ['josue', 'josue', 'OT/Jos'],
  ['judges', 'juizes', 'OT/Judg'],
  ['ruth', 'rute', 'OT/Ru'],
  ['1-kings', 'i-samuel', 'OT/1_Kgs'],
  ['2-kings', 'ii-samuel', 'OT/2_Kgs'],
  ['3-kings', 'i-reis', 'OT/3_Kgs'],
  ['4-kings', 'ii-reis', 'OT/4_Kgs'],
  ['1-paralipomenon', 'i-cronicas', 'OT/1_Par'],
  ['2-paralipomenon', 'ii-cronicas', 'OT/2_Par'],
  ['1-esdras', 'esdras', 'OT/Esd'],
  ['2-esdras', 'neemias', 'OT/Neh'],
  ['tobias', 'tobias', 'OT/Tob'],
  ['judith', 'judite', 'OT/Jdt'],
  ['esther', 'ester', 'OT/Est'],
  ['job', 'jo', 'OT/Job'],
  ['psalms', 'salmos', 'OT/Ps'],
  ['proverbs', 'proverbios', 'OT/Prov'],
  ['ecclesiastes', 'eclesiastes', 'OT/Eccl'],
  ['canticles', 'cantico-dos-canticos', 'OT/Cant'],
  ['wisdom', 'sabedoria', 'OT/Wis'],
  ['ecclesiasticus', 'eclesiastico', 'OT/Eccle'],
  ['isaias', 'isaias', 'OT/Isa'],
  ['jeremias', 'jeremias', 'OT/Jer'],
  ['lamentations', 'lamentacoes', 'OT/Lam'],
  ['baruch', 'baruc', 'OT/Bar'],
  ['ezechiel', 'ezequiel', 'OT/Eze'],
  ['daniel', 'daniel', 'OT/Dan'],
  ['osee', 'oseias', 'OT/Os'],
  ['joel', 'joel', 'OT/Jo'],
  ['amos', 'amos', 'OT/Am'],
  ['abdias', 'abdias', 'OT/Abd'],
  ['jonas', 'jonas', 'OT/Jon'],
  ['micheas', 'miqueias', 'OT/Mic'],
  ['nahum', 'naum', 'OT/Nah'],
  ['habacuc', 'habacuc', 'OT/Hab'],
  ['sophonias', 'sofonias', 'OT/Sop'],
  ['aggeus', 'ageu', 'OT/Agg'],
  ['zacharias', 'zacarias', 'OT/Zac'],
  ['malachias', 'malaquias', 'OT/Mal'],
  ['1-machabees', 'i-macabeus', 'OT/1_Mac'],
  ['2-machabees', 'ii-macabeus', 'OT/2_Mac'],
  ['matthew', 'sao-mateus', 'NT/Mat'],
  ['mark', 'sao-marcos', 'NT/Mk'],
  ['luke', 'sao-lucas', 'NT/Lk'],
  ['john', 'sao-joao', 'NT/Jn'],
  ['acts', 'atos-dos-apostolos', 'NT/Act'],
  ['romans', 'romanos', 'NT/Rom'],
  ['1-corinthians', 'i-corintios', 'NT/1_Cor'],
  ['2-corinthians', 'ii-corintios', 'NT/2_Cor'],
  ['galatians', 'galatas', 'NT/Gal'],
  ['ephesians', 'efesios', 'NT/Eph'],
  ['philippians', 'filipenses', 'NT/Phl'],
  ['colossians', 'colossenses', 'NT/Col'],
  ['1-thessalonians', 'i-tessalonicenses', 'NT/1_Th'],
  ['2-thessalonians', 'ii-tessalonicenses', 'NT/2_Th'],
  ['1-timothy', 'i-timoteo', 'NT/1_Tim'],
  ['2-timothy', 'ii-timoteo', 'NT/2_Tim'],
  ['titus', 'tito', 'NT/Tit'],
  ['philemon', 'filemon', 'NT/Phm'],
  ['hebrews', 'hebreus', 'NT/Heb'],
  ['james', 'sao-tiago', 'NT/Jas'],
  ['1-peter', 'i-sao-pedro', 'NT/1_Pet'],
  ['2-peter', 'ii-sao-pedro', 'NT/2_Pet'],
  ['1-john', 'i-sao-joao', 'NT/1_Jn'],
  ['2-john', 'ii-sao-joao', 'NT/2_Jn'],
  ['3-john', 'iii-sao-joao', 'NT/3_Jn'],
  ['jude', 'sao-judas', 'NT/Jud'],
  ['apocalypse', 'apocalipse', 'NT/Apoc'],
]

export const portugueseSlug: Record<string, string> = Object.fromEntries(
  rows.map(([douay, portuguese]) => [douay, portuguese]),
)

export const knoxCode: Record<string, string> = Object.fromEntries(
  rows.map(([douay, , knox]) => [douay, knox]),
)
