// Where each book of the CNBB sits in the Biblia Clerus: the pages of a book in
// order, each with the first chapter it holds.
export const cnbbPages: Record<string, [number, string][]> = {
  matthew: [
    [1, 'jhd'],
    [11, 'jhe'],
    [19, 'jhf'],
    [26, 'jhg'],
  ],
  mark: [
    [1, 'jcy'],
    [8, 'jcz'],
    [15, 'jc0'],
  ],
  luke: [
    [1, 'iz4'],
    [7, 'iz5'],
    [12, 'i0a'],
    [20, 'i0b'],
  ],
  john: [
    [1, 'hun'],
    [8, 'huo'],
    [15, 'hup'],
  ],
  acts: [
    [1, 'c13'],
    [8, 'c14'],
    [15, 'c15'],
    [22, 'c2a'],
  ],
  romans: [
    [1, 'kkb'],
    [10, 'kkc'],
  ],
  '1-corinthians': [
    [1, 'b1x'],
    [12, 'b1y'],
  ],
  '2-corinthians': [
    [1, 'ccr'],
    [13, 'ccs'],
  ],
  galatians: [[1, 'grc']],
  ephesians: [[1, 'ghg']],
  philippians: [[1, 'j0l']],
  colossians: [[1, 'fxg']],
  '1-thessalonians': [[1, 'can']],
  '2-thessalonians': [[1, 'chb']],
  '1-timothy': [[1, 'caw']],
  '2-timothy': [[1, 'chk']],
  titus: [[1, 'ldy']],
  philemon: [[1, 'j0s']],
  hebrews: [
    [1, 'guh'],
    [12, 'gui'],
  ],
  james: [[1, 'hsb']],
  '1-peter': [[1, 'b32']],
  '2-peter': [[1, 'ceu']],
  '1-john': [[1, 'b2j']],
  '2-john': [[1, 'cdc']],
  '3-john': [[1, 'ciw']],
  jude: [[1, 'iyi']],
  apocalypse: [
    [1, 'dey'],
    [14, 'dez'],
  ],
  genesis: [
    [1, 'gr5'],
    [13, 'gsa'],
    [24, 'gsb'],
    [31, 'gsc'],
    [39, 'gsd'],
    [47, 'gse'],
  ],
  exodus: [
    [1, 'gkr'],
    [10, 'gks'],
    [19, 'gkt'],
    [29, 'gku'],
    [37, 'gkv'],
  ],
  leviticus: [
    [1, 'jaz'],
    [11, 'ja0'],
    [18, 'ja1'],
    [26, 'ja2'],
  ],
  numbers: [
    [1, 'jiv'],
    [8, 'jiw'],
    [16, 'jix'],
    [24, 'jiy'],
    [33, 'jiz'],
  ],
  deuteronomy: [
    [1, 'gen'],
    [8, 'geo'],
    [17, 'gep'],
    [28, 'geq'],
  ],
  josue: [
    [1, 'hvt'],
    [10, 'hvu'],
    [19, 'hvv'],
  ],
  judges: [
    [1, 'hti'],
    [9, 'htj'],
    [17, 'htk'],
  ],
  ruth: [[1, 'klu']],
  '1-kings': [
    [1, 'b5s'],
    [11, 'b5t'],
    [18, 'b5u'],
    [26, 'b5v'],
  ],
  '2-kings': [
    [1, 'cgi'],
    [11, 'cgj'],
    [18, 'cgk'],
  ],
  '3-kings': [
    [1, 'b4o'],
    [8, 'b4p'],
    [14, 'b4q'],
    [21, 'b4r'],
  ],
  '4-kings': [
    [1, 'cfg'],
    [9, 'cfh'],
    [17, 'cfi'],
    [24, 'cfj'],
  ],
  '1-paralipomenon': [
    [1, 'b01'],
    [10, 'b02'],
    [20, 'b03'],
  ],
  '2-paralipomenon': [
    [1, 'cbv'],
    [11, 'cbw'],
    [22, 'cbx'],
    [31, 'cby'],
  ],
  '1-esdras': [
    [1, 'gig'],
    [10, 'gih'],
  ],
  '2-esdras': [
    [1, 'jj3'],
    [10, 'jj4'],
  ],
  tobias: [
    [1, 'k53'],
    [11, 'k54'],
  ],
  judith: [
    [1, 'hsn'],
    [10, 'hso'],
  ],
  esther: [
    [1, 'gi3'],
    [9, 'gi4'],
  ],
  '1-machabees': [
    [1, 'b21'],
    [6, 'b22'],
    [11, 'b23'],
    [15, 'b24'],
  ],
  '2-machabees': [
    [1, 'cds'],
    [7, 'cdt'],
    [13, 'cdu'],
  ],
  job: [
    [1, 'hrl'],
    [15, 'hrm'],
    [31, 'hrn'],
  ],
  psalms: [
    [1, 'kbd'],
    [26, 'kbe'],
    [46, 'kbf'],
    [70, 'kbg'],
    [89, 'kbh'],
    [107, 'kbi'],
    [124, 'kbj'],
  ],
  proverbs: [
    [1, 'j5s'],
    [14, 'j5t'],
    [26, 'j5u'],
  ],
  ecclesiastes: [[1, 'kht']],
  canticles: [[1, 'f01']],
  wisdom: [
    [1, 'ks4'],
    [13, 'ks5'],
  ],
  ecclesiasticus: [
    [1, 'ktz'],
    [11, 'kt0'],
    [21, 'kt1'],
    [30, 'kt2'],
    [40, 'kt3'],
    [50, 'kt4'],
  ],
  isaias: [
    [1, 'hph'],
    [12, 'hpi'],
    [27, 'hpj'],
    [38, 'hpk'],
    [48, 'hpl'],
    [60, 'hpm'],
  ],
  jeremias: [
    [1, 'iw1'],
    [9, 'iw2'],
    [19, 'iw3'],
    [28, 'iw4'],
    [36, 'iw5'],
    [45, 'ixa'],
    [52, 'ixb'],
  ],
  lamentations: [[1, 'i31']],
  baruch: [[1, 'ekp']],
  ezechiel: [
    [1, 'gmd'],
    [13, 'gme'],
    [21, 'gmf'],
    [29, 'gmg'],
    [37, 'gmh'],
    [45, 'gmi'],
  ],
  daniel: [
    [1, 'f2v'],
    [6, 'f2w'],
    [14, 'f2x'],
  ],
  osee: [[1, 'jsj']],
  joel: [[1, 'ht3']],
  amos: [[1, 'dcd']],
  abdias: [[1, 'c1k']],
  jonas: [[1, 'hve']],
  micheas: [[1, 'jdu']],
  nahum: [[1, 'jh5']],
  habacuc: [[1, 'gt2']],
  sophonias: [[1, 'kvc']],
  aggeus: [[1, 'c25']],
  zacharias: [[1, 'lhp']],
  malachias: [[1, 'jfg']],
}
