#!/usr/bin/env python3
"""Build the embedded starter pack for Hearth v2.

Copies a small set of essential prayer JSONs from `content/prayers/` into a
single TypeScript module bundled into the app. This makes the app functional
on first launch with zero network — users can pray the essentials offline.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"
OUT = ROOT / "apps" / "app" / "src" / "content" / "starter" / "data.ts"

ESSENTIALS = [
    "sign-of-cross",
    "our-father",
    "hail-mary",
    "glory-be",
    "apostles-creed",
    "act-of-contrition",
    "anima-christi",
    "memorare",
    "angele-dei",
    "fatima-prayer",
    "hail-holy-queen",
]


def canonical_json(obj) -> bytes:
    return json.dumps(obj, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")


def main() -> int:
    items: dict[str, dict] = {}
    body_lookups: dict[str, dict] = {}
    for slug in ESSENTIALS:
        p = CONTENT / "prayers" / f"{slug}.json"
        if not p.is_file():
            print(f"warn: missing {p}", file=sys.stderr)
            continue
        with p.open(encoding="utf-8") as fh:
            payload = json.load(fh)
        # Build the same shape v2 emits: id + body fields
        body = {**payload, "id": f"prayer/{slug}"}
        bytes_ = canonical_json(body)
        h = hashlib.sha256(bytes_).hexdigest()
        items[f"prayer/{slug}"] = {
            "kind": "prayer",
            "hash": h,
            "size": len(bytes_),
        }
        body_lookups[h] = body

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as f:
        f.write("/* AUTO-GENERATED by scripts/build-starter.py — do not edit. */\n")
        f.write("import type { CatalogEntry } from '../manifestTypes'\n\n")
        f.write("export const STARTER_ITEMS: Record<string, CatalogEntry> = ")
        f.write(json.dumps(items, indent=2, ensure_ascii=False))
        f.write(" as const\n\n")
        f.write("export const STARTER_BODIES: Record<string, unknown> = ")
        f.write(json.dumps(body_lookups, indent=2, ensure_ascii=False))
        f.write(" as const\n")

    print(f"wrote {OUT.relative_to(ROOT)} with {len(items)} items")
    return 0


if __name__ == "__main__":
    sys.exit(main())
