"""Render a prayed tier: flat per-address texts for the critics (no translator's notes to bias them), and the praying sheet.

Run from the repo root:  python3.13 research/psalterium/render.py research/psalterium/ps004 4
Writes <workdir>/prayed.vos.json, <workdir>/prayed.tu.json and <workdir>/sheet.md.
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from latin import appPointing, doLatin, readVerses, resolve  # noqa: E402


def main():
    workdir, psalm = Path(sys.argv[1]), sys.argv[2]
    prayed = json.loads((workdir / 'prayed.json').read_text(encoding='utf-8'))
    # The address is settled as vós (2026-09-20); the flat text fills every {slot} with the translator's option 0.
    hasVariants = False
    flat = {'vos': resolve(prayed)}
    latin = {v['id']: v['text'] for v in readVerses(doLatin / f'Psalmorum/Psalm{psalm}.txt')}
    # what the blind readers get: the flat Portuguese, the Latin beside it, and a folder with the Portuguese alone
    (workdir / 'prayed.vos.json').write_text(json.dumps(flat['vos'], ensure_ascii=False, indent=2), encoding='utf-8')
    (workdir / 'latin.json').write_text(json.dumps(latin, ensure_ascii=False, indent=2), encoding='utf-8')
    (workdir / 'blind').mkdir(exist_ok=True)
    (workdir / 'blind' / 'prayed.vos.json').write_text(json.dumps(flat['vos'], ensure_ascii=False, indent=2), encoding='utf-8')
    sheet = [
        f'# Salmo {psalm}\n',
        f"Draft {prayed['version']} — not final. Pointing as Ember shows it (mediant `*` only).\n",
    ]
    for address, title in [('vos', 'Vós'), ('tu', 'Tu')]:
        if address not in flat:
            continue
        sheet.append(f'{"## " + title + chr(10) + chr(10) if hasVariants else ""}| | Latin | Português |\n| --- | --- | --- |')
        for vid, text in flat[address].items():
            star = lambda s: appPointing(s).replace('*', '\\*')  # noqa: E731
            sheet.append(f'| {vid} | {star(latin[vid])} | {star(text)} |')
        sheet.append('')
    (workdir / 'sheet.md').write_text('\n'.join(sheet), encoding='utf-8')

    # The Berean-style translation table: one row per prayed verse, every tier side by side.
    literalFile = workdir / 'literal.json'
    literal = json.loads(literalFile.read_text(encoding='utf-8'))['verses'] if literalFile.exists() else {}
    cell = lambda s: (s or '').replace('*', '\\*').replace('|', '\\|')  # noqa: E731
    table = [
        f'# Ps {psalm} — translation table\n',
        f"Generated by `render.py` from the DO Latin, `literal.json` and `prayed.json` (draft {prayed['version']}); do not edit. "
        'Word-level tier: `interlinear.md`. Model verdicts: `critic/`. Open human decisions: `decisions.md`.\n',
        '| | Latin | Literal (tier 2) | Prayed (tier 3) | Why |\n| --- | --- | --- | --- | --- |',
    ]
    for vid, shown in flat['vos'].items():
        table.append(f"| {vid} | {cell(latin[vid])} | {cell(literal.get(vid))} | {cell(shown)} | {cell(prayed.get('choices', {}).get(vid))} |")
    (workdir / 'table.md').write_text('\n'.join(table) + '\n', encoding='utf-8')


main()
