"""Concordance for a word study: every occurrence of a Latin word in Pss 1–150, with what stands behind and beside it.

Run from the repo root:
  python3.13 research/psalterium/words.py exaudire '^exaud' --greek 'ακου' --pt 'ouv|escut|atend|respond|exauc|acolh'
Writes research/psalterium/words/<name>.concordance.md and prints a summary. The judgement goes in words/<name>.md.

--greek  stem (accents stripped) to pull from the Rahlfs verse — shows which Greek verb Jerome had before him.
         Needs consult/lxx-*.csv. LXX and Vulgate psalm numbers agree; verse numbers mostly do, so a miss is
         reported as a miss, never guessed.
--pt     stems to look for in the aligned pt-PT line (content/do Portugues) — how the antecedent rendered it.
"""

import argparse
import re
import unicodedata
from collections import Counter
from pathlib import Path

from latin import doLatin, doPortugues, fold, readVerses

here = Path(__file__).resolve().parent
consult = here / 'consult'


def bare(text):
    return ''.join(c for c in unicodedata.normalize('NFD', text) if not unicodedata.combining(c)).lower()


def lxxByVerse():
    verseFile, wordFile = consult / 'lxx-E-verse.csv', consult / 'lxx-text_accented.csv'
    if not verseFile.exists():
        return {}
    starts = []
    for line in verseFile.read_text(encoding='utf-8').splitlines():
        index, _, ref = line.split('\t')
        starts.append((int(index), ref.strip('「」')))
    psalms = [(i, start, ref) for i, (start, ref) in enumerate(starts) if ref.startswith('Ps ') and not ref.startswith('PsSol')]
    first, last = psalms[0][1], starts[psalms[-1][0] + 1][0]
    words = {}
    for line in wordFile.read_text(encoding='utf-8').splitlines():
        fields = line.split('\t')
        if len(fields) == 3 and first <= int(fields[0]) < last:
            words[int(fields[0])] = fields[2]
    return {ref[3:]: [words[n] for n in range(start, starts[i + 1][0]) if n in words] for i, start, ref in psalms}


def position(text, start):
    """Where in the prayed verse the word falls: opening, before the mediant, after it, or at the close."""
    before, after = text[:start], text[start:]
    if not re.search(r'[a-zA-Z]', re.sub(r'\([^)]*\)', '', before)):
        return 'opens the verse'
    if not re.search(r'\s[^\s]*[a-zA-Z]', after):
        return 'closes the verse'
    return 'second half' if '*' in before else 'first half'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('name')
    parser.add_argument('pattern')
    parser.add_argument('--greek')
    parser.add_argument('--pt')
    args = parser.parse_args()
    pattern = re.compile(args.pattern)
    lxx = lxxByVerse() if args.greek else {}

    rows, forms, psalms, greek, portuguese, places = [], Counter(), Counter(), Counter(), Counter(), Counter()
    for psalm in range(1, 151):
        latin = readVerses(doLatin / f'Psalmorum/Psalm{psalm}.txt')
        antecedent = {v['id']: v['text'] for v in readVerses(doPortugues / f'Psalmorum/Psalm{psalm}.txt')}
        for verse in latin:
            for match in re.finditer(r"[^\W\d_]+", verse['text']):
                form = fold(match.group()).lower()
                if not pattern.search(form):
                    continue
                forms[form] += 1
                psalms[psalm] += 1
                places[position(verse['text'], match.start())] += 1
                greekHit = '—'
                if args.greek:
                    candidates = [w for w in lxx.get(f"{psalm}:{verse['verse']}", []) if re.search(args.greek, bare(w))]
                    greekHit = ', '.join(candidates) or 'no match in that LXX verse'
                    # tally by what the pattern's first group caught (a prefix such as εισ- / επ-), else by the stem
                    for w in candidates or ['(miss)']:
                        hit = re.search(args.greek, bare(w)) if candidates else None
                        greek[(hit.group(1) if hit.groups() else hit.group()) or '(simple)' if hit else w] += 1
                ptLine = antecedent.get(verse['id'], '')
                ptHit = sorted(set(re.findall(rf'\b\w*(?:{args.pt})\w*', ptLine.lower()))) if args.pt else []
                for stem in {re.search(args.pt, h).group() for h in ptHit} or {'(other)'}:
                    portuguese[stem] += 1
                shown = verse['text'][: match.start()] + '**' + match.group() + '**' + verse['text'][match.end() :]
                rows.append(f"| {verse['id']} | {shown.replace('*', chr(92) + '*').replace(chr(92) + '*' + chr(92) + '*', '**')} | {greekHit} | {ptLine.replace('*', chr(92) + '*')} |")

    total = sum(forms.values())
    out = [
        f'# {args.name} — concordance\n',
        f'Generated by `words.py {args.name} {args.pattern!r}`; do not edit. {total} occurrences in {len(psalms)} psalms (Pss 1–150, DO text).\n',
        '## Forms\n', '| form | n |\n| --- | --- |', *[f'| {f} | {n} |' for f, n in forms.most_common()], '',
        '## Where in the verse\n', '| place | n |\n| --- | --- |', *[f'| {p} | {n} |' for p, n in places.most_common()], '',
        '## Greek behind it (Rahlfs; tallied by the prefix the pattern caught)\n', '| stem | n |\n| --- | --- |', *[f'| {g} | {n} |' for g, n in greek.most_common()], '',
        '## pt-PT antecedent (DO Portugues), by stem found in the aligned line\n', '| stem | n |\n| --- | --- |', *[f'| {p} | {n} |' for p, n in portuguese.most_common()], '',
        '## Psalms with three or more\n', ', '.join(f'{p} (×{n})' for p, n in sorted(psalms.items()) if n >= 3) or 'none', '',
        '## Every occurrence\n', '| verse | Latin | Greek | pt-PT antecedent |\n| --- | --- | --- | --- |', *rows, '',
    ]
    target = here / 'words'
    target.mkdir(exist_ok=True)
    (target / f'{args.name}.concordance.md').write_text('\n'.join(out), encoding='utf-8')
    print(f'{args.name}: {total} in {len(psalms)} psalms')
    for title, counter in [('forms', forms), ('place', places), ('greek', greek), ('pt-PT', portuguese)]:
        print(f'  {title}: ' + ', '.join(f'{k} {n}' for k, n in counter.most_common(12)))


main()
